package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * AccPayType generated by hbm2java
 */
public class AccPayType  implements java.io.Serializable {


     private Integer idPayType;
     private String payTypeName;

    public AccPayType() {
    }

    public AccPayType(String payTypeName) {
       this.payTypeName = payTypeName;
    }
   
    public Integer getIdPayType() {
        return this.idPayType;
    }
    
    public void setIdPayType(Integer idPayType) {
        this.idPayType = idPayType;
    }
    public String getPayTypeName() {
        return this.payTypeName;
    }
    
    public void setPayTypeName(String payTypeName) {
        this.payTypeName = payTypeName;
    }




}


