package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Action generated by hbm2java
 */
public class Action  implements java.io.Serializable {


     private Integer idaction;
     private String action;
     private Set<ApprovalByHasAction> approvalByHasActions = new HashSet<ApprovalByHasAction>(0);
     private Set<DoOnAction> doOnActions = new HashSet<DoOnAction>(0);

    public Action() {
    }

    public Action(String action, Set<ApprovalByHasAction> approvalByHasActions, Set<DoOnAction> doOnActions) {
       this.action = action;
       this.approvalByHasActions = approvalByHasActions;
       this.doOnActions = doOnActions;
    }
   
    public Integer getIdaction() {
        return this.idaction;
    }
    
    public void setIdaction(Integer idaction) {
        this.idaction = idaction;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public Set<ApprovalByHasAction> getApprovalByHasActions() {
        return this.approvalByHasActions;
    }
    
    public void setApprovalByHasActions(Set<ApprovalByHasAction> approvalByHasActions) {
        this.approvalByHasActions = approvalByHasActions;
    }
    public Set<DoOnAction> getDoOnActions() {
        return this.doOnActions;
    }
    
    public void setDoOnActions(Set<DoOnAction> doOnActions) {
        this.doOnActions = doOnActions;
    }




}


