package pojo;
// Generated Jun 24, 2019 1:56:23 PM by Hibernate Tools 4.3.1



/**
 * AllDataSheetKuliya generated by hbm2java
 */
public class AllDataSheetKuliya  implements java.io.Serializable {


     private int idAssessment;
     private Double allocation;
     private Double quarterValue;
     private Double balance1231;
     private Double balance0331;

    public AllDataSheetKuliya() {
    }

	
    public AllDataSheetKuliya(int idAssessment) {
        this.idAssessment = idAssessment;
    }
    public AllDataSheetKuliya(int idAssessment, Double allocation, Double quarterValue, Double balance1231, Double balance0331) {
       this.idAssessment = idAssessment;
       this.allocation = allocation;
       this.quarterValue = quarterValue;
       this.balance1231 = balance1231;
       this.balance0331 = balance0331;
    }
   
    public int getIdAssessment() {
        return this.idAssessment;
    }
    
    public void setIdAssessment(int idAssessment) {
        this.idAssessment = idAssessment;
    }
    public Double getAllocation() {
        return this.allocation;
    }
    
    public void setAllocation(Double allocation) {
        this.allocation = allocation;
    }
    public Double getQuarterValue() {
        return this.quarterValue;
    }
    
    public void setQuarterValue(Double quarterValue) {
        this.quarterValue = quarterValue;
    }
    public Double getBalance1231() {
        return this.balance1231;
    }
    
    public void setBalance1231(Double balance1231) {
        this.balance1231 = balance1231;
    }
    public Double getBalance0331() {
        return this.balance0331;
    }
    
    public void setBalance0331(Double balance0331) {
        this.balance0331 = balance0331;
    }




}


