package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApproveTypes generated by hbm2java
 */
public class ApproveTypes  implements java.io.Serializable {


     private Integer idaptype;
     private String apType;
     private String module;
     private String view;
     private Set<ApprovalBy> approvalBies = new HashSet<ApprovalBy>(0);

    public ApproveTypes() {
    }

    public ApproveTypes(String apType, String module, String view, Set<ApprovalBy> approvalBies) {
       this.apType = apType;
       this.module = module;
       this.view = view;
       this.approvalBies = approvalBies;
    }
   
    public Integer getIdaptype() {
        return this.idaptype;
    }
    
    public void setIdaptype(Integer idaptype) {
        this.idaptype = idaptype;
    }
    public String getApType() {
        return this.apType;
    }
    
    public void setApType(String apType) {
        this.apType = apType;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public String getView() {
        return this.view;
    }
    
    public void setView(String view) {
        this.view = view;
    }
    public Set<ApprovalBy> getApprovalBies() {
        return this.approvalBies;
    }
    
    public void setApprovalBies(Set<ApprovalBy> approvalBies) {
        this.approvalBies = approvalBies;
    }




}


