package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1



/**
 * AssApptype generated by hbm2java
 */
public class AssApptype  implements java.io.Serializable {


     private Integer idAssApptype;
     private String typeName;

    public AssApptype() {
    }

    public AssApptype(String typeName) {
       this.typeName = typeName;
    }
   
    public Integer getIdAssApptype() {
        return this.idAssApptype;
    }
    
    public void setIdAssApptype(Integer idAssApptype) {
        this.idAssApptype = idAssApptype;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }




}


