package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * BaBuldingDetails generated by hbm2java
 */
public class BaBuldingDetails  implements java.io.Serializable {


     private Integer baBuldingDetailsId;
     private Integer baApplicationId;
     private Integer baFloorId;
     private Double baCurrent;
     private Double baPurpose;
     private Double baTotal;
     private String baFloorAreaType;
     private Long baPrice;
     private Integer baVat;
     private Integer baNbt;

    public BaBuldingDetails() {
    }

    public BaBuldingDetails(Integer baApplicationId, Integer baFloorId, Double baCurrent, Double baPurpose, Double baTotal, String baFloorAreaType, Long baPrice, Integer baVat, Integer baNbt) {
       this.baApplicationId = baApplicationId;
       this.baFloorId = baFloorId;
       this.baCurrent = baCurrent;
       this.baPurpose = baPurpose;
       this.baTotal = baTotal;
       this.baFloorAreaType = baFloorAreaType;
       this.baPrice = baPrice;
       this.baVat = baVat;
       this.baNbt = baNbt;
    }
   
    public Integer getBaBuldingDetailsId() {
        return this.baBuldingDetailsId;
    }
    
    public void setBaBuldingDetailsId(Integer baBuldingDetailsId) {
        this.baBuldingDetailsId = baBuldingDetailsId;
    }
    public Integer getBaApplicationId() {
        return this.baApplicationId;
    }
    
    public void setBaApplicationId(Integer baApplicationId) {
        this.baApplicationId = baApplicationId;
    }
    public Integer getBaFloorId() {
        return this.baFloorId;
    }
    
    public void setBaFloorId(Integer baFloorId) {
        this.baFloorId = baFloorId;
    }
    public Double getBaCurrent() {
        return this.baCurrent;
    }
    
    public void setBaCurrent(Double baCurrent) {
        this.baCurrent = baCurrent;
    }
    public Double getBaPurpose() {
        return this.baPurpose;
    }
    
    public void setBaPurpose(Double baPurpose) {
        this.baPurpose = baPurpose;
    }
    public Double getBaTotal() {
        return this.baTotal;
    }
    
    public void setBaTotal(Double baTotal) {
        this.baTotal = baTotal;
    }
    public String getBaFloorAreaType() {
        return this.baFloorAreaType;
    }
    
    public void setBaFloorAreaType(String baFloorAreaType) {
        this.baFloorAreaType = baFloorAreaType;
    }
    public Long getBaPrice() {
        return this.baPrice;
    }
    
    public void setBaPrice(Long baPrice) {
        this.baPrice = baPrice;
    }
    public Integer getBaVat() {
        return this.baVat;
    }
    
    public void setBaVat(Integer baVat) {
        this.baVat = baVat;
    }
    public Integer getBaNbt() {
        return this.baNbt;
    }
    
    public void setBaNbt(Integer baNbt) {
        this.baNbt = baNbt;
    }




}


