package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * BaDrafmanDetails generated by hbm2java
 */
public class BaDrafmanDetails  implements java.io.Serializable {


     private Integer baDrafmanDetailsId;
     private BaPersonalInformation baPersonalInformation;
     private String baDrafmanNameSinhala;
     private String baDrafmanNameEnglish;
     private String baDrafmanNic;
     private String baDrafmanMobile;
     private String baDrafmanAddressSinhala;
     private String baDrafmanAddressEnglish;

    public BaDrafmanDetails() {
    }

    public BaDrafmanDetails(BaPersonalInformation baPersonalInformation, String baDrafmanNameSinhala, String baDrafmanNameEnglish, String baDrafmanNic, String baDrafmanMobile, String baDrafmanAddressSinhala, String baDrafmanAddressEnglish) {
       this.baPersonalInformation = baPersonalInformation;
       this.baDrafmanNameSinhala = baDrafmanNameSinhala;
       this.baDrafmanNameEnglish = baDrafmanNameEnglish;
       this.baDrafmanNic = baDrafmanNic;
       this.baDrafmanMobile = baDrafmanMobile;
       this.baDrafmanAddressSinhala = baDrafmanAddressSinhala;
       this.baDrafmanAddressEnglish = baDrafmanAddressEnglish;
    }
   
    public Integer getBaDrafmanDetailsId() {
        return this.baDrafmanDetailsId;
    }
    
    public void setBaDrafmanDetailsId(Integer baDrafmanDetailsId) {
        this.baDrafmanDetailsId = baDrafmanDetailsId;
    }
    public BaPersonalInformation getBaPersonalInformation() {
        return this.baPersonalInformation;
    }
    
    public void setBaPersonalInformation(BaPersonalInformation baPersonalInformation) {
        this.baPersonalInformation = baPersonalInformation;
    }
    public String getBaDrafmanNameSinhala() {
        return this.baDrafmanNameSinhala;
    }
    
    public void setBaDrafmanNameSinhala(String baDrafmanNameSinhala) {
        this.baDrafmanNameSinhala = baDrafmanNameSinhala;
    }
    public String getBaDrafmanNameEnglish() {
        return this.baDrafmanNameEnglish;
    }
    
    public void setBaDrafmanNameEnglish(String baDrafmanNameEnglish) {
        this.baDrafmanNameEnglish = baDrafmanNameEnglish;
    }
    public String getBaDrafmanNic() {
        return this.baDrafmanNic;
    }
    
    public void setBaDrafmanNic(String baDrafmanNic) {
        this.baDrafmanNic = baDrafmanNic;
    }
    public String getBaDrafmanMobile() {
        return this.baDrafmanMobile;
    }
    
    public void setBaDrafmanMobile(String baDrafmanMobile) {
        this.baDrafmanMobile = baDrafmanMobile;
    }
    public String getBaDrafmanAddressSinhala() {
        return this.baDrafmanAddressSinhala;
    }
    
    public void setBaDrafmanAddressSinhala(String baDrafmanAddressSinhala) {
        this.baDrafmanAddressSinhala = baDrafmanAddressSinhala;
    }
    public String getBaDrafmanAddressEnglish() {
        return this.baDrafmanAddressEnglish;
    }
    
    public void setBaDrafmanAddressEnglish(String baDrafmanAddressEnglish) {
        this.baDrafmanAddressEnglish = baDrafmanAddressEnglish;
    }




}


