package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BaPersonalInformation generated by hbm2java
 */
public class BaPersonalInformation  implements java.io.Serializable {


     private Integer baPersonalDetailsId;
     private String baApplicationNumber;
     private Integer baBopId;
     private String baUdaAreaOrNot;
     private Integer baLaId;
     private Date baApplicationDate;
     private Integer baElectoralDistricId;
     private Integer baGnDivisionId;
     private String baTypeofApplicant;
     private String baConstrctionType;
     private Double baLandAcres;
     private Double baLandRoods;
     private String baSurveyorsName;
     private String baSurveyorsNo;
     private Date baSurveyorsDate;
     private String baLotNo;
     private String baLandCurrentDescription;
     private String baFloorCount;
     private String baBuildingHeight;
     private String baVehicleParkDescription;
     private String baWaterVolume;
     private String baElectricityCapacity;
     private String baNumberOfEmp;
     private Date baStartingDate;
     private Date baEndDate;
     private Integer baRdaAreaOrNot;
     private Set<BaUserDetails> baUserDetailses = new HashSet<BaUserDetails>(0);
     private Set<BaDrafmanDetails> baDrafmanDetailses = new HashSet<BaDrafmanDetails>(0);

    public BaPersonalInformation() {
    }

    public BaPersonalInformation(String baApplicationNumber, Integer baBopId, String baUdaAreaOrNot, Integer baLaId, Date baApplicationDate, Integer baElectoralDistricId, Integer baGnDivisionId, String baTypeofApplicant, String baConstrctionType, Double baLandAcres, Double baLandRoods, String baSurveyorsName, String baSurveyorsNo, Date baSurveyorsDate, String baLotNo, String baLandCurrentDescription, String baFloorCount, String baBuildingHeight, String baVehicleParkDescription, String baWaterVolume, String baElectricityCapacity, String baNumberOfEmp, Date baStartingDate, Date baEndDate, Integer baRdaAreaOrNot, Set<BaUserDetails> baUserDetailses, Set<BaDrafmanDetails> baDrafmanDetailses) {
       this.baApplicationNumber = baApplicationNumber;
       this.baBopId = baBopId;
       this.baUdaAreaOrNot = baUdaAreaOrNot;
       this.baLaId = baLaId;
       this.baApplicationDate = baApplicationDate;
       this.baElectoralDistricId = baElectoralDistricId;
       this.baGnDivisionId = baGnDivisionId;
       this.baTypeofApplicant = baTypeofApplicant;
       this.baConstrctionType = baConstrctionType;
       this.baLandAcres = baLandAcres;
       this.baLandRoods = baLandRoods;
       this.baSurveyorsName = baSurveyorsName;
       this.baSurveyorsNo = baSurveyorsNo;
       this.baSurveyorsDate = baSurveyorsDate;
       this.baLotNo = baLotNo;
       this.baLandCurrentDescription = baLandCurrentDescription;
       this.baFloorCount = baFloorCount;
       this.baBuildingHeight = baBuildingHeight;
       this.baVehicleParkDescription = baVehicleParkDescription;
       this.baWaterVolume = baWaterVolume;
       this.baElectricityCapacity = baElectricityCapacity;
       this.baNumberOfEmp = baNumberOfEmp;
       this.baStartingDate = baStartingDate;
       this.baEndDate = baEndDate;
       this.baRdaAreaOrNot = baRdaAreaOrNot;
       this.baUserDetailses = baUserDetailses;
       this.baDrafmanDetailses = baDrafmanDetailses;
    }
   
    public Integer getBaPersonalDetailsId() {
        return this.baPersonalDetailsId;
    }
    
    public void setBaPersonalDetailsId(Integer baPersonalDetailsId) {
        this.baPersonalDetailsId = baPersonalDetailsId;
    }
    public String getBaApplicationNumber() {
        return this.baApplicationNumber;
    }
    
    public void setBaApplicationNumber(String baApplicationNumber) {
        this.baApplicationNumber = baApplicationNumber;
    }
    public Integer getBaBopId() {
        return this.baBopId;
    }
    
    public void setBaBopId(Integer baBopId) {
        this.baBopId = baBopId;
    }
    public String getBaUdaAreaOrNot() {
        return this.baUdaAreaOrNot;
    }
    
    public void setBaUdaAreaOrNot(String baUdaAreaOrNot) {
        this.baUdaAreaOrNot = baUdaAreaOrNot;
    }
    public Integer getBaLaId() {
        return this.baLaId;
    }
    
    public void setBaLaId(Integer baLaId) {
        this.baLaId = baLaId;
    }
    public Date getBaApplicationDate() {
        return this.baApplicationDate;
    }
    
    public void setBaApplicationDate(Date baApplicationDate) {
        this.baApplicationDate = baApplicationDate;
    }
    public Integer getBaElectoralDistricId() {
        return this.baElectoralDistricId;
    }
    
    public void setBaElectoralDistricId(Integer baElectoralDistricId) {
        this.baElectoralDistricId = baElectoralDistricId;
    }
    public Integer getBaGnDivisionId() {
        return this.baGnDivisionId;
    }
    
    public void setBaGnDivisionId(Integer baGnDivisionId) {
        this.baGnDivisionId = baGnDivisionId;
    }
    public String getBaTypeofApplicant() {
        return this.baTypeofApplicant;
    }
    
    public void setBaTypeofApplicant(String baTypeofApplicant) {
        this.baTypeofApplicant = baTypeofApplicant;
    }
    public String getBaConstrctionType() {
        return this.baConstrctionType;
    }
    
    public void setBaConstrctionType(String baConstrctionType) {
        this.baConstrctionType = baConstrctionType;
    }
    public Double getBaLandAcres() {
        return this.baLandAcres;
    }
    
    public void setBaLandAcres(Double baLandAcres) {
        this.baLandAcres = baLandAcres;
    }
    public Double getBaLandRoods() {
        return this.baLandRoods;
    }
    
    public void setBaLandRoods(Double baLandRoods) {
        this.baLandRoods = baLandRoods;
    }
    public String getBaSurveyorsName() {
        return this.baSurveyorsName;
    }
    
    public void setBaSurveyorsName(String baSurveyorsName) {
        this.baSurveyorsName = baSurveyorsName;
    }
    public String getBaSurveyorsNo() {
        return this.baSurveyorsNo;
    }
    
    public void setBaSurveyorsNo(String baSurveyorsNo) {
        this.baSurveyorsNo = baSurveyorsNo;
    }
    public Date getBaSurveyorsDate() {
        return this.baSurveyorsDate;
    }
    
    public void setBaSurveyorsDate(Date baSurveyorsDate) {
        this.baSurveyorsDate = baSurveyorsDate;
    }
    public String getBaLotNo() {
        return this.baLotNo;
    }
    
    public void setBaLotNo(String baLotNo) {
        this.baLotNo = baLotNo;
    }
    public String getBaLandCurrentDescription() {
        return this.baLandCurrentDescription;
    }
    
    public void setBaLandCurrentDescription(String baLandCurrentDescription) {
        this.baLandCurrentDescription = baLandCurrentDescription;
    }
    public String getBaFloorCount() {
        return this.baFloorCount;
    }
    
    public void setBaFloorCount(String baFloorCount) {
        this.baFloorCount = baFloorCount;
    }
    public String getBaBuildingHeight() {
        return this.baBuildingHeight;
    }
    
    public void setBaBuildingHeight(String baBuildingHeight) {
        this.baBuildingHeight = baBuildingHeight;
    }
    public String getBaVehicleParkDescription() {
        return this.baVehicleParkDescription;
    }
    
    public void setBaVehicleParkDescription(String baVehicleParkDescription) {
        this.baVehicleParkDescription = baVehicleParkDescription;
    }
    public String getBaWaterVolume() {
        return this.baWaterVolume;
    }
    
    public void setBaWaterVolume(String baWaterVolume) {
        this.baWaterVolume = baWaterVolume;
    }
    public String getBaElectricityCapacity() {
        return this.baElectricityCapacity;
    }
    
    public void setBaElectricityCapacity(String baElectricityCapacity) {
        this.baElectricityCapacity = baElectricityCapacity;
    }
    public String getBaNumberOfEmp() {
        return this.baNumberOfEmp;
    }
    
    public void setBaNumberOfEmp(String baNumberOfEmp) {
        this.baNumberOfEmp = baNumberOfEmp;
    }
    public Date getBaStartingDate() {
        return this.baStartingDate;
    }
    
    public void setBaStartingDate(Date baStartingDate) {
        this.baStartingDate = baStartingDate;
    }
    public Date getBaEndDate() {
        return this.baEndDate;
    }
    
    public void setBaEndDate(Date baEndDate) {
        this.baEndDate = baEndDate;
    }
    public Integer getBaRdaAreaOrNot() {
        return this.baRdaAreaOrNot;
    }
    
    public void setBaRdaAreaOrNot(Integer baRdaAreaOrNot) {
        this.baRdaAreaOrNot = baRdaAreaOrNot;
    }
    public Set<BaUserDetails> getBaUserDetailses() {
        return this.baUserDetailses;
    }
    
    public void setBaUserDetailses(Set<BaUserDetails> baUserDetailses) {
        this.baUserDetailses = baUserDetailses;
    }
    public Set<BaDrafmanDetails> getBaDrafmanDetailses() {
        return this.baDrafmanDetailses;
    }
    
    public void setBaDrafmanDetailses(Set<BaDrafmanDetails> baDrafmanDetailses) {
        this.baDrafmanDetailses = baDrafmanDetailses;
    }




}


