package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * BaUserDetails generated by hbm2java
 */
public class BaUserDetails  implements java.io.Serializable {


     private Integer baUserDetailsId;
     private BaPersonalInformation baPersonalInformation;
     private Integer baCustomerId;
     private String baUserNameInsinhala;
     private String baUserNameInenglish;
     private String baUserAddress;
     private String baUserMobile;
     private String baUserEmail;

    public BaUserDetails() {
    }

    public BaUserDetails(BaPersonalInformation baPersonalInformation, Integer baCustomerId, String baUserNameInsinhala, String baUserNameInenglish, String baUserAddress, String baUserMobile, String baUserEmail) {
       this.baPersonalInformation = baPersonalInformation;
       this.baCustomerId = baCustomerId;
       this.baUserNameInsinhala = baUserNameInsinhala;
       this.baUserNameInenglish = baUserNameInenglish;
       this.baUserAddress = baUserAddress;
       this.baUserMobile = baUserMobile;
       this.baUserEmail = baUserEmail;
    }
   
    public Integer getBaUserDetailsId() {
        return this.baUserDetailsId;
    }
    
    public void setBaUserDetailsId(Integer baUserDetailsId) {
        this.baUserDetailsId = baUserDetailsId;
    }
    public BaPersonalInformation getBaPersonalInformation() {
        return this.baPersonalInformation;
    }
    
    public void setBaPersonalInformation(BaPersonalInformation baPersonalInformation) {
        this.baPersonalInformation = baPersonalInformation;
    }
    public Integer getBaCustomerId() {
        return this.baCustomerId;
    }
    
    public void setBaCustomerId(Integer baCustomerId) {
        this.baCustomerId = baCustomerId;
    }
    public String getBaUserNameInsinhala() {
        return this.baUserNameInsinhala;
    }
    
    public void setBaUserNameInsinhala(String baUserNameInsinhala) {
        this.baUserNameInsinhala = baUserNameInsinhala;
    }
    public String getBaUserNameInenglish() {
        return this.baUserNameInenglish;
    }
    
    public void setBaUserNameInenglish(String baUserNameInenglish) {
        this.baUserNameInenglish = baUserNameInenglish;
    }
    public String getBaUserAddress() {
        return this.baUserAddress;
    }
    
    public void setBaUserAddress(String baUserAddress) {
        this.baUserAddress = baUserAddress;
    }
    public String getBaUserMobile() {
        return this.baUserMobile;
    }
    
    public void setBaUserMobile(String baUserMobile) {
        this.baUserMobile = baUserMobile;
    }
    public String getBaUserEmail() {
        return this.baUserEmail;
    }
    
    public void setBaUserEmail(String baUserEmail) {
        this.baUserEmail = baUserEmail;
    }




}


