package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * BopHasAssessment generated by hbm2java
 */
public class BopHasAssessment  implements java.io.Serializable {


     private Integer idBopHasAssessmentcol;
     private Assessment assessment;
     private Bop bop;
     private Integer bopHasAssessmentStatus;
     private Double size;
     private Double price;
     private String comment;
     private String lotNo;

    public BopHasAssessment() {
    }

	
    public BopHasAssessment(Assessment assessment, Bop bop) {
        this.assessment = assessment;
        this.bop = bop;
    }
    public BopHasAssessment(Assessment assessment, Bop bop, Integer bopHasAssessmentStatus, Double size, Double price, String comment, String lotNo) {
       this.assessment = assessment;
       this.bop = bop;
       this.bopHasAssessmentStatus = bopHasAssessmentStatus;
       this.size = size;
       this.price = price;
       this.comment = comment;
       this.lotNo = lotNo;
    }
   
    public Integer getIdBopHasAssessmentcol() {
        return this.idBopHasAssessmentcol;
    }
    
    public void setIdBopHasAssessmentcol(Integer idBopHasAssessmentcol) {
        this.idBopHasAssessmentcol = idBopHasAssessmentcol;
    }
    public Assessment getAssessment() {
        return this.assessment;
    }
    
    public void setAssessment(Assessment assessment) {
        this.assessment = assessment;
    }
    public Bop getBop() {
        return this.bop;
    }
    
    public void setBop(Bop bop) {
        this.bop = bop;
    }
    public Integer getBopHasAssessmentStatus() {
        return this.bopHasAssessmentStatus;
    }
    
    public void setBopHasAssessmentStatus(Integer bopHasAssessmentStatus) {
        this.bopHasAssessmentStatus = bopHasAssessmentStatus;
    }
    public Double getSize() {
        return this.size;
    }
    
    public void setSize(Double size) {
        this.size = size;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getLotNo() {
        return this.lotNo;
    }
    
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo;
    }




}


