package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * BopPaymentCalculation generated by hbm2java
 */
public class BopPaymentCalculation  implements java.io.Serializable {


     private Integer calPaymentId;
     private Integer lotsOfLand;
     private Double landStartSize;
     private Double landEndSize;
     private Double price;

    public BopPaymentCalculation() {
    }

    public BopPaymentCalculation(Integer lotsOfLand, Double landStartSize, Double landEndSize, Double price) {
       this.lotsOfLand = lotsOfLand;
       this.landStartSize = landStartSize;
       this.landEndSize = landEndSize;
       this.price = price;
    }
   
    public Integer getCalPaymentId() {
        return this.calPaymentId;
    }
    
    public void setCalPaymentId(Integer calPaymentId) {
        this.calPaymentId = calPaymentId;
    }
    public Integer getLotsOfLand() {
        return this.lotsOfLand;
    }
    
    public void setLotsOfLand(Integer lotsOfLand) {
        this.lotsOfLand = lotsOfLand;
    }
    public Double getLandStartSize() {
        return this.landStartSize;
    }
    
    public void setLandStartSize(Double landStartSize) {
        this.landStartSize = landStartSize;
    }
    public Double getLandEndSize() {
        return this.landEndSize;
    }
    
    public void setLandEndSize(Double landEndSize) {
        this.landEndSize = landEndSize;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


