package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CustomersWbtBill generated by hbm2java
 */
public class CustomersWbtBill  implements java.io.Serializable {


     private String customerId;
     private String customerNic;
     private String assmntTaxNo;
     private Date regDate;
     private String customerName;
     private String customerAddress;
     private String customerPhone1;
     private String customerPhone2;
     private String mainRoad;
     private String subRoad;
     private String supplyType;
     private String subscriberType;
     private String ownerName;
     private String ownerAddress;
     private String renterName;
     private String renterAddress;
     private BigDecimal securityDeposit;
     private BigDecimal estimatedAmount;
     private boolean customerStatus;
     private int readerId;
     private int orderNumber;
     private boolean activeStatus;
     private Boolean printedStatus;
     private Boolean billingType;

    public CustomersWbtBill() {
    }

	
    public CustomersWbtBill(String customerId, String customerNic, String assmntTaxNo, String customerName, String customerAddress, String customerPhone1, String customerPhone2, String mainRoad, String subRoad, String supplyType, String subscriberType, String ownerName, String ownerAddress, String renterName, String renterAddress, BigDecimal securityDeposit, BigDecimal estimatedAmount, boolean customerStatus, int readerId, int orderNumber, boolean activeStatus) {
        this.customerId = customerId;
        this.customerNic = customerNic;
        this.assmntTaxNo = assmntTaxNo;
        this.customerName = customerName;
        this.customerAddress = customerAddress;
        this.customerPhone1 = customerPhone1;
        this.customerPhone2 = customerPhone2;
        this.mainRoad = mainRoad;
        this.subRoad = subRoad;
        this.supplyType = supplyType;
        this.subscriberType = subscriberType;
        this.ownerName = ownerName;
        this.ownerAddress = ownerAddress;
        this.renterName = renterName;
        this.renterAddress = renterAddress;
        this.securityDeposit = securityDeposit;
        this.estimatedAmount = estimatedAmount;
        this.customerStatus = customerStatus;
        this.readerId = readerId;
        this.orderNumber = orderNumber;
        this.activeStatus = activeStatus;
    }
    public CustomersWbtBill(String customerId, String customerNic, String assmntTaxNo, Date regDate, String customerName, String customerAddress, String customerPhone1, String customerPhone2, String mainRoad, String subRoad, String supplyType, String subscriberType, String ownerName, String ownerAddress, String renterName, String renterAddress, BigDecimal securityDeposit, BigDecimal estimatedAmount, boolean customerStatus, int readerId, int orderNumber, boolean activeStatus, Boolean printedStatus, Boolean billingType) {
       this.customerId = customerId;
       this.customerNic = customerNic;
       this.assmntTaxNo = assmntTaxNo;
       this.regDate = regDate;
       this.customerName = customerName;
       this.customerAddress = customerAddress;
       this.customerPhone1 = customerPhone1;
       this.customerPhone2 = customerPhone2;
       this.mainRoad = mainRoad;
       this.subRoad = subRoad;
       this.supplyType = supplyType;
       this.subscriberType = subscriberType;
       this.ownerName = ownerName;
       this.ownerAddress = ownerAddress;
       this.renterName = renterName;
       this.renterAddress = renterAddress;
       this.securityDeposit = securityDeposit;
       this.estimatedAmount = estimatedAmount;
       this.customerStatus = customerStatus;
       this.readerId = readerId;
       this.orderNumber = orderNumber;
       this.activeStatus = activeStatus;
       this.printedStatus = printedStatus;
       this.billingType = billingType;
    }
   
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getCustomerNic() {
        return this.customerNic;
    }
    
    public void setCustomerNic(String customerNic) {
        this.customerNic = customerNic;
    }
    public String getAssmntTaxNo() {
        return this.assmntTaxNo;
    }
    
    public void setAssmntTaxNo(String assmntTaxNo) {
        this.assmntTaxNo = assmntTaxNo;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    public String getCustomerPhone1() {
        return this.customerPhone1;
    }
    
    public void setCustomerPhone1(String customerPhone1) {
        this.customerPhone1 = customerPhone1;
    }
    public String getCustomerPhone2() {
        return this.customerPhone2;
    }
    
    public void setCustomerPhone2(String customerPhone2) {
        this.customerPhone2 = customerPhone2;
    }
    public String getMainRoad() {
        return this.mainRoad;
    }
    
    public void setMainRoad(String mainRoad) {
        this.mainRoad = mainRoad;
    }
    public String getSubRoad() {
        return this.subRoad;
    }
    
    public void setSubRoad(String subRoad) {
        this.subRoad = subRoad;
    }
    public String getSupplyType() {
        return this.supplyType;
    }
    
    public void setSupplyType(String supplyType) {
        this.supplyType = supplyType;
    }
    public String getSubscriberType() {
        return this.subscriberType;
    }
    
    public void setSubscriberType(String subscriberType) {
        this.subscriberType = subscriberType;
    }
    public String getOwnerName() {
        return this.ownerName;
    }
    
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    public String getOwnerAddress() {
        return this.ownerAddress;
    }
    
    public void setOwnerAddress(String ownerAddress) {
        this.ownerAddress = ownerAddress;
    }
    public String getRenterName() {
        return this.renterName;
    }
    
    public void setRenterName(String renterName) {
        this.renterName = renterName;
    }
    public String getRenterAddress() {
        return this.renterAddress;
    }
    
    public void setRenterAddress(String renterAddress) {
        this.renterAddress = renterAddress;
    }
    public BigDecimal getSecurityDeposit() {
        return this.securityDeposit;
    }
    
    public void setSecurityDeposit(BigDecimal securityDeposit) {
        this.securityDeposit = securityDeposit;
    }
    public BigDecimal getEstimatedAmount() {
        return this.estimatedAmount;
    }
    
    public void setEstimatedAmount(BigDecimal estimatedAmount) {
        this.estimatedAmount = estimatedAmount;
    }
    public boolean isCustomerStatus() {
        return this.customerStatus;
    }
    
    public void setCustomerStatus(boolean customerStatus) {
        this.customerStatus = customerStatus;
    }
    public int getReaderId() {
        return this.readerId;
    }
    
    public void setReaderId(int readerId) {
        this.readerId = readerId;
    }
    public int getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(int orderNumber) {
        this.orderNumber = orderNumber;
    }
    public boolean isActiveStatus() {
        return this.activeStatus;
    }
    
    public void setActiveStatus(boolean activeStatus) {
        this.activeStatus = activeStatus;
    }
    public Boolean getPrintedStatus() {
        return this.printedStatus;
    }
    
    public void setPrintedStatus(Boolean printedStatus) {
        this.printedStatus = printedStatus;
    }
    public Boolean getBillingType() {
        return this.billingType;
    }
    
    public void setBillingType(Boolean billingType) {
        this.billingType = billingType;
    }




}


