package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1



/**
 * CustomerHasApplicationCatagory generated by hbm2java
 */
public class CustomerHasApplicationCatagory  implements java.io.Serializable {


     private Integer idCustomerHasApplicationCatagory;
     private ApplicationCatagory applicationCatagory;
     private Customer customer;
     private Integer customerHasApplicationCatagoryStatus;
     private Integer customerHasApplicationCatagorySyn;

    public CustomerHasApplicationCatagory() {
    }

	
    public CustomerHasApplicationCatagory(ApplicationCatagory applicationCatagory, Customer customer) {
        this.applicationCatagory = applicationCatagory;
        this.customer = customer;
    }
    public CustomerHasApplicationCatagory(ApplicationCatagory applicationCatagory, Customer customer, Integer customerHasApplicationCatagoryStatus, Integer customerHasApplicationCatagorySyn) {
       this.applicationCatagory = applicationCatagory;
       this.customer = customer;
       this.customerHasApplicationCatagoryStatus = customerHasApplicationCatagoryStatus;
       this.customerHasApplicationCatagorySyn = customerHasApplicationCatagorySyn;
    }
   
    public Integer getIdCustomerHasApplicationCatagory() {
        return this.idCustomerHasApplicationCatagory;
    }
    
    public void setIdCustomerHasApplicationCatagory(Integer idCustomerHasApplicationCatagory) {
        this.idCustomerHasApplicationCatagory = idCustomerHasApplicationCatagory;
    }
    public ApplicationCatagory getApplicationCatagory() {
        return this.applicationCatagory;
    }
    
    public void setApplicationCatagory(ApplicationCatagory applicationCatagory) {
        this.applicationCatagory = applicationCatagory;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Integer getCustomerHasApplicationCatagoryStatus() {
        return this.customerHasApplicationCatagoryStatus;
    }
    
    public void setCustomerHasApplicationCatagoryStatus(Integer customerHasApplicationCatagoryStatus) {
        this.customerHasApplicationCatagoryStatus = customerHasApplicationCatagoryStatus;
    }
    public Integer getCustomerHasApplicationCatagorySyn() {
        return this.customerHasApplicationCatagorySyn;
    }
    
    public void setCustomerHasApplicationCatagorySyn(Integer customerHasApplicationCatagorySyn) {
        this.customerHasApplicationCatagorySyn = customerHasApplicationCatagorySyn;
    }




}


