package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * DoOnActionHasAttributes generated by hbm2java
 */
public class DoOnActionHasAttributes  implements java.io.Serializable {


     private DoOnActionHasAttributesId id;
     private Attributes attributes;
     private DoOnAction doOnAction;

    public DoOnActionHasAttributes() {
    }

    public DoOnActionHasAttributes(DoOnActionHasAttributesId id, Attributes attributes, DoOnAction doOnAction) {
       this.id = id;
       this.attributes = attributes;
       this.doOnAction = doOnAction;
    }
   
    public DoOnActionHasAttributesId getId() {
        return this.id;
    }
    
    public void setId(DoOnActionHasAttributesId id) {
        this.id = id;
    }
    public Attributes getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(Attributes attributes) {
        this.attributes = attributes;
    }
    public DoOnAction getDoOnAction() {
        return this.doOnAction;
    }
    
    public void setDoOnAction(DoOnAction doOnAction) {
        this.doOnAction = doOnAction;
    }




}


