package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExBankDeposit generated by hbm2java
 */
public class ExBankDeposit  implements java.io.Serializable {


     private Integer exBankDepositId;
     private Integer exBankAccountId;
     private Date exDepositDate;
     private Double exTotalCashAmount;
     private Double exTotalChequeAmount;
     private Integer exDepositStatus;

    public ExBankDeposit() {
    }

    public ExBankDeposit(Integer exBankAccountId, Date exDepositDate, Double exTotalCashAmount, Double exTotalChequeAmount, Integer exDepositStatus) {
       this.exBankAccountId = exBankAccountId;
       this.exDepositDate = exDepositDate;
       this.exTotalCashAmount = exTotalCashAmount;
       this.exTotalChequeAmount = exTotalChequeAmount;
       this.exDepositStatus = exDepositStatus;
    }
   
    public Integer getExBankDepositId() {
        return this.exBankDepositId;
    }
    
    public void setExBankDepositId(Integer exBankDepositId) {
        this.exBankDepositId = exBankDepositId;
    }
    public Integer getExBankAccountId() {
        return this.exBankAccountId;
    }
    
    public void setExBankAccountId(Integer exBankAccountId) {
        this.exBankAccountId = exBankAccountId;
    }
    public Date getExDepositDate() {
        return this.exDepositDate;
    }
    
    public void setExDepositDate(Date exDepositDate) {
        this.exDepositDate = exDepositDate;
    }
    public Double getExTotalCashAmount() {
        return this.exTotalCashAmount;
    }
    
    public void setExTotalCashAmount(Double exTotalCashAmount) {
        this.exTotalCashAmount = exTotalCashAmount;
    }
    public Double getExTotalChequeAmount() {
        return this.exTotalChequeAmount;
    }
    
    public void setExTotalChequeAmount(Double exTotalChequeAmount) {
        this.exTotalChequeAmount = exTotalChequeAmount;
    }
    public Integer getExDepositStatus() {
        return this.exDepositStatus;
    }
    
    public void setExDepositStatus(Integer exDepositStatus) {
        this.exDepositStatus = exDepositStatus;
    }




}


