package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * ExBalanceSheetOpeningBalance generated by hbm2java
 */
public class ExBalanceSheetOpeningBalance  implements java.io.Serializable {


     private Integer exSubtitleOpenBalanceId;
     private Integer exSubTitleId;
     private String exYear;
     private Double exOpeningBalance;
     private Integer exActiveStatus;

    public ExBalanceSheetOpeningBalance() {
    }

    public ExBalanceSheetOpeningBalance(Integer exSubTitleId, String exYear, Double exOpeningBalance, Integer exActiveStatus) {
       this.exSubTitleId = exSubTitleId;
       this.exYear = exYear;
       this.exOpeningBalance = exOpeningBalance;
       this.exActiveStatus = exActiveStatus;
    }
   
    public Integer getExSubtitleOpenBalanceId() {
        return this.exSubtitleOpenBalanceId;
    }
    
    public void setExSubtitleOpenBalanceId(Integer exSubtitleOpenBalanceId) {
        this.exSubtitleOpenBalanceId = exSubtitleOpenBalanceId;
    }
    public Integer getExSubTitleId() {
        return this.exSubTitleId;
    }
    
    public void setExSubTitleId(Integer exSubTitleId) {
        this.exSubTitleId = exSubTitleId;
    }
    public String getExYear() {
        return this.exYear;
    }
    
    public void setExYear(String exYear) {
        this.exYear = exYear;
    }
    public Double getExOpeningBalance() {
        return this.exOpeningBalance;
    }
    
    public void setExOpeningBalance(Double exOpeningBalance) {
        this.exOpeningBalance = exOpeningBalance;
    }
    public Integer getExActiveStatus() {
        return this.exActiveStatus;
    }
    
    public void setExActiveStatus(Integer exActiveStatus) {
        this.exActiveStatus = exActiveStatus;
    }




}


