package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * ExChequeForVoucher generated by hbm2java
 */
public class ExChequeForVoucher  implements java.io.Serializable {


     private Integer exSingleChequeDetailsId;
     private Integer exVoucherInfoId;
     private String exChequeNo;
     private Integer exActiveStatus;

    public ExChequeForVoucher() {
    }

    public ExChequeForVoucher(Integer exVoucherInfoId, String exChequeNo, Integer exActiveStatus) {
       this.exVoucherInfoId = exVoucherInfoId;
       this.exChequeNo = exChequeNo;
       this.exActiveStatus = exActiveStatus;
    }
   
    public Integer getExSingleChequeDetailsId() {
        return this.exSingleChequeDetailsId;
    }
    
    public void setExSingleChequeDetailsId(Integer exSingleChequeDetailsId) {
        this.exSingleChequeDetailsId = exSingleChequeDetailsId;
    }
    public Integer getExVoucherInfoId() {
        return this.exVoucherInfoId;
    }
    
    public void setExVoucherInfoId(Integer exVoucherInfoId) {
        this.exVoucherInfoId = exVoucherInfoId;
    }
    public String getExChequeNo() {
        return this.exChequeNo;
    }
    
    public void setExChequeNo(String exChequeNo) {
        this.exChequeNo = exChequeNo;
    }
    public Integer getExActiveStatus() {
        return this.exActiveStatus;
    }
    
    public void setExActiveStatus(Integer exActiveStatus) {
        this.exActiveStatus = exActiveStatus;
    }




}


