package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * ExDuty generated by hbm2java
 */
public class ExDuty  implements java.io.Serializable {


     private Integer exDutyId;
     private Integer exDutyUserId;
     private Integer exDutyLocationId;
     private Integer exDutyStatus;

    public ExDuty() {
    }

    public ExDuty(Integer exDutyUserId, Integer exDutyLocationId, Integer exDutyStatus) {
       this.exDutyUserId = exDutyUserId;
       this.exDutyLocationId = exDutyLocationId;
       this.exDutyStatus = exDutyStatus;
    }
   
    public Integer getExDutyId() {
        return this.exDutyId;
    }
    
    public void setExDutyId(Integer exDutyId) {
        this.exDutyId = exDutyId;
    }
    public Integer getExDutyUserId() {
        return this.exDutyUserId;
    }
    
    public void setExDutyUserId(Integer exDutyUserId) {
        this.exDutyUserId = exDutyUserId;
    }
    public Integer getExDutyLocationId() {
        return this.exDutyLocationId;
    }
    
    public void setExDutyLocationId(Integer exDutyLocationId) {
        this.exDutyLocationId = exDutyLocationId;
    }
    public Integer getExDutyStatus() {
        return this.exDutyStatus;
    }
    
    public void setExDutyStatus(Integer exDutyStatus) {
        this.exDutyStatus = exDutyStatus;
    }




}


