package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * ExForms generated by hbm2java
 */
public class ExForms  implements java.io.Serializable {


     private Integer exFormId;
     private String exFormName;
     private String exDescription;

    public ExForms() {
    }

    public ExForms(String exFormName, String exDescription) {
       this.exFormName = exFormName;
       this.exDescription = exDescription;
    }
   
    public Integer getExFormId() {
        return this.exFormId;
    }
    
    public void setExFormId(Integer exFormId) {
        this.exFormId = exFormId;
    }
    public String getExFormName() {
        return this.exFormName;
    }
    
    public void setExFormName(String exFormName) {
        this.exFormName = exFormName;
    }
    public String getExDescription() {
        return this.exDescription;
    }
    
    public void setExDescription(String exDescription) {
        this.exDescription = exDescription;
    }




}


