package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * ExNature generated by hbm2java
 */
public class ExNature  implements java.io.Serializable {


     private Integer exNatureId;
     private String exNatureDescription;

    public ExNature() {
    }

    public ExNature(String exNatureDescription) {
       this.exNatureDescription = exNatureDescription;
    }
   
    public Integer getExNatureId() {
        return this.exNatureId;
    }
    
    public void setExNatureId(Integer exNatureId) {
        this.exNatureId = exNatureId;
    }
    public String getExNatureDescription() {
        return this.exNatureDescription;
    }
    
    public void setExNatureDescription(String exNatureDescription) {
        this.exNatureDescription = exNatureDescription;
    }




}


