package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * ExPriveliageTag generated by hbm2java
 */
public class ExPriveliageTag  implements java.io.Serializable {


     private Integer exControlId;
     private String exTagIdName;
     private String exTagDescription;
     private Integer exActiveStatus;
     private Integer exFormId;

    public ExPriveliageTag() {
    }

    public ExPriveliageTag(String exTagIdName, String exTagDescription, Integer exActiveStatus, Integer exFormId) {
       this.exTagIdName = exTagIdName;
       this.exTagDescription = exTagDescription;
       this.exActiveStatus = exActiveStatus;
       this.exFormId = exFormId;
    }
   
    public Integer getExControlId() {
        return this.exControlId;
    }
    
    public void setExControlId(Integer exControlId) {
        this.exControlId = exControlId;
    }
    public String getExTagIdName() {
        return this.exTagIdName;
    }
    
    public void setExTagIdName(String exTagIdName) {
        this.exTagIdName = exTagIdName;
    }
    public String getExTagDescription() {
        return this.exTagDescription;
    }
    
    public void setExTagDescription(String exTagDescription) {
        this.exTagDescription = exTagDescription;
    }
    public Integer getExActiveStatus() {
        return this.exActiveStatus;
    }
    
    public void setExActiveStatus(Integer exActiveStatus) {
        this.exActiveStatus = exActiveStatus;
    }
    public Integer getExFormId() {
        return this.exFormId;
    }
    
    public void setExFormId(Integer exFormId) {
        this.exFormId = exFormId;
    }




}


