package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExReciptDeduct generated by hbm2java
 */
public class ExReciptDeduct  implements java.io.Serializable {


     private Integer exDepositDeductId;
     private Integer exVoucherInfoId;
     private Double exDeductAmount;
     private Date exDeductDate;
     private Integer exApproveStatus;
     private Integer exActiveStatus;
     private Integer exGridGridId;
     private Integer exReciptId;

    public ExReciptDeduct() {
    }

    public ExReciptDeduct(Integer exVoucherInfoId, Double exDeductAmount, Date exDeductDate, Integer exApproveStatus, Integer exActiveStatus, Integer exGridGridId, Integer exReciptId) {
       this.exVoucherInfoId = exVoucherInfoId;
       this.exDeductAmount = exDeductAmount;
       this.exDeductDate = exDeductDate;
       this.exApproveStatus = exApproveStatus;
       this.exActiveStatus = exActiveStatus;
       this.exGridGridId = exGridGridId;
       this.exReciptId = exReciptId;
    }
   
    public Integer getExDepositDeductId() {
        return this.exDepositDeductId;
    }
    
    public void setExDepositDeductId(Integer exDepositDeductId) {
        this.exDepositDeductId = exDepositDeductId;
    }
    public Integer getExVoucherInfoId() {
        return this.exVoucherInfoId;
    }
    
    public void setExVoucherInfoId(Integer exVoucherInfoId) {
        this.exVoucherInfoId = exVoucherInfoId;
    }
    public Double getExDeductAmount() {
        return this.exDeductAmount;
    }
    
    public void setExDeductAmount(Double exDeductAmount) {
        this.exDeductAmount = exDeductAmount;
    }
    public Date getExDeductDate() {
        return this.exDeductDate;
    }
    
    public void setExDeductDate(Date exDeductDate) {
        this.exDeductDate = exDeductDate;
    }
    public Integer getExApproveStatus() {
        return this.exApproveStatus;
    }
    
    public void setExApproveStatus(Integer exApproveStatus) {
        this.exApproveStatus = exApproveStatus;
    }
    public Integer getExActiveStatus() {
        return this.exActiveStatus;
    }
    
    public void setExActiveStatus(Integer exActiveStatus) {
        this.exActiveStatus = exActiveStatus;
    }
    public Integer getExGridGridId() {
        return this.exGridGridId;
    }
    
    public void setExGridGridId(Integer exGridGridId) {
        this.exGridGridId = exGridGridId;
    }
    public Integer getExReciptId() {
        return this.exReciptId;
    }
    
    public void setExReciptId(Integer exReciptId) {
        this.exReciptId = exReciptId;
    }




}


