package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * ExTitle generated by hbm2java
 */
public class ExTitle  implements java.io.Serializable {


     private Integer idexProgramTitle;
     private Program program;
     private String exTitleNo;
     private String exTitleNameSin;
     private String exTitleNameEng;
     private String exTitleNameTamil;
     private Integer exStatusProgramTitle;
     private Integer exSynProgramTitle;
     private Integer exProjectId;
     private Integer exIncomeOrExpence;

    public ExTitle() {
    }

	
    public ExTitle(Program program) {
        this.program = program;
    }
    public ExTitle(Program program, String exTitleNo, String exTitleNameSin, String exTitleNameEng, String exTitleNameTamil, Integer exStatusProgramTitle, Integer exSynProgramTitle, Integer exProjectId, Integer exIncomeOrExpence) {
       this.program = program;
       this.exTitleNo = exTitleNo;
       this.exTitleNameSin = exTitleNameSin;
       this.exTitleNameEng = exTitleNameEng;
       this.exTitleNameTamil = exTitleNameTamil;
       this.exStatusProgramTitle = exStatusProgramTitle;
       this.exSynProgramTitle = exSynProgramTitle;
       this.exProjectId = exProjectId;
       this.exIncomeOrExpence = exIncomeOrExpence;
    }
   
    public Integer getIdexProgramTitle() {
        return this.idexProgramTitle;
    }
    
    public void setIdexProgramTitle(Integer idexProgramTitle) {
        this.idexProgramTitle = idexProgramTitle;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public String getExTitleNo() {
        return this.exTitleNo;
    }
    
    public void setExTitleNo(String exTitleNo) {
        this.exTitleNo = exTitleNo;
    }
    public String getExTitleNameSin() {
        return this.exTitleNameSin;
    }
    
    public void setExTitleNameSin(String exTitleNameSin) {
        this.exTitleNameSin = exTitleNameSin;
    }
    public String getExTitleNameEng() {
        return this.exTitleNameEng;
    }
    
    public void setExTitleNameEng(String exTitleNameEng) {
        this.exTitleNameEng = exTitleNameEng;
    }
    public String getExTitleNameTamil() {
        return this.exTitleNameTamil;
    }
    
    public void setExTitleNameTamil(String exTitleNameTamil) {
        this.exTitleNameTamil = exTitleNameTamil;
    }
    public Integer getExStatusProgramTitle() {
        return this.exStatusProgramTitle;
    }
    
    public void setExStatusProgramTitle(Integer exStatusProgramTitle) {
        this.exStatusProgramTitle = exStatusProgramTitle;
    }
    public Integer getExSynProgramTitle() {
        return this.exSynProgramTitle;
    }
    
    public void setExSynProgramTitle(Integer exSynProgramTitle) {
        this.exSynProgramTitle = exSynProgramTitle;
    }
    public Integer getExProjectId() {
        return this.exProjectId;
    }
    
    public void setExProjectId(Integer exProjectId) {
        this.exProjectId = exProjectId;
    }
    public Integer getExIncomeOrExpence() {
        return this.exIncomeOrExpence;
    }
    
    public void setExIncomeOrExpence(Integer exIncomeOrExpence) {
        this.exIncomeOrExpence = exIncomeOrExpence;
    }




}


