package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * ExUserCatPriviliages generated by hbm2java
 */
public class ExUserCatPriviliages  implements java.io.Serializable {


     private Integer exUserCatPriviliageId;
     private Integer exUserCatId;
     private Integer exPriviliageId;
     private Integer exActiveStatus;
     private Integer isSelect;

    public ExUserCatPriviliages() {
    }

    public ExUserCatPriviliages(Integer exUserCatId, Integer exPriviliageId, Integer exActiveStatus, Integer isSelect) {
       this.exUserCatId = exUserCatId;
       this.exPriviliageId = exPriviliageId;
       this.exActiveStatus = exActiveStatus;
       this.isSelect = isSelect;
    }
   
    public Integer getExUserCatPriviliageId() {
        return this.exUserCatPriviliageId;
    }
    
    public void setExUserCatPriviliageId(Integer exUserCatPriviliageId) {
        this.exUserCatPriviliageId = exUserCatPriviliageId;
    }
    public Integer getExUserCatId() {
        return this.exUserCatId;
    }
    
    public void setExUserCatId(Integer exUserCatId) {
        this.exUserCatId = exUserCatId;
    }
    public Integer getExPriviliageId() {
        return this.exPriviliageId;
    }
    
    public void setExPriviliageId(Integer exPriviliageId) {
        this.exPriviliageId = exPriviliageId;
    }
    public Integer getExActiveStatus() {
        return this.exActiveStatus;
    }
    
    public void setExActiveStatus(Integer exActiveStatus) {
        this.exActiveStatus = exActiveStatus;
    }
    public Integer getIsSelect() {
        return this.isSelect;
    }
    
    public void setIsSelect(Integer isSelect) {
        this.isSelect = isSelect;
    }




}


