package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * Fxkeyvalue generated by hbm2java
 */
public class Fxkeyvalue  implements java.io.Serializable {


     private int id;
     private String key;
     private String value;
     private String commnet;

    public Fxkeyvalue() {
    }

	
    public Fxkeyvalue(int id) {
        this.id = id;
    }
    public Fxkeyvalue(int id, String key, String value, String commnet) {
       this.id = id;
       this.key = key;
       this.value = value;
       this.commnet = commnet;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getCommnet() {
        return this.commnet;
    }
    
    public void setCommnet(String commnet) {
        this.commnet = commnet;
    }




}


