package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Job generated by hbm2java
 */
public class Job  implements java.io.Serializable {


     private Integer idJob;
     private String jobNumber;
     private String jobName;
     private Integer jobTypeId;
     private String jobDescription;
     private String jobInstruction;
     private Integer jobDipId;
     private Date jobDedline;
     private Date jobCreateDatetime;
     private Integer jobStatus;
     private Integer jobCat;
     private String jobCatName;
     private String cusName;
     private String cusEmail;
     private String cusMobile;

    public Job() {
    }

    public Job(String jobNumber, String jobName, Integer jobTypeId, String jobDescription, String jobInstruction, Integer jobDipId, Date jobDedline, Date jobCreateDatetime, Integer jobStatus, Integer jobCat, String jobCatName, String cusName, String cusEmail, String cusMobile) {
       this.jobNumber = jobNumber;
       this.jobName = jobName;
       this.jobTypeId = jobTypeId;
       this.jobDescription = jobDescription;
       this.jobInstruction = jobInstruction;
       this.jobDipId = jobDipId;
       this.jobDedline = jobDedline;
       this.jobCreateDatetime = jobCreateDatetime;
       this.jobStatus = jobStatus;
       this.jobCat = jobCat;
       this.jobCatName = jobCatName;
       this.cusName = cusName;
       this.cusEmail = cusEmail;
       this.cusMobile = cusMobile;
    }
   
    public Integer getIdJob() {
        return this.idJob;
    }
    
    public void setIdJob(Integer idJob) {
        this.idJob = idJob;
    }
    public String getJobNumber() {
        return this.jobNumber;
    }
    
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    public Integer getJobTypeId() {
        return this.jobTypeId;
    }
    
    public void setJobTypeId(Integer jobTypeId) {
        this.jobTypeId = jobTypeId;
    }
    public String getJobDescription() {
        return this.jobDescription;
    }
    
    public void setJobDescription(String jobDescription) {
        this.jobDescription = jobDescription;
    }
    public String getJobInstruction() {
        return this.jobInstruction;
    }
    
    public void setJobInstruction(String jobInstruction) {
        this.jobInstruction = jobInstruction;
    }
    public Integer getJobDipId() {
        return this.jobDipId;
    }
    
    public void setJobDipId(Integer jobDipId) {
        this.jobDipId = jobDipId;
    }
    public Date getJobDedline() {
        return this.jobDedline;
    }
    
    public void setJobDedline(Date jobDedline) {
        this.jobDedline = jobDedline;
    }
    public Date getJobCreateDatetime() {
        return this.jobCreateDatetime;
    }
    
    public void setJobCreateDatetime(Date jobCreateDatetime) {
        this.jobCreateDatetime = jobCreateDatetime;
    }
    public Integer getJobStatus() {
        return this.jobStatus;
    }
    
    public void setJobStatus(Integer jobStatus) {
        this.jobStatus = jobStatus;
    }
    public Integer getJobCat() {
        return this.jobCat;
    }
    
    public void setJobCat(Integer jobCat) {
        this.jobCat = jobCat;
    }
    public String getJobCatName() {
        return this.jobCatName;
    }
    
    public void setJobCatName(String jobCatName) {
        this.jobCatName = jobCatName;
    }
    public String getCusName() {
        return this.cusName;
    }
    
    public void setCusName(String cusName) {
        this.cusName = cusName;
    }
    public String getCusEmail() {
        return this.cusEmail;
    }
    
    public void setCusEmail(String cusEmail) {
        this.cusEmail = cusEmail;
    }
    public String getCusMobile() {
        return this.cusMobile;
    }
    
    public void setCusMobile(String cusMobile) {
        this.cusMobile = cusMobile;
    }




}


