package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * OnlineCus generated by hbm2java
 */
public class OnlineCus  implements java.io.Serializable {


     private Integer idOnline;
     private String fullname;
     private String nic;
     private String email;
     private String mobile;
     private String pword;
     private Integer status;
     private String code;

    public OnlineCus() {
    }

    public OnlineCus(String fullname, String nic, String email, String mobile, String pword, Integer status, String code) {
       this.fullname = fullname;
       this.nic = nic;
       this.email = email;
       this.mobile = mobile;
       this.pword = pword;
       this.status = status;
       this.code = code;
    }
   
    public Integer getIdOnline() {
        return this.idOnline;
    }
    
    public void setIdOnline(Integer idOnline) {
        this.idOnline = idOnline;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getPword() {
        return this.pword;
    }
    
    public void setPword(String pword) {
        this.pword = pword;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }




}


