package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PersonTitle generated by hbm2java
 */
public class PersonTitle  implements java.io.Serializable {


     private Integer titleId;
     private String titleName;
     private String titleNameEng;
     private Set<Bop> bops = new HashSet<Bop>(0);

    public PersonTitle() {
    }

    public PersonTitle(String titleName, String titleNameEng, Set<Bop> bops) {
       this.titleName = titleName;
       this.titleNameEng = titleNameEng;
       this.bops = bops;
    }
   
    public Integer getTitleId() {
        return this.titleId;
    }
    
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }
    public String getTitleName() {
        return this.titleName;
    }
    
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }
    public String getTitleNameEng() {
        return this.titleNameEng;
    }
    
    public void setTitleNameEng(String titleNameEng) {
        this.titleNameEng = titleNameEng;
    }
    public Set<Bop> getBops() {
        return this.bops;
    }
    
    public void setBops(Set<Bop> bops) {
        this.bops = bops;
    }




}


