package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * PrivilegesOtherSoft generated by hbm2java
 */
public class PrivilegesOtherSoft  implements java.io.Serializable {


     private Integer otherPrivilegesId;
     private Privilage privilage;
     private Integer privilegesOrder;
     private String privilegesImage;
     private Integer appCategory;
     private Integer privilegeCallIdInSystem;
     private byte[] image;

    public PrivilegesOtherSoft() {
    }

    public PrivilegesOtherSoft(Privilage privilage, Integer privilegesOrder, String privilegesImage, Integer appCategory, Integer privilegeCallIdInSystem, byte[] image) {
       this.privilage = privilage;
       this.privilegesOrder = privilegesOrder;
       this.privilegesImage = privilegesImage;
       this.appCategory = appCategory;
       this.privilegeCallIdInSystem = privilegeCallIdInSystem;
       this.image = image;
    }
   
    public Integer getOtherPrivilegesId() {
        return this.otherPrivilegesId;
    }
    
    public void setOtherPrivilegesId(Integer otherPrivilegesId) {
        this.otherPrivilegesId = otherPrivilegesId;
    }
    public Privilage getPrivilage() {
        return this.privilage;
    }
    
    public void setPrivilage(Privilage privilage) {
        this.privilage = privilage;
    }
    public Integer getPrivilegesOrder() {
        return this.privilegesOrder;
    }
    
    public void setPrivilegesOrder(Integer privilegesOrder) {
        this.privilegesOrder = privilegesOrder;
    }
    public String getPrivilegesImage() {
        return this.privilegesImage;
    }
    
    public void setPrivilegesImage(String privilegesImage) {
        this.privilegesImage = privilegesImage;
    }
    public Integer getAppCategory() {
        return this.appCategory;
    }
    
    public void setAppCategory(Integer appCategory) {
        this.appCategory = appCategory;
    }
    public Integer getPrivilegeCallIdInSystem() {
        return this.privilegeCallIdInSystem;
    }
    
    public void setPrivilegeCallIdInSystem(Integer privilegeCallIdInSystem) {
        this.privilegeCallIdInSystem = privilegeCallIdInSystem;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


