package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * ProgramSubtitleCopy generated by hbm2java
 */
public class ProgramSubtitleCopy  implements java.io.Serializable {


     private Integer idProgramSubTitle;
     private ProgramTitle programTitle;
     private String subTitleNo;
     private String subTitleName;
     private Integer status;
     private Integer syn;

    public ProgramSubtitleCopy() {
    }

	
    public ProgramSubtitleCopy(ProgramTitle programTitle) {
        this.programTitle = programTitle;
    }
    public ProgramSubtitleCopy(ProgramTitle programTitle, String subTitleNo, String subTitleName, Integer status, Integer syn) {
       this.programTitle = programTitle;
       this.subTitleNo = subTitleNo;
       this.subTitleName = subTitleName;
       this.status = status;
       this.syn = syn;
    }
   
    public Integer getIdProgramSubTitle() {
        return this.idProgramSubTitle;
    }
    
    public void setIdProgramSubTitle(Integer idProgramSubTitle) {
        this.idProgramSubTitle = idProgramSubTitle;
    }
    public ProgramTitle getProgramTitle() {
        return this.programTitle;
    }
    
    public void setProgramTitle(ProgramTitle programTitle) {
        this.programTitle = programTitle;
    }
    public String getSubTitleNo() {
        return this.subTitleNo;
    }
    
    public void setSubTitleNo(String subTitleNo) {
        this.subTitleNo = subTitleNo;
    }
    public String getSubTitleName() {
        return this.subTitleName;
    }
    
    public void setSubTitleName(String subTitleName) {
        this.subTitleName = subTitleName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }




}


