package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class Program  implements java.io.Serializable {


     private Integer idProgram;
     private String nameProgram;
     private String programcol;
     private Integer statusProgram;
     private Integer synProgram;
     private Set<ProgramTitle> programTitles = new HashSet<ProgramTitle>(0);
     private Set<ProgramTitleCopy> programTitleCopies = new HashSet<ProgramTitleCopy>(0);

    public Program() {
    }

    public Program(String nameProgram, String programcol, Integer statusProgram, Integer synProgram, Set<ProgramTitle> programTitles, Set<ProgramTitleCopy> programTitleCopies) {
       this.nameProgram = nameProgram;
       this.programcol = programcol;
       this.statusProgram = statusProgram;
       this.synProgram = synProgram;
       this.programTitles = programTitles;
       this.programTitleCopies = programTitleCopies;
    }
   
    public Integer getIdProgram() {
        return this.idProgram;
    }
    
    public void setIdProgram(Integer idProgram) {
        this.idProgram = idProgram;
    }
    public String getNameProgram() {
        return this.nameProgram;
    }
    
    public void setNameProgram(String nameProgram) {
        this.nameProgram = nameProgram;
    }
    public String getProgramcol() {
        return this.programcol;
    }
    
    public void setProgramcol(String programcol) {
        this.programcol = programcol;
    }
    public Integer getStatusProgram() {
        return this.statusProgram;
    }
    
    public void setStatusProgram(Integer statusProgram) {
        this.statusProgram = statusProgram;
    }
    public Integer getSynProgram() {
        return this.synProgram;
    }
    
    public void setSynProgram(Integer synProgram) {
        this.synProgram = synProgram;
    }
    public Set<ProgramTitle> getProgramTitles() {
        return this.programTitles;
    }
    
    public void setProgramTitles(Set<ProgramTitle> programTitles) {
        this.programTitles = programTitles;
    }
    public Set<ProgramTitleCopy> getProgramTitleCopies() {
        return this.programTitleCopies;
    }
    
    public void setProgramTitleCopies(Set<ProgramTitleCopy> programTitleCopies) {
        this.programTitleCopies = programTitleCopies;
    }




}


