package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Receipt generated by hbm2java
 */
public class Receipt  implements java.io.Serializable {


     private Integer idReceipt;
     private ApplicationCatagory applicationCatagory;
     private User user;
     private Integer receptApplicationId;
     private String receiptPrintNo;
     private Double cheack;
     private Double cesh;
     private Double receiptTotal;
     private Date receiptDay;
     private Integer receiptStatus;
     private Integer receiptSyn;
     private String chqueNo;
     private Date chqueDate;
     private String chqueBank;
     private Integer oder;
     private Integer officeIdOffice;
     private Integer receiptAccountId;
     private String ribno;
     private Date receiptTime;
     private Integer incomeExpense;
     private Integer cusId;
     private Integer crossReciptOrVoucher;
     private Integer payType;
     private Double amount;
     private Set<Cheack> cheacks = new HashSet<Cheack>(0);
     private Set<WbTPayment> wbTPayments = new HashSet<WbTPayment>(0);
     private Set<WbTPaid> wbTPaids = new HashSet<WbTPaid>(0);
     private Set<AssPayment> assPayments = new HashSet<AssPayment>(0);

    public Receipt() {
    }

	
    public Receipt(ApplicationCatagory applicationCatagory) {
        this.applicationCatagory = applicationCatagory;
    }
    public Receipt(ApplicationCatagory applicationCatagory, User user, Integer receptApplicationId, String receiptPrintNo, Double cheack, Double cesh, Double receiptTotal, Date receiptDay, Integer receiptStatus, Integer receiptSyn, String chqueNo, Date chqueDate, String chqueBank, Integer oder, Integer officeIdOffice, Integer receiptAccountId, String ribno, Date receiptTime, Integer incomeExpense, Integer cusId, Integer crossReciptOrVoucher, Integer payType, Double amount, Set<Cheack> cheacks, Set<WbTPayment> wbTPayments, Set<WbTPaid> wbTPaids, Set<AssPayment> assPayments) {
       this.applicationCatagory = applicationCatagory;
       this.user = user;
       this.receptApplicationId = receptApplicationId;
       this.receiptPrintNo = receiptPrintNo;
       this.cheack = cheack;
       this.cesh = cesh;
       this.receiptTotal = receiptTotal;
       this.receiptDay = receiptDay;
       this.receiptStatus = receiptStatus;
       this.receiptSyn = receiptSyn;
       this.chqueNo = chqueNo;
       this.chqueDate = chqueDate;
       this.chqueBank = chqueBank;
       this.oder = oder;
       this.officeIdOffice = officeIdOffice;
       this.receiptAccountId = receiptAccountId;
       this.ribno = ribno;
       this.receiptTime = receiptTime;
       this.incomeExpense = incomeExpense;
       this.cusId = cusId;
       this.crossReciptOrVoucher = crossReciptOrVoucher;
       this.payType = payType;
       this.amount = amount;
       this.cheacks = cheacks;
       this.wbTPayments = wbTPayments;
       this.wbTPaids = wbTPaids;
       this.assPayments = assPayments;
    }
   
    public Integer getIdReceipt() {
        return this.idReceipt;
    }
    
    public void setIdReceipt(Integer idReceipt) {
        this.idReceipt = idReceipt;
    }
    public ApplicationCatagory getApplicationCatagory() {
        return this.applicationCatagory;
    }
    
    public void setApplicationCatagory(ApplicationCatagory applicationCatagory) {
        this.applicationCatagory = applicationCatagory;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getReceptApplicationId() {
        return this.receptApplicationId;
    }
    
    public void setReceptApplicationId(Integer receptApplicationId) {
        this.receptApplicationId = receptApplicationId;
    }
    public String getReceiptPrintNo() {
        return this.receiptPrintNo;
    }
    
    public void setReceiptPrintNo(String receiptPrintNo) {
        this.receiptPrintNo = receiptPrintNo;
    }
    public Double getCheack() {
        return this.cheack;
    }
    
    public void setCheack(Double cheack) {
        this.cheack = cheack;
    }
    public Double getCesh() {
        return this.cesh;
    }
    
    public void setCesh(Double cesh) {
        this.cesh = cesh;
    }
    public Double getReceiptTotal() {
        return this.receiptTotal;
    }
    
    public void setReceiptTotal(Double receiptTotal) {
        this.receiptTotal = receiptTotal;
    }
    public Date getReceiptDay() {
        return this.receiptDay;
    }
    
    public void setReceiptDay(Date receiptDay) {
        this.receiptDay = receiptDay;
    }
    public Integer getReceiptStatus() {
        return this.receiptStatus;
    }
    
    public void setReceiptStatus(Integer receiptStatus) {
        this.receiptStatus = receiptStatus;
    }
    public Integer getReceiptSyn() {
        return this.receiptSyn;
    }
    
    public void setReceiptSyn(Integer receiptSyn) {
        this.receiptSyn = receiptSyn;
    }
    public String getChqueNo() {
        return this.chqueNo;
    }
    
    public void setChqueNo(String chqueNo) {
        this.chqueNo = chqueNo;
    }
    public Date getChqueDate() {
        return this.chqueDate;
    }
    
    public void setChqueDate(Date chqueDate) {
        this.chqueDate = chqueDate;
    }
    public String getChqueBank() {
        return this.chqueBank;
    }
    
    public void setChqueBank(String chqueBank) {
        this.chqueBank = chqueBank;
    }
    public Integer getOder() {
        return this.oder;
    }
    
    public void setOder(Integer oder) {
        this.oder = oder;
    }
    public Integer getOfficeIdOffice() {
        return this.officeIdOffice;
    }
    
    public void setOfficeIdOffice(Integer officeIdOffice) {
        this.officeIdOffice = officeIdOffice;
    }
    public Integer getReceiptAccountId() {
        return this.receiptAccountId;
    }
    
    public void setReceiptAccountId(Integer receiptAccountId) {
        this.receiptAccountId = receiptAccountId;
    }
    public String getRibno() {
        return this.ribno;
    }
    
    public void setRibno(String ribno) {
        this.ribno = ribno;
    }
    public Date getReceiptTime() {
        return this.receiptTime;
    }
    
    public void setReceiptTime(Date receiptTime) {
        this.receiptTime = receiptTime;
    }
    public Integer getIncomeExpense() {
        return this.incomeExpense;
    }
    
    public void setIncomeExpense(Integer incomeExpense) {
        this.incomeExpense = incomeExpense;
    }
    public Integer getCusId() {
        return this.cusId;
    }
    
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }
    public Integer getCrossReciptOrVoucher() {
        return this.crossReciptOrVoucher;
    }
    
    public void setCrossReciptOrVoucher(Integer crossReciptOrVoucher) {
        this.crossReciptOrVoucher = crossReciptOrVoucher;
    }
    public Integer getPayType() {
        return this.payType;
    }
    
    public void setPayType(Integer payType) {
        this.payType = payType;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Set<Cheack> getCheacks() {
        return this.cheacks;
    }
    
    public void setCheacks(Set<Cheack> cheacks) {
        this.cheacks = cheacks;
    }
    public Set<WbTPayment> getWbTPayments() {
        return this.wbTPayments;
    }
    
    public void setWbTPayments(Set<WbTPayment> wbTPayments) {
        this.wbTPayments = wbTPayments;
    }
    public Set<WbTPaid> getWbTPaids() {
        return this.wbTPaids;
    }
    
    public void setWbTPaids(Set<WbTPaid> wbTPaids) {
        this.wbTPaids = wbTPaids;
    }
    public Set<AssPayment> getAssPayments() {
        return this.assPayments;
    }
    
    public void setAssPayments(Set<AssPayment> assPayments) {
        this.assPayments = assPayments;
    }




}


