package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SchoolDetails generated by hbm2java
 */
public class SchoolDetails  implements java.io.Serializable {


     private Integer schoolId;
     private String schoolNameE;
     private String schoolNameS;
     private Set<SwimApp> swimApps = new HashSet<SwimApp>(0);

    public SchoolDetails() {
    }

    public SchoolDetails(String schoolNameE, String schoolNameS, Set<SwimApp> swimApps) {
       this.schoolNameE = schoolNameE;
       this.schoolNameS = schoolNameS;
       this.swimApps = swimApps;
    }
   
    public Integer getSchoolId() {
        return this.schoolId;
    }
    
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
    public String getSchoolNameE() {
        return this.schoolNameE;
    }
    
    public void setSchoolNameE(String schoolNameE) {
        this.schoolNameE = schoolNameE;
    }
    public String getSchoolNameS() {
        return this.schoolNameS;
    }
    
    public void setSchoolNameS(String schoolNameS) {
        this.schoolNameS = schoolNameS;
    }
    public Set<SwimApp> getSwimApps() {
        return this.swimApps;
    }
    
    public void setSwimApps(Set<SwimApp> swimApps) {
        this.swimApps = swimApps;
    }




}


