package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1



/**
 * SlPaymentVote generated by hbm2java
 */
public class SlPaymentVote  implements java.io.Serializable {


     private Integer slPaymentVoteId;
     private Integer slPaymentAppCatgry;
     private Integer slPaymentAmountVote;
     private Integer slPaymentVat;
     private Integer slPaymentDeposit;
     private Integer slPaymentStamp;
     private Integer slPaymentOther1;
     private Integer slPaymentNbt;
     private Integer slAccountId;
     private Integer slCashId;
     private Integer slChequeId;

    public SlPaymentVote() {
    }

    public SlPaymentVote(Integer slPaymentAppCatgry, Integer slPaymentAmountVote, Integer slPaymentVat, Integer slPaymentDeposit, Integer slPaymentStamp, Integer slPaymentOther1, Integer slPaymentNbt, Integer slAccountId, Integer slCashId, Integer slChequeId) {
       this.slPaymentAppCatgry = slPaymentAppCatgry;
       this.slPaymentAmountVote = slPaymentAmountVote;
       this.slPaymentVat = slPaymentVat;
       this.slPaymentDeposit = slPaymentDeposit;
       this.slPaymentStamp = slPaymentStamp;
       this.slPaymentOther1 = slPaymentOther1;
       this.slPaymentNbt = slPaymentNbt;
       this.slAccountId = slAccountId;
       this.slCashId = slCashId;
       this.slChequeId = slChequeId;
    }
   
    public Integer getSlPaymentVoteId() {
        return this.slPaymentVoteId;
    }
    
    public void setSlPaymentVoteId(Integer slPaymentVoteId) {
        this.slPaymentVoteId = slPaymentVoteId;
    }
    public Integer getSlPaymentAppCatgry() {
        return this.slPaymentAppCatgry;
    }
    
    public void setSlPaymentAppCatgry(Integer slPaymentAppCatgry) {
        this.slPaymentAppCatgry = slPaymentAppCatgry;
    }
    public Integer getSlPaymentAmountVote() {
        return this.slPaymentAmountVote;
    }
    
    public void setSlPaymentAmountVote(Integer slPaymentAmountVote) {
        this.slPaymentAmountVote = slPaymentAmountVote;
    }
    public Integer getSlPaymentVat() {
        return this.slPaymentVat;
    }
    
    public void setSlPaymentVat(Integer slPaymentVat) {
        this.slPaymentVat = slPaymentVat;
    }
    public Integer getSlPaymentDeposit() {
        return this.slPaymentDeposit;
    }
    
    public void setSlPaymentDeposit(Integer slPaymentDeposit) {
        this.slPaymentDeposit = slPaymentDeposit;
    }
    public Integer getSlPaymentStamp() {
        return this.slPaymentStamp;
    }
    
    public void setSlPaymentStamp(Integer slPaymentStamp) {
        this.slPaymentStamp = slPaymentStamp;
    }
    public Integer getSlPaymentOther1() {
        return this.slPaymentOther1;
    }
    
    public void setSlPaymentOther1(Integer slPaymentOther1) {
        this.slPaymentOther1 = slPaymentOther1;
    }
    public Integer getSlPaymentNbt() {
        return this.slPaymentNbt;
    }
    
    public void setSlPaymentNbt(Integer slPaymentNbt) {
        this.slPaymentNbt = slPaymentNbt;
    }
    public Integer getSlAccountId() {
        return this.slAccountId;
    }
    
    public void setSlAccountId(Integer slAccountId) {
        this.slAccountId = slAccountId;
    }
    public Integer getSlCashId() {
        return this.slCashId;
    }
    
    public void setSlCashId(Integer slCashId) {
        this.slCashId = slCashId;
    }
    public Integer getSlChequeId() {
        return this.slChequeId;
    }
    
    public void setSlChequeId(Integer slChequeId) {
        this.slChequeId = slChequeId;
    }




}


