package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1



/**
 * SlYesNoDetails4 generated by hbm2java
 */
public class SlYesNoDetails4  implements java.io.Serializable {


     private Integer yesNoStatusId;
     private String yesNoStatusName;

    public SlYesNoDetails4() {
    }

    public SlYesNoDetails4(String yesNoStatusName) {
       this.yesNoStatusName = yesNoStatusName;
    }
   
    public Integer getYesNoStatusId() {
        return this.yesNoStatusId;
    }
    
    public void setYesNoStatusId(Integer yesNoStatusId) {
        this.yesNoStatusId = yesNoStatusId;
    }
    public String getYesNoStatusName() {
        return this.yesNoStatusName;
    }
    
    public void setYesNoStatusName(String yesNoStatusName) {
        this.yesNoStatusName = yesNoStatusName;
    }




}


