package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * SmsDetails generated by hbm2java
 */
public class SmsDetails  implements java.io.Serializable {


     private Integer smsId;
     private Integer smsApplicationCatId;
     private Integer smsOder;
     private String smsHeader;
     private String smsDescrip1;
     private String smsDescrip2;
     private String smsDescrip3;
     private String smsDescrip4;
     private String smsDescrip5;
     private String smsDescrip6;
     private String smsDescrip7;
     private String smsSignature;
     private String smsSignature2;
     private String smsSignature3;
     private String smsSendOrNot;

    public SmsDetails() {
    }

    public SmsDetails(Integer smsApplicationCatId, Integer smsOder, String smsHeader, String smsDescrip1, String smsDescrip2, String smsDescrip3, String smsDescrip4, String smsDescrip5, String smsDescrip6, String smsDescrip7, String smsSignature, String smsSignature2, String smsSignature3, String smsSendOrNot) {
       this.smsApplicationCatId = smsApplicationCatId;
       this.smsOder = smsOder;
       this.smsHeader = smsHeader;
       this.smsDescrip1 = smsDescrip1;
       this.smsDescrip2 = smsDescrip2;
       this.smsDescrip3 = smsDescrip3;
       this.smsDescrip4 = smsDescrip4;
       this.smsDescrip5 = smsDescrip5;
       this.smsDescrip6 = smsDescrip6;
       this.smsDescrip7 = smsDescrip7;
       this.smsSignature = smsSignature;
       this.smsSignature2 = smsSignature2;
       this.smsSignature3 = smsSignature3;
       this.smsSendOrNot = smsSendOrNot;
    }
   
    public Integer getSmsId() {
        return this.smsId;
    }
    
    public void setSmsId(Integer smsId) {
        this.smsId = smsId;
    }
    public Integer getSmsApplicationCatId() {
        return this.smsApplicationCatId;
    }
    
    public void setSmsApplicationCatId(Integer smsApplicationCatId) {
        this.smsApplicationCatId = smsApplicationCatId;
    }
    public Integer getSmsOder() {
        return this.smsOder;
    }
    
    public void setSmsOder(Integer smsOder) {
        this.smsOder = smsOder;
    }
    public String getSmsHeader() {
        return this.smsHeader;
    }
    
    public void setSmsHeader(String smsHeader) {
        this.smsHeader = smsHeader;
    }
    public String getSmsDescrip1() {
        return this.smsDescrip1;
    }
    
    public void setSmsDescrip1(String smsDescrip1) {
        this.smsDescrip1 = smsDescrip1;
    }
    public String getSmsDescrip2() {
        return this.smsDescrip2;
    }
    
    public void setSmsDescrip2(String smsDescrip2) {
        this.smsDescrip2 = smsDescrip2;
    }
    public String getSmsDescrip3() {
        return this.smsDescrip3;
    }
    
    public void setSmsDescrip3(String smsDescrip3) {
        this.smsDescrip3 = smsDescrip3;
    }
    public String getSmsDescrip4() {
        return this.smsDescrip4;
    }
    
    public void setSmsDescrip4(String smsDescrip4) {
        this.smsDescrip4 = smsDescrip4;
    }
    public String getSmsDescrip5() {
        return this.smsDescrip5;
    }
    
    public void setSmsDescrip5(String smsDescrip5) {
        this.smsDescrip5 = smsDescrip5;
    }
    public String getSmsDescrip6() {
        return this.smsDescrip6;
    }
    
    public void setSmsDescrip6(String smsDescrip6) {
        this.smsDescrip6 = smsDescrip6;
    }
    public String getSmsDescrip7() {
        return this.smsDescrip7;
    }
    
    public void setSmsDescrip7(String smsDescrip7) {
        this.smsDescrip7 = smsDescrip7;
    }
    public String getSmsSignature() {
        return this.smsSignature;
    }
    
    public void setSmsSignature(String smsSignature) {
        this.smsSignature = smsSignature;
    }
    public String getSmsSignature2() {
        return this.smsSignature2;
    }
    
    public void setSmsSignature2(String smsSignature2) {
        this.smsSignature2 = smsSignature2;
    }
    public String getSmsSignature3() {
        return this.smsSignature3;
    }
    
    public void setSmsSignature3(String smsSignature3) {
        this.smsSignature3 = smsSignature3;
    }
    public String getSmsSendOrNot() {
        return this.smsSendOrNot;
    }
    
    public void setSmsSendOrNot(String smsSendOrNot) {
        this.smsSendOrNot = smsSendOrNot;
    }




}


