package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrBuilding generated by hbm2java
 */
public class SrBuilding  implements java.io.Serializable {


     private Integer idsrBuilding;
     private String srBuildingName;
     private Integer srBuildingStatus;
     private String srBuildingCode;
     private Integer srOfficeId;
     private Set<SrShop> srShops = new HashSet<SrShop>(0);
     private Set<SrFlow> srFlows = new HashSet<SrFlow>(0);

    public SrBuilding() {
    }

    public SrBuilding(String srBuildingName, Integer srBuildingStatus, String srBuildingCode, Integer srOfficeId, Set<SrShop> srShops, Set<SrFlow> srFlows) {
       this.srBuildingName = srBuildingName;
       this.srBuildingStatus = srBuildingStatus;
       this.srBuildingCode = srBuildingCode;
       this.srOfficeId = srOfficeId;
       this.srShops = srShops;
       this.srFlows = srFlows;
    }
   
    public Integer getIdsrBuilding() {
        return this.idsrBuilding;
    }
    
    public void setIdsrBuilding(Integer idsrBuilding) {
        this.idsrBuilding = idsrBuilding;
    }
    public String getSrBuildingName() {
        return this.srBuildingName;
    }
    
    public void setSrBuildingName(String srBuildingName) {
        this.srBuildingName = srBuildingName;
    }
    public Integer getSrBuildingStatus() {
        return this.srBuildingStatus;
    }
    
    public void setSrBuildingStatus(Integer srBuildingStatus) {
        this.srBuildingStatus = srBuildingStatus;
    }
    public String getSrBuildingCode() {
        return this.srBuildingCode;
    }
    
    public void setSrBuildingCode(String srBuildingCode) {
        this.srBuildingCode = srBuildingCode;
    }
    public Integer getSrOfficeId() {
        return this.srOfficeId;
    }
    
    public void setSrOfficeId(Integer srOfficeId) {
        this.srOfficeId = srOfficeId;
    }
    public Set<SrShop> getSrShops() {
        return this.srShops;
    }
    
    public void setSrShops(Set<SrShop> srShops) {
        this.srShops = srShops;
    }
    public Set<SrFlow> getSrFlows() {
        return this.srFlows;
    }
    
    public void setSrFlows(Set<SrFlow> srFlows) {
        this.srFlows = srFlows;
    }




}


