package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrFlow generated by hbm2java
 */
public class SrFlow  implements java.io.Serializable {


     private Integer idsrFlow;
     private SrBuilding srBuilding;
     private String srFlowName;
     private Integer srFlowNumber;
     private Integer srFlowStatus;
     private String srFloorCode;
     private Set<SrShop> srShops = new HashSet<SrShop>(0);

    public SrFlow() {
    }

	
    public SrFlow(SrBuilding srBuilding) {
        this.srBuilding = srBuilding;
    }
    public SrFlow(SrBuilding srBuilding, String srFlowName, Integer srFlowNumber, Integer srFlowStatus, String srFloorCode, Set<SrShop> srShops) {
       this.srBuilding = srBuilding;
       this.srFlowName = srFlowName;
       this.srFlowNumber = srFlowNumber;
       this.srFlowStatus = srFlowStatus;
       this.srFloorCode = srFloorCode;
       this.srShops = srShops;
    }
   
    public Integer getIdsrFlow() {
        return this.idsrFlow;
    }
    
    public void setIdsrFlow(Integer idsrFlow) {
        this.idsrFlow = idsrFlow;
    }
    public SrBuilding getSrBuilding() {
        return this.srBuilding;
    }
    
    public void setSrBuilding(SrBuilding srBuilding) {
        this.srBuilding = srBuilding;
    }
    public String getSrFlowName() {
        return this.srFlowName;
    }
    
    public void setSrFlowName(String srFlowName) {
        this.srFlowName = srFlowName;
    }
    public Integer getSrFlowNumber() {
        return this.srFlowNumber;
    }
    
    public void setSrFlowNumber(Integer srFlowNumber) {
        this.srFlowNumber = srFlowNumber;
    }
    public Integer getSrFlowStatus() {
        return this.srFlowStatus;
    }
    
    public void setSrFlowStatus(Integer srFlowStatus) {
        this.srFlowStatus = srFlowStatus;
    }
    public String getSrFloorCode() {
        return this.srFloorCode;
    }
    
    public void setSrFloorCode(String srFloorCode) {
        this.srFloorCode = srFloorCode;
    }
    public Set<SrShop> getSrShops() {
        return this.srShops;
    }
    
    public void setSrShops(Set<SrShop> srShops) {
        this.srShops = srShops;
    }




}


