package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrShop generated by hbm2java
 */
public class SrShop  implements java.io.Serializable {


     private Integer idsrShop;
     private Office office;
     private SrBuilding srBuilding;
     private SrFlow srFlow;
     private SrShopType srShopType;
     private String srShopNo;
     private Integer srShopNumber;
     private Integer srShopStatus;
     private String srShopDis;
     private String cusname;
     private String address;
     private Integer customerIdCustomer;
     private Integer srShopFineProcCategoryId;
     private Set<SrShopNow> srShopNows = new HashSet<SrShopNow>(0);
     private Set<SrShopHasVote> srShopHasVotes = new HashSet<SrShopHasVote>(0);

    public SrShop() {
    }

	
    public SrShop(SrBuilding srBuilding, SrFlow srFlow) {
        this.srBuilding = srBuilding;
        this.srFlow = srFlow;
    }
    public SrShop(Office office, SrBuilding srBuilding, SrFlow srFlow, SrShopType srShopType, String srShopNo, Integer srShopNumber, Integer srShopStatus, String srShopDis, String cusname, String address, Integer customerIdCustomer, Integer srShopFineProcCategoryId, Set<SrShopNow> srShopNows, Set<SrShopHasVote> srShopHasVotes) {
       this.office = office;
       this.srBuilding = srBuilding;
       this.srFlow = srFlow;
       this.srShopType = srShopType;
       this.srShopNo = srShopNo;
       this.srShopNumber = srShopNumber;
       this.srShopStatus = srShopStatus;
       this.srShopDis = srShopDis;
       this.cusname = cusname;
       this.address = address;
       this.customerIdCustomer = customerIdCustomer;
       this.srShopFineProcCategoryId = srShopFineProcCategoryId;
       this.srShopNows = srShopNows;
       this.srShopHasVotes = srShopHasVotes;
    }
   
    public Integer getIdsrShop() {
        return this.idsrShop;
    }
    
    public void setIdsrShop(Integer idsrShop) {
        this.idsrShop = idsrShop;
    }
    public Office getOffice() {
        return this.office;
    }
    
    public void setOffice(Office office) {
        this.office = office;
    }
    public SrBuilding getSrBuilding() {
        return this.srBuilding;
    }
    
    public void setSrBuilding(SrBuilding srBuilding) {
        this.srBuilding = srBuilding;
    }
    public SrFlow getSrFlow() {
        return this.srFlow;
    }
    
    public void setSrFlow(SrFlow srFlow) {
        this.srFlow = srFlow;
    }
    public SrShopType getSrShopType() {
        return this.srShopType;
    }
    
    public void setSrShopType(SrShopType srShopType) {
        this.srShopType = srShopType;
    }
    public String getSrShopNo() {
        return this.srShopNo;
    }
    
    public void setSrShopNo(String srShopNo) {
        this.srShopNo = srShopNo;
    }
    public Integer getSrShopNumber() {
        return this.srShopNumber;
    }
    
    public void setSrShopNumber(Integer srShopNumber) {
        this.srShopNumber = srShopNumber;
    }
    public Integer getSrShopStatus() {
        return this.srShopStatus;
    }
    
    public void setSrShopStatus(Integer srShopStatus) {
        this.srShopStatus = srShopStatus;
    }
    public String getSrShopDis() {
        return this.srShopDis;
    }
    
    public void setSrShopDis(String srShopDis) {
        this.srShopDis = srShopDis;
    }
    public String getCusname() {
        return this.cusname;
    }
    
    public void setCusname(String cusname) {
        this.cusname = cusname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getCustomerIdCustomer() {
        return this.customerIdCustomer;
    }
    
    public void setCustomerIdCustomer(Integer customerIdCustomer) {
        this.customerIdCustomer = customerIdCustomer;
    }
    public Integer getSrShopFineProcCategoryId() {
        return this.srShopFineProcCategoryId;
    }
    
    public void setSrShopFineProcCategoryId(Integer srShopFineProcCategoryId) {
        this.srShopFineProcCategoryId = srShopFineProcCategoryId;
    }
    public Set<SrShopNow> getSrShopNows() {
        return this.srShopNows;
    }
    
    public void setSrShopNows(Set<SrShopNow> srShopNows) {
        this.srShopNows = srShopNows;
    }
    public Set<SrShopHasVote> getSrShopHasVotes() {
        return this.srShopHasVotes;
    }
    
    public void setSrShopHasVotes(Set<SrShopHasVote> srShopHasVotes) {
        this.srShopHasVotes = srShopHasVotes;
    }




}


