package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrShop generated by hbm2java
 */
public class SrShop  implements java.io.Serializable {


     private Integer idsrShop;
     private Office office;
     private SrBuilding srBuilding;
     private SrFlow srFlow;
     private SrShopType srShopType;
     private String srShopNo;
     private Integer srShopNumber;
     private Integer srShopStatus;
     private String srShopDis;
     private String cusname;
     private String address;
     private Integer customerIdCustomer;
     private Integer srShopFineProcCategoryId;
     private Set<SrShopFinePrcDetail> srShopFinePrcDetails = new HashSet<SrShopFinePrcDetail>(0);
     private Set<SrShopPayment> srShopPayments = new HashSet<SrShopPayment>(0);
     private Set<CustomerHasSrShop> customerHasSrShops = new HashSet<CustomerHasSrShop>(0);
     private Set<SrShopHasCustomer> srShopHasCustomers = new HashSet<SrShopHasCustomer>(0);
     private Set<SrShopHasValue> srShopHasValues = new HashSet<SrShopHasValue>(0);
     private Set<SrShopHasVote> srShopHasVotes = new HashSet<SrShopHasVote>(0);
     private Set<SrShopPaymentCrossTbl> srShopPaymentCrossTbls = new HashSet<SrShopPaymentCrossTbl>(0);
     private Set<SrShopProc> srShopProcs = new HashSet<SrShopProc>(0);
     private Set<SrShopCashflow> srShopCashflows = new HashSet<SrShopCashflow>(0);

    public SrShop() {
    }

	
    public SrShop(SrBuilding srBuilding, SrFlow srFlow) {
        this.srBuilding = srBuilding;
        this.srFlow = srFlow;
    }
    public SrShop(Office office, SrBuilding srBuilding, SrFlow srFlow, SrShopType srShopType, String srShopNo, Integer srShopNumber, Integer srShopStatus, String srShopDis, String cusname, String address, Integer customerIdCustomer, Integer srShopFineProcCategoryId, Set<SrShopFinePrcDetail> srShopFinePrcDetails, Set<SrShopPayment> srShopPayments, Set<CustomerHasSrShop> customerHasSrShops, Set<SrShopHasCustomer> srShopHasCustomers, Set<SrShopHasValue> srShopHasValues, Set<SrShopHasVote> srShopHasVotes, Set<SrShopPaymentCrossTbl> srShopPaymentCrossTbls, Set<SrShopProc> srShopProcs, Set<SrShopCashflow> srShopCashflows) {
       this.office = office;
       this.srBuilding = srBuilding;
       this.srFlow = srFlow;
       this.srShopType = srShopType;
       this.srShopNo = srShopNo;
       this.srShopNumber = srShopNumber;
       this.srShopStatus = srShopStatus;
       this.srShopDis = srShopDis;
       this.cusname = cusname;
       this.address = address;
       this.customerIdCustomer = customerIdCustomer;
       this.srShopFineProcCategoryId = srShopFineProcCategoryId;
       this.srShopFinePrcDetails = srShopFinePrcDetails;
       this.srShopPayments = srShopPayments;
       this.customerHasSrShops = customerHasSrShops;
       this.srShopHasCustomers = srShopHasCustomers;
       this.srShopHasValues = srShopHasValues;
       this.srShopHasVotes = srShopHasVotes;
       this.srShopPaymentCrossTbls = srShopPaymentCrossTbls;
       this.srShopProcs = srShopProcs;
       this.srShopCashflows = srShopCashflows;
    }
   
    public Integer getIdsrShop() {
        return this.idsrShop;
    }
    
    public void setIdsrShop(Integer idsrShop) {
        this.idsrShop = idsrShop;
    }
    public Office getOffice() {
        return this.office;
    }
    
    public void setOffice(Office office) {
        this.office = office;
    }
    public SrBuilding getSrBuilding() {
        return this.srBuilding;
    }
    
    public void setSrBuilding(SrBuilding srBuilding) {
        this.srBuilding = srBuilding;
    }
    public SrFlow getSrFlow() {
        return this.srFlow;
    }
    
    public void setSrFlow(SrFlow srFlow) {
        this.srFlow = srFlow;
    }
    public SrShopType getSrShopType() {
        return this.srShopType;
    }
    
    public void setSrShopType(SrShopType srShopType) {
        this.srShopType = srShopType;
    }
    public String getSrShopNo() {
        return this.srShopNo;
    }
    
    public void setSrShopNo(String srShopNo) {
        this.srShopNo = srShopNo;
    }
    public Integer getSrShopNumber() {
        return this.srShopNumber;
    }
    
    public void setSrShopNumber(Integer srShopNumber) {
        this.srShopNumber = srShopNumber;
    }
    public Integer getSrShopStatus() {
        return this.srShopStatus;
    }
    
    public void setSrShopStatus(Integer srShopStatus) {
        this.srShopStatus = srShopStatus;
    }
    public String getSrShopDis() {
        return this.srShopDis;
    }
    
    public void setSrShopDis(String srShopDis) {
        this.srShopDis = srShopDis;
    }
    public String getCusname() {
        return this.cusname;
    }
    
    public void setCusname(String cusname) {
        this.cusname = cusname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getCustomerIdCustomer() {
        return this.customerIdCustomer;
    }
    
    public void setCustomerIdCustomer(Integer customerIdCustomer) {
        this.customerIdCustomer = customerIdCustomer;
    }
    public Integer getSrShopFineProcCategoryId() {
        return this.srShopFineProcCategoryId;
    }
    
    public void setSrShopFineProcCategoryId(Integer srShopFineProcCategoryId) {
        this.srShopFineProcCategoryId = srShopFineProcCategoryId;
    }
    public Set<SrShopFinePrcDetail> getSrShopFinePrcDetails() {
        return this.srShopFinePrcDetails;
    }
    
    public void setSrShopFinePrcDetails(Set<SrShopFinePrcDetail> srShopFinePrcDetails) {
        this.srShopFinePrcDetails = srShopFinePrcDetails;
    }
    public Set<SrShopPayment> getSrShopPayments() {
        return this.srShopPayments;
    }
    
    public void setSrShopPayments(Set<SrShopPayment> srShopPayments) {
        this.srShopPayments = srShopPayments;
    }
    public Set<CustomerHasSrShop> getCustomerHasSrShops() {
        return this.customerHasSrShops;
    }
    
    public void setCustomerHasSrShops(Set<CustomerHasSrShop> customerHasSrShops) {
        this.customerHasSrShops = customerHasSrShops;
    }
    public Set<SrShopHasCustomer> getSrShopHasCustomers() {
        return this.srShopHasCustomers;
    }
    
    public void setSrShopHasCustomers(Set<SrShopHasCustomer> srShopHasCustomers) {
        this.srShopHasCustomers = srShopHasCustomers;
    }
    public Set<SrShopHasValue> getSrShopHasValues() {
        return this.srShopHasValues;
    }
    
    public void setSrShopHasValues(Set<SrShopHasValue> srShopHasValues) {
        this.srShopHasValues = srShopHasValues;
    }
    public Set<SrShopHasVote> getSrShopHasVotes() {
        return this.srShopHasVotes;
    }
    
    public void setSrShopHasVotes(Set<SrShopHasVote> srShopHasVotes) {
        this.srShopHasVotes = srShopHasVotes;
    }
    public Set<SrShopPaymentCrossTbl> getSrShopPaymentCrossTbls() {
        return this.srShopPaymentCrossTbls;
    }
    
    public void setSrShopPaymentCrossTbls(Set<SrShopPaymentCrossTbl> srShopPaymentCrossTbls) {
        this.srShopPaymentCrossTbls = srShopPaymentCrossTbls;
    }
    public Set<SrShopProc> getSrShopProcs() {
        return this.srShopProcs;
    }
    
    public void setSrShopProcs(Set<SrShopProc> srShopProcs) {
        this.srShopProcs = srShopProcs;
    }
    public Set<SrShopCashflow> getSrShopCashflows() {
        return this.srShopCashflows;
    }
    
    public void setSrShopCashflows(Set<SrShopCashflow> srShopCashflows) {
        this.srShopCashflows = srShopCashflows;
    }




}


