package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * SrShopHasValue generated by hbm2java
 */
public class SrShopHasValue  implements java.io.Serializable {


     private Integer shopHasValueId;
     private SrShopNow srShopNow;
     private SrShopValues srShopValues;
     private Integer valueStatus;

    public SrShopHasValue() {
    }

    public SrShopHasValue(SrShopNow srShopNow, SrShopValues srShopValues, Integer valueStatus) {
       this.srShopNow = srShopNow;
       this.srShopValues = srShopValues;
       this.valueStatus = valueStatus;
    }
   
    public Integer getShopHasValueId() {
        return this.shopHasValueId;
    }
    
    public void setShopHasValueId(Integer shopHasValueId) {
        this.shopHasValueId = shopHasValueId;
    }
    public SrShopNow getSrShopNow() {
        return this.srShopNow;
    }
    
    public void setSrShopNow(SrShopNow srShopNow) {
        this.srShopNow = srShopNow;
    }
    public SrShopValues getSrShopValues() {
        return this.srShopValues;
    }
    
    public void setSrShopValues(SrShopValues srShopValues) {
        this.srShopValues = srShopValues;
    }
    public Integer getValueStatus() {
        return this.valueStatus;
    }
    
    public void setValueStatus(Integer valueStatus) {
        this.valueStatus = valueStatus;
    }




}


