package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrShopType generated by hbm2java
 */
public class SrShopType  implements java.io.Serializable {


     private Integer idsrShopType;
     private String srShopTypeName;
     private Integer srShopTypeStatus;
     private Integer srShopTypeMonthsCount;
     private Set<SrShop> srShops = new HashSet<SrShop>(0);

    public SrShopType() {
    }

    public SrShopType(String srShopTypeName, Integer srShopTypeStatus, Integer srShopTypeMonthsCount, Set<SrShop> srShops) {
       this.srShopTypeName = srShopTypeName;
       this.srShopTypeStatus = srShopTypeStatus;
       this.srShopTypeMonthsCount = srShopTypeMonthsCount;
       this.srShops = srShops;
    }
   
    public Integer getIdsrShopType() {
        return this.idsrShopType;
    }
    
    public void setIdsrShopType(Integer idsrShopType) {
        this.idsrShopType = idsrShopType;
    }
    public String getSrShopTypeName() {
        return this.srShopTypeName;
    }
    
    public void setSrShopTypeName(String srShopTypeName) {
        this.srShopTypeName = srShopTypeName;
    }
    public Integer getSrShopTypeStatus() {
        return this.srShopTypeStatus;
    }
    
    public void setSrShopTypeStatus(Integer srShopTypeStatus) {
        this.srShopTypeStatus = srShopTypeStatus;
    }
    public Integer getSrShopTypeMonthsCount() {
        return this.srShopTypeMonthsCount;
    }
    
    public void setSrShopTypeMonthsCount(Integer srShopTypeMonthsCount) {
        this.srShopTypeMonthsCount = srShopTypeMonthsCount;
    }
    public Set<SrShop> getSrShops() {
        return this.srShops;
    }
    
    public void setSrShops(Set<SrShop> srShops) {
        this.srShops = srShops;
    }




}


