package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer idStatus;
     private String statusName;
     private Integer statusId;

    public Status() {
    }

    public Status(String statusName, Integer statusId) {
       this.statusName = statusName;
       this.statusId = statusId;
    }
   
    public Integer getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(Integer idStatus) {
        this.idStatus = idStatus;
    }
    public String getStatusName() {
        return this.statusName;
    }
    
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }




}


