package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SwimGameDetails generated by hbm2java
 */
public class SwimGameDetails  implements java.io.Serializable {


     private Integer swimGameTypeId;
     private String swimGameName;
     private Integer swimGameActiveStatus;
     private Set<SwimCorchRegistration> swimCorchRegistrations = new HashSet<SwimCorchRegistration>(0);

    public SwimGameDetails() {
    }

    public SwimGameDetails(String swimGameName, Integer swimGameActiveStatus, Set<SwimCorchRegistration> swimCorchRegistrations) {
       this.swimGameName = swimGameName;
       this.swimGameActiveStatus = swimGameActiveStatus;
       this.swimCorchRegistrations = swimCorchRegistrations;
    }
   
    public Integer getSwimGameTypeId() {
        return this.swimGameTypeId;
    }
    
    public void setSwimGameTypeId(Integer swimGameTypeId) {
        this.swimGameTypeId = swimGameTypeId;
    }
    public String getSwimGameName() {
        return this.swimGameName;
    }
    
    public void setSwimGameName(String swimGameName) {
        this.swimGameName = swimGameName;
    }
    public Integer getSwimGameActiveStatus() {
        return this.swimGameActiveStatus;
    }
    
    public void setSwimGameActiveStatus(Integer swimGameActiveStatus) {
        this.swimGameActiveStatus = swimGameActiveStatus;
    }
    public Set<SwimCorchRegistration> getSwimCorchRegistrations() {
        return this.swimCorchRegistrations;
    }
    
    public void setSwimCorchRegistrations(Set<SwimCorchRegistration> swimCorchRegistrations) {
        this.swimCorchRegistrations = swimCorchRegistrations;
    }




}


