package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TlApp generated by hbm2java
 */
public class TlApp  implements java.io.Serializable {


     private Integer idTlApp;
     private Customer customer;
     private TlAppGetType tlAppGetType;
     private TlCreatePropId tlCreatePropId;
     private User user;
     private String createAppNo;
     private String appNo;
     private String appTlEname;
     private String appTlSname;
     private Integer appAssId;
     private Integer appShopId;
     private Integer appUserId;
     private Date appDate;
     private Date appTime;
     private Integer appStatusAcrive;
     private Integer appYear;
     private Integer tlAppNoOrder;
     private Integer tlAppChairDet;
     private Set<TlCrossTblDetails> tlCrossTblDetailses = new HashSet<TlCrossTblDetails>(0);
     private Set<TlPayDetails> tlPayDetailses = new HashSet<TlPayDetails>(0);
     private Set<TlPay> tlPays = new HashSet<TlPay>(0);

    public TlApp() {
    }

    public TlApp(Customer customer, TlAppGetType tlAppGetType, TlCreatePropId tlCreatePropId, User user, String createAppNo, String appNo, String appTlEname, String appTlSname, Integer appAssId, Integer appShopId, Integer appUserId, Date appDate, Date appTime, Integer appStatusAcrive, Integer appYear, Integer tlAppNoOrder, Integer tlAppChairDet, Set<TlCrossTblDetails> tlCrossTblDetailses, Set<TlPayDetails> tlPayDetailses, Set<TlPay> tlPays) {
       this.customer = customer;
       this.tlAppGetType = tlAppGetType;
       this.tlCreatePropId = tlCreatePropId;
       this.user = user;
       this.createAppNo = createAppNo;
       this.appNo = appNo;
       this.appTlEname = appTlEname;
       this.appTlSname = appTlSname;
       this.appAssId = appAssId;
       this.appShopId = appShopId;
       this.appUserId = appUserId;
       this.appDate = appDate;
       this.appTime = appTime;
       this.appStatusAcrive = appStatusAcrive;
       this.appYear = appYear;
       this.tlAppNoOrder = tlAppNoOrder;
       this.tlAppChairDet = tlAppChairDet;
       this.tlCrossTblDetailses = tlCrossTblDetailses;
       this.tlPayDetailses = tlPayDetailses;
       this.tlPays = tlPays;
    }
   
    public Integer getIdTlApp() {
        return this.idTlApp;
    }
    
    public void setIdTlApp(Integer idTlApp) {
        this.idTlApp = idTlApp;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public TlAppGetType getTlAppGetType() {
        return this.tlAppGetType;
    }
    
    public void setTlAppGetType(TlAppGetType tlAppGetType) {
        this.tlAppGetType = tlAppGetType;
    }
    public TlCreatePropId getTlCreatePropId() {
        return this.tlCreatePropId;
    }
    
    public void setTlCreatePropId(TlCreatePropId tlCreatePropId) {
        this.tlCreatePropId = tlCreatePropId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCreateAppNo() {
        return this.createAppNo;
    }
    
    public void setCreateAppNo(String createAppNo) {
        this.createAppNo = createAppNo;
    }
    public String getAppNo() {
        return this.appNo;
    }
    
    public void setAppNo(String appNo) {
        this.appNo = appNo;
    }
    public String getAppTlEname() {
        return this.appTlEname;
    }
    
    public void setAppTlEname(String appTlEname) {
        this.appTlEname = appTlEname;
    }
    public String getAppTlSname() {
        return this.appTlSname;
    }
    
    public void setAppTlSname(String appTlSname) {
        this.appTlSname = appTlSname;
    }
    public Integer getAppAssId() {
        return this.appAssId;
    }
    
    public void setAppAssId(Integer appAssId) {
        this.appAssId = appAssId;
    }
    public Integer getAppShopId() {
        return this.appShopId;
    }
    
    public void setAppShopId(Integer appShopId) {
        this.appShopId = appShopId;
    }
    public Integer getAppUserId() {
        return this.appUserId;
    }
    
    public void setAppUserId(Integer appUserId) {
        this.appUserId = appUserId;
    }
    public Date getAppDate() {
        return this.appDate;
    }
    
    public void setAppDate(Date appDate) {
        this.appDate = appDate;
    }
    public Date getAppTime() {
        return this.appTime;
    }
    
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }
    public Integer getAppStatusAcrive() {
        return this.appStatusAcrive;
    }
    
    public void setAppStatusAcrive(Integer appStatusAcrive) {
        this.appStatusAcrive = appStatusAcrive;
    }
    public Integer getAppYear() {
        return this.appYear;
    }
    
    public void setAppYear(Integer appYear) {
        this.appYear = appYear;
    }
    public Integer getTlAppNoOrder() {
        return this.tlAppNoOrder;
    }
    
    public void setTlAppNoOrder(Integer tlAppNoOrder) {
        this.tlAppNoOrder = tlAppNoOrder;
    }
    public Integer getTlAppChairDet() {
        return this.tlAppChairDet;
    }
    
    public void setTlAppChairDet(Integer tlAppChairDet) {
        this.tlAppChairDet = tlAppChairDet;
    }
    public Set<TlCrossTblDetails> getTlCrossTblDetailses() {
        return this.tlCrossTblDetailses;
    }
    
    public void setTlCrossTblDetailses(Set<TlCrossTblDetails> tlCrossTblDetailses) {
        this.tlCrossTblDetailses = tlCrossTblDetailses;
    }
    public Set<TlPayDetails> getTlPayDetailses() {
        return this.tlPayDetailses;
    }
    
    public void setTlPayDetailses(Set<TlPayDetails> tlPayDetailses) {
        this.tlPayDetailses = tlPayDetailses;
    }
    public Set<TlPay> getTlPays() {
        return this.tlPays;
    }
    
    public void setTlPays(Set<TlPay> tlPays) {
        this.tlPays = tlPays;
    }




}


