package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TlApproveDetails generated by hbm2java
 */
public class TlApproveDetails  implements java.io.Serializable {


     private Integer tlApproveDetailsId;
     private int tlApproveAppId;
     private Integer tlApprovePayId;
     private String tlApproveUserId;
     private int tlApproveUserCatId;
     private String tlApproveComment;
     private Date tlApproveDate;
     private Date tlApproveTime;

    public TlApproveDetails() {
    }

	
    public TlApproveDetails(int tlApproveAppId, int tlApproveUserCatId) {
        this.tlApproveAppId = tlApproveAppId;
        this.tlApproveUserCatId = tlApproveUserCatId;
    }
    public TlApproveDetails(int tlApproveAppId, Integer tlApprovePayId, String tlApproveUserId, int tlApproveUserCatId, String tlApproveComment, Date tlApproveDate, Date tlApproveTime) {
       this.tlApproveAppId = tlApproveAppId;
       this.tlApprovePayId = tlApprovePayId;
       this.tlApproveUserId = tlApproveUserId;
       this.tlApproveUserCatId = tlApproveUserCatId;
       this.tlApproveComment = tlApproveComment;
       this.tlApproveDate = tlApproveDate;
       this.tlApproveTime = tlApproveTime;
    }
   
    public Integer getTlApproveDetailsId() {
        return this.tlApproveDetailsId;
    }
    
    public void setTlApproveDetailsId(Integer tlApproveDetailsId) {
        this.tlApproveDetailsId = tlApproveDetailsId;
    }
    public int getTlApproveAppId() {
        return this.tlApproveAppId;
    }
    
    public void setTlApproveAppId(int tlApproveAppId) {
        this.tlApproveAppId = tlApproveAppId;
    }
    public Integer getTlApprovePayId() {
        return this.tlApprovePayId;
    }
    
    public void setTlApprovePayId(Integer tlApprovePayId) {
        this.tlApprovePayId = tlApprovePayId;
    }
    public String getTlApproveUserId() {
        return this.tlApproveUserId;
    }
    
    public void setTlApproveUserId(String tlApproveUserId) {
        this.tlApproveUserId = tlApproveUserId;
    }
    public int getTlApproveUserCatId() {
        return this.tlApproveUserCatId;
    }
    
    public void setTlApproveUserCatId(int tlApproveUserCatId) {
        this.tlApproveUserCatId = tlApproveUserCatId;
    }
    public String getTlApproveComment() {
        return this.tlApproveComment;
    }
    
    public void setTlApproveComment(String tlApproveComment) {
        this.tlApproveComment = tlApproveComment;
    }
    public Date getTlApproveDate() {
        return this.tlApproveDate;
    }
    
    public void setTlApproveDate(Date tlApproveDate) {
        this.tlApproveDate = tlApproveDate;
    }
    public Date getTlApproveTime() {
        return this.tlApproveTime;
    }
    
    public void setTlApproveTime(Date tlApproveTime) {
        this.tlApproveTime = tlApproveTime;
    }




}


