package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * TlChargingScheme generated by hbm2java
 */
public class TlChargingScheme  implements java.io.Serializable {


     private Integer tlChargingSchemeId;
     private TlSubType tlSubType;
     private TlUseWhatStatus tlUseWhatStatus;
     private Double tlChargingStart;
     private Double tlChargingEnd;
     private Double tlChargeAmount;
     private Double tlChargePrecentage;
     private Integer tlChargingStatus;

    public TlChargingScheme() {
    }

    public TlChargingScheme(TlSubType tlSubType, TlUseWhatStatus tlUseWhatStatus, Double tlChargingStart, Double tlChargingEnd, Double tlChargeAmount, Double tlChargePrecentage, Integer tlChargingStatus) {
       this.tlSubType = tlSubType;
       this.tlUseWhatStatus = tlUseWhatStatus;
       this.tlChargingStart = tlChargingStart;
       this.tlChargingEnd = tlChargingEnd;
       this.tlChargeAmount = tlChargeAmount;
       this.tlChargePrecentage = tlChargePrecentage;
       this.tlChargingStatus = tlChargingStatus;
    }
   
    public Integer getTlChargingSchemeId() {
        return this.tlChargingSchemeId;
    }
    
    public void setTlChargingSchemeId(Integer tlChargingSchemeId) {
        this.tlChargingSchemeId = tlChargingSchemeId;
    }
    public TlSubType getTlSubType() {
        return this.tlSubType;
    }
    
    public void setTlSubType(TlSubType tlSubType) {
        this.tlSubType = tlSubType;
    }
    public TlUseWhatStatus getTlUseWhatStatus() {
        return this.tlUseWhatStatus;
    }
    
    public void setTlUseWhatStatus(TlUseWhatStatus tlUseWhatStatus) {
        this.tlUseWhatStatus = tlUseWhatStatus;
    }
    public Double getTlChargingStart() {
        return this.tlChargingStart;
    }
    
    public void setTlChargingStart(Double tlChargingStart) {
        this.tlChargingStart = tlChargingStart;
    }
    public Double getTlChargingEnd() {
        return this.tlChargingEnd;
    }
    
    public void setTlChargingEnd(Double tlChargingEnd) {
        this.tlChargingEnd = tlChargingEnd;
    }
    public Double getTlChargeAmount() {
        return this.tlChargeAmount;
    }
    
    public void setTlChargeAmount(Double tlChargeAmount) {
        this.tlChargeAmount = tlChargeAmount;
    }
    public Double getTlChargePrecentage() {
        return this.tlChargePrecentage;
    }
    
    public void setTlChargePrecentage(Double tlChargePrecentage) {
        this.tlChargePrecentage = tlChargePrecentage;
    }
    public Integer getTlChargingStatus() {
        return this.tlChargingStatus;
    }
    
    public void setTlChargingStatus(Integer tlChargingStatus) {
        this.tlChargingStatus = tlChargingStatus;
    }




}


