package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TlCrossTblDetails generated by hbm2java
 */
public class TlCrossTblDetails  implements java.io.Serializable {


     private Integer tlCrossTblId;
     private TlApp tlApp;
     private TlPayDetails tlPayDetails;
     private Integer tlVortId;
     private Double tlAmount;
     private Date tlDate;
     private Integer tlPaidStatus;
     private Integer tlApproveornotId;
     

    public TlCrossTblDetails() {
    }

    public TlCrossTblDetails(TlApp tlApp, TlPayDetails tlPayDetails, Integer tlVortId, Double tlAmount, Date tlDate, Integer tlPaidStatus, Integer tlApproveornotId) {
       this.tlApp = tlApp;
       this.tlPayDetails = tlPayDetails;
       this.tlVortId = tlVortId;
       this.tlAmount = tlAmount;
       this.tlDate = tlDate;
       this.tlPaidStatus = tlPaidStatus;
       this.tlApproveornotId = tlApproveornotId;
     
    }
   
    public Integer getTlCrossTblId() {
        return this.tlCrossTblId;
    }
    
    public void setTlCrossTblId(Integer tlCrossTblId) {
        this.tlCrossTblId = tlCrossTblId;
    }
    public TlApp getTlApp() {
        return this.tlApp;
    }
    
    public void setTlApp(TlApp tlApp) {
        this.tlApp = tlApp;
    }
    public TlPayDetails getTlPayDetails() {
        return this.tlPayDetails;
    }
    
    public void setTlPayDetails(TlPayDetails tlPayDetails) {
        this.tlPayDetails = tlPayDetails;
    }
    public Integer getTlVortId() {
        return this.tlVortId;
    }
    
    public void setTlVortId(Integer tlVortId) {
        this.tlVortId = tlVortId;
    }
    public Double getTlAmount() {
        return this.tlAmount;
    }
    
    public void setTlAmount(Double tlAmount) {
        this.tlAmount = tlAmount;
    }
    public Date getTlDate() {
        return this.tlDate;
    }
    
    public void setTlDate(Date tlDate) {
        this.tlDate = tlDate;
    }
    public Integer getTlPaidStatus() {
        return this.tlPaidStatus;
    }
    
    public void setTlPaidStatus(Integer tlPaidStatus) {
        this.tlPaidStatus = tlPaidStatus;
    }
    public Integer getTlApproveornotId() {
        return this.tlApproveornotId;
    }
    
    public void setTlApproveornotId(Integer tlApproveornotId) {
        this.tlApproveornotId = tlApproveornotId;
    }





}


