package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TlPaidType generated by hbm2java
 */
public class TlPaidType  implements java.io.Serializable {


     private Integer tlPaidType;
     private String tlPaidCategory;
     private Integer tlVatPaidNot;
     private Integer tlNbtPaidNot;
     private Integer tlStampPaidNot;
     private Integer tlVatId;
     private Integer tlNbtId;
     private Integer tlStampId;
     private Integer tlPaidActiveStatus;
     private Set<TlSubType> tlSubTypes = new HashSet<TlSubType>(0);

    public TlPaidType() {
    }

    public TlPaidType(String tlPaidCategory, Integer tlVatPaidNot, Integer tlNbtPaidNot, Integer tlStampPaidNot, Integer tlVatId, Integer tlNbtId, Integer tlStampId, Integer tlPaidActiveStatus, Set<TlSubType> tlSubTypes) {
       this.tlPaidCategory = tlPaidCategory;
       this.tlVatPaidNot = tlVatPaidNot;
       this.tlNbtPaidNot = tlNbtPaidNot;
       this.tlStampPaidNot = tlStampPaidNot;
       this.tlVatId = tlVatId;
       this.tlNbtId = tlNbtId;
       this.tlStampId = tlStampId;
       this.tlPaidActiveStatus = tlPaidActiveStatus;
       this.tlSubTypes = tlSubTypes;
    }
   
    public Integer getTlPaidType() {
        return this.tlPaidType;
    }
    
    public void setTlPaidType(Integer tlPaidType) {
        this.tlPaidType = tlPaidType;
    }
    public String getTlPaidCategory() {
        return this.tlPaidCategory;
    }
    
    public void setTlPaidCategory(String tlPaidCategory) {
        this.tlPaidCategory = tlPaidCategory;
    }
    public Integer getTlVatPaidNot() {
        return this.tlVatPaidNot;
    }
    
    public void setTlVatPaidNot(Integer tlVatPaidNot) {
        this.tlVatPaidNot = tlVatPaidNot;
    }
    public Integer getTlNbtPaidNot() {
        return this.tlNbtPaidNot;
    }
    
    public void setTlNbtPaidNot(Integer tlNbtPaidNot) {
        this.tlNbtPaidNot = tlNbtPaidNot;
    }
    public Integer getTlStampPaidNot() {
        return this.tlStampPaidNot;
    }
    
    public void setTlStampPaidNot(Integer tlStampPaidNot) {
        this.tlStampPaidNot = tlStampPaidNot;
    }
    public Integer getTlVatId() {
        return this.tlVatId;
    }
    
    public void setTlVatId(Integer tlVatId) {
        this.tlVatId = tlVatId;
    }
    public Integer getTlNbtId() {
        return this.tlNbtId;
    }
    
    public void setTlNbtId(Integer tlNbtId) {
        this.tlNbtId = tlNbtId;
    }
    public Integer getTlStampId() {
        return this.tlStampId;
    }
    
    public void setTlStampId(Integer tlStampId) {
        this.tlStampId = tlStampId;
    }
    public Integer getTlPaidActiveStatus() {
        return this.tlPaidActiveStatus;
    }
    
    public void setTlPaidActiveStatus(Integer tlPaidActiveStatus) {
        this.tlPaidActiveStatus = tlPaidActiveStatus;
    }
    public Set<TlSubType> getTlSubTypes() {
        return this.tlSubTypes;
    }
    
    public void setTlSubTypes(Set<TlSubType> tlSubTypes) {
        this.tlSubTypes = tlSubTypes;
    }




}


