package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * TlPhiSelectionAnswer generated by hbm2java
 */
public class TlPhiSelectionAnswer  implements java.io.Serializable {


     private Integer tlPhiSelectionAnswerId;
     private Integer tlPhiSelectionAnswerSelecId;
     private int tlPhiSelectionAnswerAppId;
     private int tlPhiSelectionPayDetailsId;

    public TlPhiSelectionAnswer() {
    }

	
    public TlPhiSelectionAnswer(int tlPhiSelectionAnswerAppId, int tlPhiSelectionPayDetailsId) {
        this.tlPhiSelectionAnswerAppId = tlPhiSelectionAnswerAppId;
        this.tlPhiSelectionPayDetailsId = tlPhiSelectionPayDetailsId;
    }
    public TlPhiSelectionAnswer(Integer tlPhiSelectionAnswerSelecId, int tlPhiSelectionAnswerAppId, int tlPhiSelectionPayDetailsId) {
       this.tlPhiSelectionAnswerSelecId = tlPhiSelectionAnswerSelecId;
       this.tlPhiSelectionAnswerAppId = tlPhiSelectionAnswerAppId;
       this.tlPhiSelectionPayDetailsId = tlPhiSelectionPayDetailsId;
    }
   
    public Integer getTlPhiSelectionAnswerId() {
        return this.tlPhiSelectionAnswerId;
    }
    
    public void setTlPhiSelectionAnswerId(Integer tlPhiSelectionAnswerId) {
        this.tlPhiSelectionAnswerId = tlPhiSelectionAnswerId;
    }
    public Integer getTlPhiSelectionAnswerSelecId() {
        return this.tlPhiSelectionAnswerSelecId;
    }
    
    public void setTlPhiSelectionAnswerSelecId(Integer tlPhiSelectionAnswerSelecId) {
        this.tlPhiSelectionAnswerSelecId = tlPhiSelectionAnswerSelecId;
    }
    public int getTlPhiSelectionAnswerAppId() {
        return this.tlPhiSelectionAnswerAppId;
    }
    
    public void setTlPhiSelectionAnswerAppId(int tlPhiSelectionAnswerAppId) {
        this.tlPhiSelectionAnswerAppId = tlPhiSelectionAnswerAppId;
    }
    public int getTlPhiSelectionPayDetailsId() {
        return this.tlPhiSelectionPayDetailsId;
    }
    
    public void setTlPhiSelectionPayDetailsId(int tlPhiSelectionPayDetailsId) {
        this.tlPhiSelectionPayDetailsId = tlPhiSelectionPayDetailsId;
    }




}


