package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TlPrintDetails generated by hbm2java
 */
public class TlPrintDetails  implements java.io.Serializable {


     private int tlPrintDetailsId;
     private String tlPrintChairmanName;
     private String tlPrintChairmanNameInitials;
     private String tlPrintSecrataryName;
     private String gazzertNo;
     private Date gazzertDate;
     private Integer status;

    public TlPrintDetails() {
    }

	
    public TlPrintDetails(int tlPrintDetailsId) {
        this.tlPrintDetailsId = tlPrintDetailsId;
    }
    public TlPrintDetails(int tlPrintDetailsId, String tlPrintChairmanName, String tlPrintChairmanNameInitials, String tlPrintSecrataryName, String gazzertNo, Date gazzertDate, Integer status) {
       this.tlPrintDetailsId = tlPrintDetailsId;
       this.tlPrintChairmanName = tlPrintChairmanName;
       this.tlPrintChairmanNameInitials = tlPrintChairmanNameInitials;
       this.tlPrintSecrataryName = tlPrintSecrataryName;
       this.gazzertNo = gazzertNo;
       this.gazzertDate = gazzertDate;
       this.status = status;
    }
   
    public int getTlPrintDetailsId() {
        return this.tlPrintDetailsId;
    }
    
    public void setTlPrintDetailsId(int tlPrintDetailsId) {
        this.tlPrintDetailsId = tlPrintDetailsId;
    }
    public String getTlPrintChairmanName() {
        return this.tlPrintChairmanName;
    }
    
    public void setTlPrintChairmanName(String tlPrintChairmanName) {
        this.tlPrintChairmanName = tlPrintChairmanName;
    }
    public String getTlPrintChairmanNameInitials() {
        return this.tlPrintChairmanNameInitials;
    }
    
    public void setTlPrintChairmanNameInitials(String tlPrintChairmanNameInitials) {
        this.tlPrintChairmanNameInitials = tlPrintChairmanNameInitials;
    }
    public String getTlPrintSecrataryName() {
        return this.tlPrintSecrataryName;
    }
    
    public void setTlPrintSecrataryName(String tlPrintSecrataryName) {
        this.tlPrintSecrataryName = tlPrintSecrataryName;
    }
    public String getGazzertNo() {
        return this.gazzertNo;
    }
    
    public void setGazzertNo(String gazzertNo) {
        this.gazzertNo = gazzertNo;
    }
    public Date getGazzertDate() {
        return this.gazzertDate;
    }
    
    public void setGazzertDate(Date gazzertDate) {
        this.gazzertDate = gazzertDate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


