package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * TlPrintBillVoteName generated by hbm2java
 */
public class TlPrintBillVoteName  implements java.io.Serializable {


     private Integer tlPrintBillVoteNameId;
     private String tlPrintBillVoteName;
     private Integer tlPrintBillVoteId;
     private Integer tlPrintBillVoteOrder;

    public TlPrintBillVoteName() {
    }

    public TlPrintBillVoteName(String tlPrintBillVoteName, Integer tlPrintBillVoteId, Integer tlPrintBillVoteOrder) {
       this.tlPrintBillVoteName = tlPrintBillVoteName;
       this.tlPrintBillVoteId = tlPrintBillVoteId;
       this.tlPrintBillVoteOrder = tlPrintBillVoteOrder;
    }
   
    public Integer getTlPrintBillVoteNameId() {
        return this.tlPrintBillVoteNameId;
    }
    
    public void setTlPrintBillVoteNameId(Integer tlPrintBillVoteNameId) {
        this.tlPrintBillVoteNameId = tlPrintBillVoteNameId;
    }
    public String getTlPrintBillVoteName() {
        return this.tlPrintBillVoteName;
    }
    
    public void setTlPrintBillVoteName(String tlPrintBillVoteName) {
        this.tlPrintBillVoteName = tlPrintBillVoteName;
    }
    public Integer getTlPrintBillVoteId() {
        return this.tlPrintBillVoteId;
    }
    
    public void setTlPrintBillVoteId(Integer tlPrintBillVoteId) {
        this.tlPrintBillVoteId = tlPrintBillVoteId;
    }
    public Integer getTlPrintBillVoteOrder() {
        return this.tlPrintBillVoteOrder;
    }
    
    public void setTlPrintBillVoteOrder(Integer tlPrintBillVoteOrder) {
        this.tlPrintBillVoteOrder = tlPrintBillVoteOrder;
    }




}


