package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * TlSendApproveCat generated by hbm2java
 */
public class TlSendApproveCat  implements java.io.Serializable {


     private Integer tlSendApproveCatId;
     private String tlSendApproveCat;

    public TlSendApproveCat() {
    }

    public TlSendApproveCat(String tlSendApproveCat) {
       this.tlSendApproveCat = tlSendApproveCat;
    }
   
    public Integer getTlSendApproveCatId() {
        return this.tlSendApproveCatId;
    }
    
    public void setTlSendApproveCatId(Integer tlSendApproveCatId) {
        this.tlSendApproveCatId = tlSendApproveCatId;
    }
    public String getTlSendApproveCat() {
        return this.tlSendApproveCat;
    }
    
    public void setTlSendApproveCat(String tlSendApproveCat) {
        this.tlSendApproveCat = tlSendApproveCat;
    }




}


