package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TlSubType generated by hbm2java
 */
public class TlSubType  implements java.io.Serializable {


     private Integer tlSubTypeId;
     private TlPaidType tlPaidType;
     private TlType tlType;
     private TlVoteCategory tlVoteCategory;
     private String tlSubTypeEng;
     private String tlSubTypeSin;
     private Integer tlSubTypeStatus;
     private Integer tlSubApproveSendOrNot;
     private Integer tlApproveSendPath;
     private Set<TlChargingScheme> tlChargingSchemes = new HashSet<TlChargingScheme>(0);
     private Set<TlNature> tlNatures = new HashSet<TlNature>(0);
     private Set<TlAppLicenceNoTbl> tlAppLicenceNoTbls = new HashSet<TlAppLicenceNoTbl>(0);
     private Set<TlPayDetails> tlPayDetailses = new HashSet<TlPayDetails>(0);

    public TlSubType() {
    }

    public TlSubType(TlPaidType tlPaidType, TlType tlType, TlVoteCategory tlVoteCategory, String tlSubTypeEng, String tlSubTypeSin, Integer tlSubTypeStatus, Integer tlSubApproveSendOrNot, Integer tlApproveSendPath, Set<TlChargingScheme> tlChargingSchemes, Set<TlNature> tlNatures, Set<TlAppLicenceNoTbl> tlAppLicenceNoTbls, Set<TlPayDetails> tlPayDetailses) {
       this.tlPaidType = tlPaidType;
       this.tlType = tlType;
       this.tlVoteCategory = tlVoteCategory;
       this.tlSubTypeEng = tlSubTypeEng;
       this.tlSubTypeSin = tlSubTypeSin;
       this.tlSubTypeStatus = tlSubTypeStatus;
       this.tlSubApproveSendOrNot = tlSubApproveSendOrNot;
       this.tlApproveSendPath = tlApproveSendPath;
       this.tlChargingSchemes = tlChargingSchemes;
       this.tlNatures = tlNatures;
       this.tlAppLicenceNoTbls = tlAppLicenceNoTbls;
       this.tlPayDetailses = tlPayDetailses;
    }
   
    public Integer getTlSubTypeId() {
        return this.tlSubTypeId;
    }
    
    public void setTlSubTypeId(Integer tlSubTypeId) {
        this.tlSubTypeId = tlSubTypeId;
    }
    public TlPaidType getTlPaidType() {
        return this.tlPaidType;
    }
    
    public void setTlPaidType(TlPaidType tlPaidType) {
        this.tlPaidType = tlPaidType;
    }
    public TlType getTlType() {
        return this.tlType;
    }
    
    public void setTlType(TlType tlType) {
        this.tlType = tlType;
    }
    public TlVoteCategory getTlVoteCategory() {
        return this.tlVoteCategory;
    }
    
    public void setTlVoteCategory(TlVoteCategory tlVoteCategory) {
        this.tlVoteCategory = tlVoteCategory;
    }
    public String getTlSubTypeEng() {
        return this.tlSubTypeEng;
    }
    
    public void setTlSubTypeEng(String tlSubTypeEng) {
        this.tlSubTypeEng = tlSubTypeEng;
    }
    public String getTlSubTypeSin() {
        return this.tlSubTypeSin;
    }
    
    public void setTlSubTypeSin(String tlSubTypeSin) {
        this.tlSubTypeSin = tlSubTypeSin;
    }
    public Integer getTlSubTypeStatus() {
        return this.tlSubTypeStatus;
    }
    
    public void setTlSubTypeStatus(Integer tlSubTypeStatus) {
        this.tlSubTypeStatus = tlSubTypeStatus;
    }
    public Integer getTlSubApproveSendOrNot() {
        return this.tlSubApproveSendOrNot;
    }
    
    public void setTlSubApproveSendOrNot(Integer tlSubApproveSendOrNot) {
        this.tlSubApproveSendOrNot = tlSubApproveSendOrNot;
    }
    public Integer getTlApproveSendPath() {
        return this.tlApproveSendPath;
    }
    
    public void setTlApproveSendPath(Integer tlApproveSendPath) {
        this.tlApproveSendPath = tlApproveSendPath;
    }
    public Set<TlChargingScheme> getTlChargingSchemes() {
        return this.tlChargingSchemes;
    }
    
    public void setTlChargingSchemes(Set<TlChargingScheme> tlChargingSchemes) {
        this.tlChargingSchemes = tlChargingSchemes;
    }
    public Set<TlNature> getTlNatures() {
        return this.tlNatures;
    }
    
    public void setTlNatures(Set<TlNature> tlNatures) {
        this.tlNatures = tlNatures;
    }
    public Set<TlAppLicenceNoTbl> getTlAppLicenceNoTbls() {
        return this.tlAppLicenceNoTbls;
    }
    
    public void setTlAppLicenceNoTbls(Set<TlAppLicenceNoTbl> tlAppLicenceNoTbls) {
        this.tlAppLicenceNoTbls = tlAppLicenceNoTbls;
    }
    public Set<TlPayDetails> getTlPayDetailses() {
        return this.tlPayDetailses;
    }
    
    public void setTlPayDetailses(Set<TlPayDetails> tlPayDetailses) {
        this.tlPayDetailses = tlPayDetailses;
    }




}


