package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TlSubnature generated by hbm2java
 */
public class TlSubnature  implements java.io.Serializable {


     private Integer idTlSubnatuer;
     private TlNature tlNature;
     private String tlSubEname;
     private String tlSubSname;
     private Integer tlSubStatusId;
     private Set<TlPayDetails> tlPayDetailses = new HashSet<TlPayDetails>(0);

    public TlSubnature() {
    }

    public TlSubnature(TlNature tlNature, String tlSubEname, String tlSubSname, Integer tlSubStatusId, Set<TlPayDetails> tlPayDetailses) {
       this.tlNature = tlNature;
       this.tlSubEname = tlSubEname;
       this.tlSubSname = tlSubSname;
       this.tlSubStatusId = tlSubStatusId;
       this.tlPayDetailses = tlPayDetailses;
    }
   
    public Integer getIdTlSubnatuer() {
        return this.idTlSubnatuer;
    }
    
    public void setIdTlSubnatuer(Integer idTlSubnatuer) {
        this.idTlSubnatuer = idTlSubnatuer;
    }
    public TlNature getTlNature() {
        return this.tlNature;
    }
    
    public void setTlNature(TlNature tlNature) {
        this.tlNature = tlNature;
    }
    public String getTlSubEname() {
        return this.tlSubEname;
    }
    
    public void setTlSubEname(String tlSubEname) {
        this.tlSubEname = tlSubEname;
    }
    public String getTlSubSname() {
        return this.tlSubSname;
    }
    
    public void setTlSubSname(String tlSubSname) {
        this.tlSubSname = tlSubSname;
    }
    public Integer getTlSubStatusId() {
        return this.tlSubStatusId;
    }
    
    public void setTlSubStatusId(Integer tlSubStatusId) {
        this.tlSubStatusId = tlSubStatusId;
    }
    public Set<TlPayDetails> getTlPayDetailses() {
        return this.tlPayDetailses;
    }
    
    public void setTlPayDetailses(Set<TlPayDetails> tlPayDetailses) {
        this.tlPayDetailses = tlPayDetailses;
    }




}


