package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TlUseWhatStatus generated by hbm2java
 */
public class TlUseWhatStatus  implements java.io.Serializable {


     private int tlUseWhatStatusId;
     private String tlUseWhatStatus;
     private Set<TlChargingScheme> tlChargingSchemes = new HashSet<TlChargingScheme>(0);

    public TlUseWhatStatus() {
    }

	
    public TlUseWhatStatus(int tlUseWhatStatusId) {
        this.tlUseWhatStatusId = tlUseWhatStatusId;
    }
    public TlUseWhatStatus(int tlUseWhatStatusId, String tlUseWhatStatus, Set<TlChargingScheme> tlChargingSchemes) {
       this.tlUseWhatStatusId = tlUseWhatStatusId;
       this.tlUseWhatStatus = tlUseWhatStatus;
       this.tlChargingSchemes = tlChargingSchemes;
    }
   
    public int getTlUseWhatStatusId() {
        return this.tlUseWhatStatusId;
    }
    
    public void setTlUseWhatStatusId(int tlUseWhatStatusId) {
        this.tlUseWhatStatusId = tlUseWhatStatusId;
    }
    public String getTlUseWhatStatus() {
        return this.tlUseWhatStatus;
    }
    
    public void setTlUseWhatStatus(String tlUseWhatStatus) {
        this.tlUseWhatStatus = tlUseWhatStatus;
    }
    public Set<TlChargingScheme> getTlChargingSchemes() {
        return this.tlChargingSchemes;
    }
    
    public void setTlChargingSchemes(Set<TlChargingScheme> tlChargingSchemes) {
        this.tlChargingSchemes = tlChargingSchemes;
    }




}


