package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Unique generated by hbm2java
 */
public class Unique  implements java.io.Serializable {


     private Integer idUnique;
     private Integer customerId;
     private String cusNic;
     private String cusName;
     private Integer appcatId;
     private Integer appId;
     private String mobile;
     private String confermCode;
     private Integer rating;
     private Date startAt;
     private String location;
     private Integer oldUinqueId;
     private Integer status;
     private Set<Steps> stepses = new HashSet<Steps>(0);

    public Unique() {
    }

    public Unique(Integer customerId, String cusNic, String cusName, Integer appcatId, Integer appId, String mobile, String confermCode, Integer rating, Date startAt, String location, Integer oldUinqueId, Integer status, Set<Steps> stepses) {
       this.customerId = customerId;
       this.cusNic = cusNic;
       this.cusName = cusName;
       this.appcatId = appcatId;
       this.appId = appId;
       this.mobile = mobile;
       this.confermCode = confermCode;
       this.rating = rating;
       this.startAt = startAt;
       this.location = location;
       this.oldUinqueId = oldUinqueId;
       this.status = status;
       this.stepses = stepses;
    }
   
    public Integer getIdUnique() {
        return this.idUnique;
    }
    
    public void setIdUnique(Integer idUnique) {
        this.idUnique = idUnique;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getCusNic() {
        return this.cusNic;
    }
    
    public void setCusNic(String cusNic) {
        this.cusNic = cusNic;
    }
    public String getCusName() {
        return this.cusName;
    }
    
    public void setCusName(String cusName) {
        this.cusName = cusName;
    }
    public Integer getAppcatId() {
        return this.appcatId;
    }
    
    public void setAppcatId(Integer appcatId) {
        this.appcatId = appcatId;
    }
    public Integer getAppId() {
        return this.appId;
    }
    
    public void setAppId(Integer appId) {
        this.appId = appId;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getConfermCode() {
        return this.confermCode;
    }
    
    public void setConfermCode(String confermCode) {
        this.confermCode = confermCode;
    }
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }
    public Date getStartAt() {
        return this.startAt;
    }
    
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Integer getOldUinqueId() {
        return this.oldUinqueId;
    }
    
    public void setOldUinqueId(Integer oldUinqueId) {
        this.oldUinqueId = oldUinqueId;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Steps> getStepses() {
        return this.stepses;
    }
    
    public void setStepses(Set<Steps> stepses) {
        this.stepses = stepses;
    }




}


