package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Version generated by hbm2java
 */
public class Version  implements java.io.Serializable {


     private Integer idVersion;
     private Integer vnoint;
     private String vnostring;
     private Date vdate;
     private Integer priority;
     private String downlink;
     private String downpage;
     private String description;
     private Integer status;

    public Version() {
    }

    public Version(Integer vnoint, String vnostring, Date vdate, Integer priority, String downlink, String downpage, String description, Integer status) {
       this.vnoint = vnoint;
       this.vnostring = vnostring;
       this.vdate = vdate;
       this.priority = priority;
       this.downlink = downlink;
       this.downpage = downpage;
       this.description = description;
       this.status = status;
    }
   
    public Integer getIdVersion() {
        return this.idVersion;
    }
    
    public void setIdVersion(Integer idVersion) {
        this.idVersion = idVersion;
    }
    public Integer getVnoint() {
        return this.vnoint;
    }
    
    public void setVnoint(Integer vnoint) {
        this.vnoint = vnoint;
    }
    public String getVnostring() {
        return this.vnostring;
    }
    
    public void setVnostring(String vnostring) {
        this.vnostring = vnostring;
    }
    public Date getVdate() {
        return this.vdate;
    }
    
    public void setVdate(Date vdate) {
        this.vdate = vdate;
    }
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    public String getDownlink() {
        return this.downlink;
    }
    
    public void setDownlink(String downlink) {
        this.downlink = downlink;
    }
    public String getDownpage() {
        return this.downpage;
    }
    
    public void setDownpage(String downpage) {
        this.downpage = downpage;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


