package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * Vote generated by hbm2java
 */
public class Vote  implements java.io.Serializable {


     private Integer idVote;
     private ProgramSubtitle programSubtitle;
     private String voteNo;
     private String voteName;
     private Double voteCurrentBalance;
     private Double voteAlocation;
     private Integer voteStatus;
     private Integer voteSyn;
     private String voteBankAccountNo;

    public Vote() {
    }

	
    public Vote(ProgramSubtitle programSubtitle) {
        this.programSubtitle = programSubtitle;
    }
    public Vote(ProgramSubtitle programSubtitle, String voteNo, String voteName, Double voteCurrentBalance, Double voteAlocation, Integer voteStatus, Integer voteSyn, String voteBankAccountNo) {
       this.programSubtitle = programSubtitle;
       this.voteNo = voteNo;
       this.voteName = voteName;
       this.voteCurrentBalance = voteCurrentBalance;
       this.voteAlocation = voteAlocation;
       this.voteStatus = voteStatus;
       this.voteSyn = voteSyn;
       this.voteBankAccountNo = voteBankAccountNo;
    }
   
    public Integer getIdVote() {
        return this.idVote;
    }
    
    public void setIdVote(Integer idVote) {
        this.idVote = idVote;
    }
    public ProgramSubtitle getProgramSubtitle() {
        return this.programSubtitle;
    }
    
    public void setProgramSubtitle(ProgramSubtitle programSubtitle) {
        this.programSubtitle = programSubtitle;
    }
    public String getVoteNo() {
        return this.voteNo;
    }
    
    public void setVoteNo(String voteNo) {
        this.voteNo = voteNo;
    }
    public String getVoteName() {
        return this.voteName;
    }
    
    public void setVoteName(String voteName) {
        this.voteName = voteName;
    }
    public Double getVoteCurrentBalance() {
        return this.voteCurrentBalance;
    }
    
    public void setVoteCurrentBalance(Double voteCurrentBalance) {
        this.voteCurrentBalance = voteCurrentBalance;
    }
    public Double getVoteAlocation() {
        return this.voteAlocation;
    }
    
    public void setVoteAlocation(Double voteAlocation) {
        this.voteAlocation = voteAlocation;
    }
    public Integer getVoteStatus() {
        return this.voteStatus;
    }
    
    public void setVoteStatus(Integer voteStatus) {
        this.voteStatus = voteStatus;
    }
    public Integer getVoteSyn() {
        return this.voteSyn;
    }
    
    public void setVoteSyn(Integer voteSyn) {
        this.voteSyn = voteSyn;
    }
    public String getVoteBankAccountNo() {
        return this.voteBankAccountNo;
    }
    
    public void setVoteBankAccountNo(String voteBankAccountNo) {
        this.voteBankAccountNo = voteBankAccountNo;
    }




}


