package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WbMDivisionHasMeterReader generated by hbm2java
 */
public class WbMDivisionHasMeterReader  implements java.io.Serializable {


     private Integer divisionHasMeterReaderId;
     private User user;
     private WbMDevision wbMDevision;
     private Integer divisionHasMeterReaderStatus;
     private Set<WbTBillProcess> wbTBillProcesses = new HashSet<WbTBillProcess>(0);

    public WbMDivisionHasMeterReader() {
    }

    public WbMDivisionHasMeterReader(User user, WbMDevision wbMDevision, Integer divisionHasMeterReaderStatus, Set<WbTBillProcess> wbTBillProcesses) {
       this.user = user;
       this.wbMDevision = wbMDevision;
       this.divisionHasMeterReaderStatus = divisionHasMeterReaderStatus;
       this.wbTBillProcesses = wbTBillProcesses;
    }
   
    public Integer getDivisionHasMeterReaderId() {
        return this.divisionHasMeterReaderId;
    }
    
    public void setDivisionHasMeterReaderId(Integer divisionHasMeterReaderId) {
        this.divisionHasMeterReaderId = divisionHasMeterReaderId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public WbMDevision getWbMDevision() {
        return this.wbMDevision;
    }
    
    public void setWbMDevision(WbMDevision wbMDevision) {
        this.wbMDevision = wbMDevision;
    }
    public Integer getDivisionHasMeterReaderStatus() {
        return this.divisionHasMeterReaderStatus;
    }
    
    public void setDivisionHasMeterReaderStatus(Integer divisionHasMeterReaderStatus) {
        this.divisionHasMeterReaderStatus = divisionHasMeterReaderStatus;
    }
    public Set<WbTBillProcess> getWbTBillProcesses() {
        return this.wbTBillProcesses;
    }
    
    public void setWbTBillProcesses(Set<WbTBillProcess> wbTBillProcesses) {
        this.wbTBillProcesses = wbTBillProcesses;
    }




}


