package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WbMMeterStatus generated by hbm2java
 */
public class WbMMeterStatus  implements java.io.Serializable {


     private Integer wbMMeterStatusId;
     private String wbMMeterStatus;
     private Set<WbMReadingProblems> wbMReadingProblemses = new HashSet<WbMReadingProblems>(0);

    public WbMMeterStatus() {
    }

    public WbMMeterStatus(String wbMMeterStatus, Set<WbMReadingProblems> wbMReadingProblemses) {
       this.wbMMeterStatus = wbMMeterStatus;
       this.wbMReadingProblemses = wbMReadingProblemses;
    }
   
    public Integer getWbMMeterStatusId() {
        return this.wbMMeterStatusId;
    }
    
    public void setWbMMeterStatusId(Integer wbMMeterStatusId) {
        this.wbMMeterStatusId = wbMMeterStatusId;
    }
    public String getWbMMeterStatus() {
        return this.wbMMeterStatus;
    }
    
    public void setWbMMeterStatus(String wbMMeterStatus) {
        this.wbMMeterStatus = wbMMeterStatus;
    }
    public Set<WbMReadingProblems> getWbMReadingProblemses() {
        return this.wbMReadingProblemses;
    }
    
    public void setWbMReadingProblemses(Set<WbMReadingProblems> wbMReadingProblemses) {
        this.wbMReadingProblemses = wbMReadingProblemses;
    }




}


