package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WbMMainRoad generated by hbm2java
 */
public class WbMMainRoad  implements java.io.Serializable {


     private Integer id;
     private String roadName;
     private Date dateCreated;
     private Date dateModified;
     private String modifiedBy;
     private String status;
     private Set<WbMSubRoad> wbMSubRoads = new HashSet<WbMSubRoad>(0);

    public WbMMainRoad() {
    }

	
    public WbMMainRoad(String roadName, String status) {
        this.roadName = roadName;
        this.status = status;
    }
    public WbMMainRoad(String roadName, Date dateCreated, Date dateModified, String modifiedBy, String status, Set<WbMSubRoad> wbMSubRoads) {
       this.roadName = roadName;
       this.dateCreated = dateCreated;
       this.dateModified = dateModified;
       this.modifiedBy = modifiedBy;
       this.status = status;
       this.wbMSubRoads = wbMSubRoads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRoadName() {
        return this.roadName;
    }
    
    public void setRoadName(String roadName) {
        this.roadName = roadName;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<WbMSubRoad> getWbMSubRoads() {
        return this.wbMSubRoads;
    }
    
    public void setWbMSubRoads(Set<WbMSubRoad> wbMSubRoads) {
        this.wbMSubRoads = wbMSubRoads;
    }




}


