package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WbMNature generated by hbm2java
 */
public class WbMNature  implements java.io.Serializable {


     private Integer id;
     private String nature;
     private Double charge;
     private String status;
     private Set<WbTBillProcess> wbTBillProcesses = new HashSet<WbTBillProcess>(0);
     private Set<WbMConnection> wbMConnections = new HashSet<WbMConnection>(0);
     private Set<WbMCustomer> wbMCustomers = new HashSet<WbMCustomer>(0);
     private Set<WbTChargeScheme> wbTChargeSchemes = new HashSet<WbTChargeScheme>(0);

    public WbMNature() {
    }

	
    public WbMNature(String status) {
        this.status = status;
    }
    public WbMNature(String nature, Double charge, String status, Set<WbTBillProcess> wbTBillProcesses, Set<WbMConnection> wbMConnections, Set<WbMCustomer> wbMCustomers, Set<WbTChargeScheme> wbTChargeSchemes) {
       this.nature = nature;
       this.charge = charge;
       this.status = status;
       this.wbTBillProcesses = wbTBillProcesses;
       this.wbMConnections = wbMConnections;
       this.wbMCustomers = wbMCustomers;
       this.wbTChargeSchemes = wbTChargeSchemes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }
    public Double getCharge() {
        return this.charge;
    }
    
    public void setCharge(Double charge) {
        this.charge = charge;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<WbTBillProcess> getWbTBillProcesses() {
        return this.wbTBillProcesses;
    }
    
    public void setWbTBillProcesses(Set<WbTBillProcess> wbTBillProcesses) {
        this.wbTBillProcesses = wbTBillProcesses;
    }
    public Set<WbMConnection> getWbMConnections() {
        return this.wbMConnections;
    }
    
    public void setWbMConnections(Set<WbMConnection> wbMConnections) {
        this.wbMConnections = wbMConnections;
    }
    public Set<WbMCustomer> getWbMCustomers() {
        return this.wbMCustomers;
    }
    
    public void setWbMCustomers(Set<WbMCustomer> wbMCustomers) {
        this.wbMCustomers = wbMCustomers;
    }
    public Set<WbTChargeScheme> getWbTChargeSchemes() {
        return this.wbTChargeSchemes;
    }
    
    public void setWbTChargeSchemes(Set<WbTChargeScheme> wbTChargeSchemes) {
        this.wbTChargeSchemes = wbTChargeSchemes;
    }




}


