package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WbMNatureChangeTbl generated by hbm2java
 */
public class WbMNatureChangeTbl  implements java.io.Serializable {


     private Integer wbNatureAndConTypeChangeId;
     private User user;
     private WbMConnection wbMConnection;
     private String previousNatureOrType;
     private String currentNatureOrType;
     private Date changeDate;
     private Date changeTime;
     private String changeDescription;

    public WbMNatureChangeTbl() {
    }

    public WbMNatureChangeTbl(User user, WbMConnection wbMConnection, String previousNatureOrType, String currentNatureOrType, Date changeDate, Date changeTime, String changeDescription) {
       this.user = user;
       this.wbMConnection = wbMConnection;
       this.previousNatureOrType = previousNatureOrType;
       this.currentNatureOrType = currentNatureOrType;
       this.changeDate = changeDate;
       this.changeTime = changeTime;
       this.changeDescription = changeDescription;
    }
   
    public Integer getWbNatureAndConTypeChangeId() {
        return this.wbNatureAndConTypeChangeId;
    }
    
    public void setWbNatureAndConTypeChangeId(Integer wbNatureAndConTypeChangeId) {
        this.wbNatureAndConTypeChangeId = wbNatureAndConTypeChangeId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public WbMConnection getWbMConnection() {
        return this.wbMConnection;
    }
    
    public void setWbMConnection(WbMConnection wbMConnection) {
        this.wbMConnection = wbMConnection;
    }
    public String getPreviousNatureOrType() {
        return this.previousNatureOrType;
    }
    
    public void setPreviousNatureOrType(String previousNatureOrType) {
        this.previousNatureOrType = previousNatureOrType;
    }
    public String getCurrentNatureOrType() {
        return this.currentNatureOrType;
    }
    
    public void setCurrentNatureOrType(String currentNatureOrType) {
        this.currentNatureOrType = currentNatureOrType;
    }
    public Date getChangeDate() {
        return this.changeDate;
    }
    
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }
    public Date getChangeTime() {
        return this.changeTime;
    }
    
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }
    public String getChangeDescription() {
        return this.changeDescription;
    }
    
    public void setChangeDescription(String changeDescription) {
        this.changeDescription = changeDescription;
    }




}


