package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WbMProcStatus generated by hbm2java
 */
public class WbMProcStatus  implements java.io.Serializable {


     private Integer wbMProcStatusId;
     private String wbMProcStatus;
     private Set<WbTBillProcess> wbTBillProcesses = new HashSet<WbTBillProcess>(0);

    public WbMProcStatus() {
    }

    public WbMProcStatus(String wbMProcStatus, Set<WbTBillProcess> wbTBillProcesses) {
       this.wbMProcStatus = wbMProcStatus;
       this.wbTBillProcesses = wbTBillProcesses;
    }
   
    public Integer getWbMProcStatusId() {
        return this.wbMProcStatusId;
    }
    
    public void setWbMProcStatusId(Integer wbMProcStatusId) {
        this.wbMProcStatusId = wbMProcStatusId;
    }
    public String getWbMProcStatus() {
        return this.wbMProcStatus;
    }
    
    public void setWbMProcStatus(String wbMProcStatus) {
        this.wbMProcStatus = wbMProcStatus;
    }
    public Set<WbTBillProcess> getWbTBillProcesses() {
        return this.wbTBillProcesses;
    }
    
    public void setWbTBillProcesses(Set<WbTBillProcess> wbTBillProcesses) {
        this.wbTBillProcesses = wbTBillProcesses;
    }




}


