package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * WbMUseOldOrNewStreetStatus generated by hbm2java
 */
public class WbMUseOldOrNewStreetStatus  implements java.io.Serializable {


     private int wbMUseOldOrNewStreetId;
     private Integer wbMUseOldOrNewStatus;
     private String wbMUseOldOrNewComment;

    public WbMUseOldOrNewStreetStatus() {
    }

	
    public WbMUseOldOrNewStreetStatus(int wbMUseOldOrNewStreetId) {
        this.wbMUseOldOrNewStreetId = wbMUseOldOrNewStreetId;
    }
    public WbMUseOldOrNewStreetStatus(int wbMUseOldOrNewStreetId, Integer wbMUseOldOrNewStatus, String wbMUseOldOrNewComment) {
       this.wbMUseOldOrNewStreetId = wbMUseOldOrNewStreetId;
       this.wbMUseOldOrNewStatus = wbMUseOldOrNewStatus;
       this.wbMUseOldOrNewComment = wbMUseOldOrNewComment;
    }
   
    public int getWbMUseOldOrNewStreetId() {
        return this.wbMUseOldOrNewStreetId;
    }
    
    public void setWbMUseOldOrNewStreetId(int wbMUseOldOrNewStreetId) {
        this.wbMUseOldOrNewStreetId = wbMUseOldOrNewStreetId;
    }
    public Integer getWbMUseOldOrNewStatus() {
        return this.wbMUseOldOrNewStatus;
    }
    
    public void setWbMUseOldOrNewStatus(Integer wbMUseOldOrNewStatus) {
        this.wbMUseOldOrNewStatus = wbMUseOldOrNewStatus;
    }
    public String getWbMUseOldOrNewComment() {
        return this.wbMUseOldOrNewComment;
    }
    
    public void setWbMUseOldOrNewComment(String wbMUseOldOrNewComment) {
        this.wbMUseOldOrNewComment = wbMUseOldOrNewComment;
    }




}


