package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * WbProcessTbl generated by hbm2java
 */
public class WbProcessTbl  implements java.io.Serializable {


     private Integer wbProcessTblId;
     private WbMConnection wbMConnection;
     private String wbProcessTblInvoiceNo;
     private Double wbProcessTblLya;
     private Double wbProcessTblLyaBal;
     private Double wbProcessTblLma;
     private Double wbProcessTblLmaBal;
     private Double wbProcessTblTma;
     private Double wbProcessTblTmaBal;
     private Double wbProcessTblVat;
     private Double wbProcessTblNbt;
     private Double wbProcessTblStamp;
     private Integer wbProcessTblYear;
     private Integer wbProcessTblMonth;
     private String wbProcessTblComStatus;

    public WbProcessTbl() {
    }

    public WbProcessTbl(WbMConnection wbMConnection, String wbProcessTblInvoiceNo, Double wbProcessTblLya, Double wbProcessTblLyaBal, Double wbProcessTblLma, Double wbProcessTblLmaBal, Double wbProcessTblTma, Double wbProcessTblTmaBal, Double wbProcessTblVat, Double wbProcessTblNbt, Double wbProcessTblStamp, Integer wbProcessTblYear, Integer wbProcessTblMonth, String wbProcessTblComStatus) {
       this.wbMConnection = wbMConnection;
       this.wbProcessTblInvoiceNo = wbProcessTblInvoiceNo;
       this.wbProcessTblLya = wbProcessTblLya;
       this.wbProcessTblLyaBal = wbProcessTblLyaBal;
       this.wbProcessTblLma = wbProcessTblLma;
       this.wbProcessTblLmaBal = wbProcessTblLmaBal;
       this.wbProcessTblTma = wbProcessTblTma;
       this.wbProcessTblTmaBal = wbProcessTblTmaBal;
       this.wbProcessTblVat = wbProcessTblVat;
       this.wbProcessTblNbt = wbProcessTblNbt;
       this.wbProcessTblStamp = wbProcessTblStamp;
       this.wbProcessTblYear = wbProcessTblYear;
       this.wbProcessTblMonth = wbProcessTblMonth;
       this.wbProcessTblComStatus = wbProcessTblComStatus;
    }
   
    public Integer getWbProcessTblId() {
        return this.wbProcessTblId;
    }
    
    public void setWbProcessTblId(Integer wbProcessTblId) {
        this.wbProcessTblId = wbProcessTblId;
    }
    public WbMConnection getWbMConnection() {
        return this.wbMConnection;
    }
    
    public void setWbMConnection(WbMConnection wbMConnection) {
        this.wbMConnection = wbMConnection;
    }
    public String getWbProcessTblInvoiceNo() {
        return this.wbProcessTblInvoiceNo;
    }
    
    public void setWbProcessTblInvoiceNo(String wbProcessTblInvoiceNo) {
        this.wbProcessTblInvoiceNo = wbProcessTblInvoiceNo;
    }
    public Double getWbProcessTblLya() {
        return this.wbProcessTblLya;
    }
    
    public void setWbProcessTblLya(Double wbProcessTblLya) {
        this.wbProcessTblLya = wbProcessTblLya;
    }
    public Double getWbProcessTblLyaBal() {
        return this.wbProcessTblLyaBal;
    }
    
    public void setWbProcessTblLyaBal(Double wbProcessTblLyaBal) {
        this.wbProcessTblLyaBal = wbProcessTblLyaBal;
    }
    public Double getWbProcessTblLma() {
        return this.wbProcessTblLma;
    }
    
    public void setWbProcessTblLma(Double wbProcessTblLma) {
        this.wbProcessTblLma = wbProcessTblLma;
    }
    public Double getWbProcessTblLmaBal() {
        return this.wbProcessTblLmaBal;
    }
    
    public void setWbProcessTblLmaBal(Double wbProcessTblLmaBal) {
        this.wbProcessTblLmaBal = wbProcessTblLmaBal;
    }
    public Double getWbProcessTblTma() {
        return this.wbProcessTblTma;
    }
    
    public void setWbProcessTblTma(Double wbProcessTblTma) {
        this.wbProcessTblTma = wbProcessTblTma;
    }
    public Double getWbProcessTblTmaBal() {
        return this.wbProcessTblTmaBal;
    }
    
    public void setWbProcessTblTmaBal(Double wbProcessTblTmaBal) {
        this.wbProcessTblTmaBal = wbProcessTblTmaBal;
    }
    public Double getWbProcessTblVat() {
        return this.wbProcessTblVat;
    }
    
    public void setWbProcessTblVat(Double wbProcessTblVat) {
        this.wbProcessTblVat = wbProcessTblVat;
    }
    public Double getWbProcessTblNbt() {
        return this.wbProcessTblNbt;
    }
    
    public void setWbProcessTblNbt(Double wbProcessTblNbt) {
        this.wbProcessTblNbt = wbProcessTblNbt;
    }
    public Double getWbProcessTblStamp() {
        return this.wbProcessTblStamp;
    }
    
    public void setWbProcessTblStamp(Double wbProcessTblStamp) {
        this.wbProcessTblStamp = wbProcessTblStamp;
    }
    public Integer getWbProcessTblYear() {
        return this.wbProcessTblYear;
    }
    
    public void setWbProcessTblYear(Integer wbProcessTblYear) {
        this.wbProcessTblYear = wbProcessTblYear;
    }
    public Integer getWbProcessTblMonth() {
        return this.wbProcessTblMonth;
    }
    
    public void setWbProcessTblMonth(Integer wbProcessTblMonth) {
        this.wbProcessTblMonth = wbProcessTblMonth;
    }
    public String getWbProcessTblComStatus() {
        return this.wbProcessTblComStatus;
    }
    
    public void setWbProcessTblComStatus(String wbProcessTblComStatus) {
        this.wbProcessTblComStatus = wbProcessTblComStatus;
    }




}


