package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * WbTGetFirstPaidAmount generated by hbm2java
 */
public class WbTGetFirstPaidAmount  implements java.io.Serializable {


     private int wbTGetProConId;
     private Double wbTGetProPaidAmount;

    public WbTGetFirstPaidAmount() {
    }

	
    public WbTGetFirstPaidAmount(int wbTGetProConId) {
        this.wbTGetProConId = wbTGetProConId;
    }
    public WbTGetFirstPaidAmount(int wbTGetProConId, Double wbTGetProPaidAmount) {
       this.wbTGetProConId = wbTGetProConId;
       this.wbTGetProPaidAmount = wbTGetProPaidAmount;
    }
   
    public int getWbTGetProConId() {
        return this.wbTGetProConId;
    }
    
    public void setWbTGetProConId(int wbTGetProConId) {
        this.wbTGetProConId = wbTGetProConId;
    }
    public Double getWbTGetProPaidAmount() {
        return this.wbTGetProPaidAmount;
    }
    
    public void setWbTGetProPaidAmount(Double wbTGetProPaidAmount) {
        this.wbTGetProPaidAmount = wbTGetProPaidAmount;
    }




}


