package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WbTPaid generated by hbm2java
 */
public class WbTPaid  implements java.io.Serializable {


     private Integer wbTPaidDetailId;
     private Receipt receipt;
     private User user;
     private WbMConnection wbMConnection;
     private String wbTReceiptNo;
     private Double wbTLya;
     private Double wbTLma;
     private Double wbTTma;
     private Double wbTOp;
     private Double wbTVat;
     private Integer wbTCompleteStatus;
     private Date wbTDate;
     private Date wbTTime;

    public WbTPaid() {
    }

	
    public WbTPaid(Receipt receipt, String wbTReceiptNo) {
        this.receipt = receipt;
        this.wbTReceiptNo = wbTReceiptNo;
    }
    public WbTPaid(Receipt receipt, User user, WbMConnection wbMConnection, String wbTReceiptNo, Double wbTLya, Double wbTLma, Double wbTTma, Double wbTOp, Double wbTVat, Integer wbTCompleteStatus, Date wbTDate, Date wbTTime) {
       this.receipt = receipt;
       this.user = user;
       this.wbMConnection = wbMConnection;
       this.wbTReceiptNo = wbTReceiptNo;
       this.wbTLya = wbTLya;
       this.wbTLma = wbTLma;
       this.wbTTma = wbTTma;
       this.wbTOp = wbTOp;
       this.wbTVat = wbTVat;
       this.wbTCompleteStatus = wbTCompleteStatus;
       this.wbTDate = wbTDate;
       this.wbTTime = wbTTime;
    }
   
    public Integer getWbTPaidDetailId() {
        return this.wbTPaidDetailId;
    }
    
    public void setWbTPaidDetailId(Integer wbTPaidDetailId) {
        this.wbTPaidDetailId = wbTPaidDetailId;
    }
    public Receipt getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public WbMConnection getWbMConnection() {
        return this.wbMConnection;
    }
    
    public void setWbMConnection(WbMConnection wbMConnection) {
        this.wbMConnection = wbMConnection;
    }
    public String getWbTReceiptNo() {
        return this.wbTReceiptNo;
    }
    
    public void setWbTReceiptNo(String wbTReceiptNo) {
        this.wbTReceiptNo = wbTReceiptNo;
    }
    public Double getWbTLya() {
        return this.wbTLya;
    }
    
    public void setWbTLya(Double wbTLya) {
        this.wbTLya = wbTLya;
    }
    public Double getWbTLma() {
        return this.wbTLma;
    }
    
    public void setWbTLma(Double wbTLma) {
        this.wbTLma = wbTLma;
    }
    public Double getWbTTma() {
        return this.wbTTma;
    }
    
    public void setWbTTma(Double wbTTma) {
        this.wbTTma = wbTTma;
    }
    public Double getWbTOp() {
        return this.wbTOp;
    }
    
    public void setWbTOp(Double wbTOp) {
        this.wbTOp = wbTOp;
    }
    public Double getWbTVat() {
        return this.wbTVat;
    }
    
    public void setWbTVat(Double wbTVat) {
        this.wbTVat = wbTVat;
    }
    public Integer getWbTCompleteStatus() {
        return this.wbTCompleteStatus;
    }
    
    public void setWbTCompleteStatus(Integer wbTCompleteStatus) {
        this.wbTCompleteStatus = wbTCompleteStatus;
    }
    public Date getWbTDate() {
        return this.wbTDate;
    }
    
    public void setWbTDate(Date wbTDate) {
        this.wbTDate = wbTDate;
    }
    public Date getWbTTime() {
        return this.wbTTime;
    }
    
    public void setWbTTime(Date wbTTime) {
        this.wbTTime = wbTTime;
    }




}


