package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WbULevel generated by hbm2java
 */
public class WbULevel  implements java.io.Serializable {


     private int LId;
     private String level;
     private Set<WbMUsers> wbMUserses = new HashSet<WbMUsers>(0);

    public WbULevel() {
    }

	
    public WbULevel(int LId, String level) {
        this.LId = LId;
        this.level = level;
    }
    public WbULevel(int LId, String level, Set<WbMUsers> wbMUserses) {
       this.LId = LId;
       this.level = level;
       this.wbMUserses = wbMUserses;
    }
   
    public int getLId() {
        return this.LId;
    }
    
    public void setLId(int LId) {
        this.LId = LId;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public Set<WbMUsers> getWbMUserses() {
        return this.wbMUserses;
    }
    
    public void setWbMUserses(Set<WbMUsers> wbMUserses) {
        this.wbMUserses = wbMUserses;
    }




}


