package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * WebPrivHasApproveCat generated by hbm2java
 */
public class WebPrivHasApproveCat  implements java.io.Serializable {


     private Integer idWebPrivHasApproveCat;
     private ApprovalCat approvalCat;
     private WebPrivilages webPrivilages;

    public WebPrivHasApproveCat() {
    }

    public WebPrivHasApproveCat(ApprovalCat approvalCat, WebPrivilages webPrivilages) {
       this.approvalCat = approvalCat;
       this.webPrivilages = webPrivilages;
    }
   
    public Integer getIdWebPrivHasApproveCat() {
        return this.idWebPrivHasApproveCat;
    }
    
    public void setIdWebPrivHasApproveCat(Integer idWebPrivHasApproveCat) {
        this.idWebPrivHasApproveCat = idWebPrivHasApproveCat;
    }
    public ApprovalCat getApprovalCat() {
        return this.approvalCat;
    }
    
    public void setApprovalCat(ApprovalCat approvalCat) {
        this.approvalCat = approvalCat;
    }
    public WebPrivilages getWebPrivilages() {
        return this.webPrivilages;
    }
    
    public void setWebPrivilages(WebPrivilages webPrivilages) {
        this.webPrivilages = webPrivilages;
    }




}


