package pojo;
// Generated Jul 9, 2020 11:48:20 AM by Hibernate Tools 4.3.1



/**
 * Xxx generated by hbm2java
 */
public class Xxx  implements java.io.Serializable {


     private Integer w;
     private String sdads;

    public Xxx() {
    }

    public Xxx(String sdads) {
       this.sdads = sdads;
    }
   
    public Integer getW() {
        return this.w;
    }
    
    public void setW(Integer w) {
        this.w = w;
    }
    public String getSdads() {
        return this.sdads;
    }
    
    public void setSdads(String sdads) {
        this.sdads = sdads;
    }




}


