package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AccountReceiptTitle generated by hbm2java
 */
public class AccountReceiptTitle  implements java.io.Serializable {


     private Integer idAccountReceiptTitle;
     private String artVoteAndBal;
     private String artProNameEng;
     private Integer artProCode;
     private String artTitleNameEng;
     private Integer atrTitleCode;
     private String artSubtitleNameEng;
     private Integer artSubtitleCode;
     private Integer artType1Id;
     private String artType1Name;
     private Integer artType2Id;
     private String artType2Name;
     private Integer artVoteOrBal;
     private Integer artOrder;
     private Integer artVBId;
     private String artProNameSinhala;
     private String artTitleNameSinhala;
     private String artSubtitleNameSinhala;
     private Set<Mixintype> mixintypes = new HashSet<Mixintype>(0);

    public AccountReceiptTitle() {
    }

    public AccountReceiptTitle(String artVoteAndBal, String artProNameEng, Integer artProCode, String artTitleNameEng, Integer atrTitleCode, String artSubtitleNameEng, Integer artSubtitleCode, Integer artType1Id, String artType1Name, Integer artType2Id, String artType2Name, Integer artVoteOrBal, Integer artOrder, Integer artVBId, String artProNameSinhala, String artTitleNameSinhala, String artSubtitleNameSinhala, Set<Mixintype> mixintypes) {
       this.artVoteAndBal = artVoteAndBal;
       this.artProNameEng = artProNameEng;
       this.artProCode = artProCode;
       this.artTitleNameEng = artTitleNameEng;
       this.atrTitleCode = atrTitleCode;
       this.artSubtitleNameEng = artSubtitleNameEng;
       this.artSubtitleCode = artSubtitleCode;
       this.artType1Id = artType1Id;
       this.artType1Name = artType1Name;
       this.artType2Id = artType2Id;
       this.artType2Name = artType2Name;
       this.artVoteOrBal = artVoteOrBal;
       this.artOrder = artOrder;
       this.artVBId = artVBId;
       this.artProNameSinhala = artProNameSinhala;
       this.artTitleNameSinhala = artTitleNameSinhala;
       this.artSubtitleNameSinhala = artSubtitleNameSinhala;
       this.mixintypes = mixintypes;
    }
   
    public Integer getIdAccountReceiptTitle() {
        return this.idAccountReceiptTitle;
    }
    
    public void setIdAccountReceiptTitle(Integer idAccountReceiptTitle) {
        this.idAccountReceiptTitle = idAccountReceiptTitle;
    }
    public String getArtVoteAndBal() {
        return this.artVoteAndBal;
    }
    
    public void setArtVoteAndBal(String artVoteAndBal) {
        this.artVoteAndBal = artVoteAndBal;
    }
    public String getArtProNameEng() {
        return this.artProNameEng;
    }
    
    public void setArtProNameEng(String artProNameEng) {
        this.artProNameEng = artProNameEng;
    }
    public Integer getArtProCode() {
        return this.artProCode;
    }
    
    public void setArtProCode(Integer artProCode) {
        this.artProCode = artProCode;
    }
    public String getArtTitleNameEng() {
        return this.artTitleNameEng;
    }
    
    public void setArtTitleNameEng(String artTitleNameEng) {
        this.artTitleNameEng = artTitleNameEng;
    }
    public Integer getAtrTitleCode() {
        return this.atrTitleCode;
    }
    
    public void setAtrTitleCode(Integer atrTitleCode) {
        this.atrTitleCode = atrTitleCode;
    }
    public String getArtSubtitleNameEng() {
        return this.artSubtitleNameEng;
    }
    
    public void setArtSubtitleNameEng(String artSubtitleNameEng) {
        this.artSubtitleNameEng = artSubtitleNameEng;
    }
    public Integer getArtSubtitleCode() {
        return this.artSubtitleCode;
    }
    
    public void setArtSubtitleCode(Integer artSubtitleCode) {
        this.artSubtitleCode = artSubtitleCode;
    }
    public Integer getArtType1Id() {
        return this.artType1Id;
    }
    
    public void setArtType1Id(Integer artType1Id) {
        this.artType1Id = artType1Id;
    }
    public String getArtType1Name() {
        return this.artType1Name;
    }
    
    public void setArtType1Name(String artType1Name) {
        this.artType1Name = artType1Name;
    }
    public Integer getArtType2Id() {
        return this.artType2Id;
    }
    
    public void setArtType2Id(Integer artType2Id) {
        this.artType2Id = artType2Id;
    }
    public String getArtType2Name() {
        return this.artType2Name;
    }
    
    public void setArtType2Name(String artType2Name) {
        this.artType2Name = artType2Name;
    }
    public Integer getArtVoteOrBal() {
        return this.artVoteOrBal;
    }
    
    public void setArtVoteOrBal(Integer artVoteOrBal) {
        this.artVoteOrBal = artVoteOrBal;
    }
    public Integer getArtOrder() {
        return this.artOrder;
    }
    
    public void setArtOrder(Integer artOrder) {
        this.artOrder = artOrder;
    }
    public Integer getArtVBId() {
        return this.artVBId;
    }
    
    public void setArtVBId(Integer artVBId) {
        this.artVBId = artVBId;
    }
    public String getArtProNameSinhala() {
        return this.artProNameSinhala;
    }
    
    public void setArtProNameSinhala(String artProNameSinhala) {
        this.artProNameSinhala = artProNameSinhala;
    }
    public String getArtTitleNameSinhala() {
        return this.artTitleNameSinhala;
    }
    
    public void setArtTitleNameSinhala(String artTitleNameSinhala) {
        this.artTitleNameSinhala = artTitleNameSinhala;
    }
    public String getArtSubtitleNameSinhala() {
        return this.artSubtitleNameSinhala;
    }
    
    public void setArtSubtitleNameSinhala(String artSubtitleNameSinhala) {
        this.artSubtitleNameSinhala = artSubtitleNameSinhala;
    }
    public Set<Mixintype> getMixintypes() {
        return this.mixintypes;
    }
    
    public void setMixintypes(Set<Mixintype> mixintypes) {
        this.mixintypes = mixintypes;
    }




}


