package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AccountPsThree generated by hbm2java
 */
public class AccountPsThree  implements java.io.Serializable {


     private Integer idReport;
     private Date reportDate;
     private String reportRiciptNo;
     private Integer reportRiciptId;
     private Integer reportVortId;
     private Integer reportAccountId;
     private Double reportAmount;
     private Integer reportUserId;
     private Integer reportApplicationId;
     private Integer reportApplicationCatId;
     private Integer reportStatus;
     private Integer officeIdOffice;

    public AccountPsThree() {
    }

    public AccountPsThree(Date reportDate, String reportRiciptNo, Integer reportRiciptId, Integer reportVortId, Integer reportAccountId, Double reportAmount, Integer reportUserId, Integer reportApplicationId, Integer reportApplicationCatId, Integer reportStatus, Integer officeIdOffice) {
       this.reportDate = reportDate;
       this.reportRiciptNo = reportRiciptNo;
       this.reportRiciptId = reportRiciptId;
       this.reportVortId = reportVortId;
       this.reportAccountId = reportAccountId;
       this.reportAmount = reportAmount;
       this.reportUserId = reportUserId;
       this.reportApplicationId = reportApplicationId;
       this.reportApplicationCatId = reportApplicationCatId;
       this.reportStatus = reportStatus;
       this.officeIdOffice = officeIdOffice;
    }
   
    public Integer getIdReport() {
        return this.idReport;
    }
    
    public void setIdReport(Integer idReport) {
        this.idReport = idReport;
    }
    public Date getReportDate() {
        return this.reportDate;
    }
    
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }
    public String getReportRiciptNo() {
        return this.reportRiciptNo;
    }
    
    public void setReportRiciptNo(String reportRiciptNo) {
        this.reportRiciptNo = reportRiciptNo;
    }
    public Integer getReportRiciptId() {
        return this.reportRiciptId;
    }
    
    public void setReportRiciptId(Integer reportRiciptId) {
        this.reportRiciptId = reportRiciptId;
    }
    public Integer getReportVortId() {
        return this.reportVortId;
    }
    
    public void setReportVortId(Integer reportVortId) {
        this.reportVortId = reportVortId;
    }
    public Integer getReportAccountId() {
        return this.reportAccountId;
    }
    
    public void setReportAccountId(Integer reportAccountId) {
        this.reportAccountId = reportAccountId;
    }
    public Double getReportAmount() {
        return this.reportAmount;
    }
    
    public void setReportAmount(Double reportAmount) {
        this.reportAmount = reportAmount;
    }
    public Integer getReportUserId() {
        return this.reportUserId;
    }
    
    public void setReportUserId(Integer reportUserId) {
        this.reportUserId = reportUserId;
    }
    public Integer getReportApplicationId() {
        return this.reportApplicationId;
    }
    
    public void setReportApplicationId(Integer reportApplicationId) {
        this.reportApplicationId = reportApplicationId;
    }
    public Integer getReportApplicationCatId() {
        return this.reportApplicationCatId;
    }
    
    public void setReportApplicationCatId(Integer reportApplicationCatId) {
        this.reportApplicationCatId = reportApplicationCatId;
    }
    public Integer getReportStatus() {
        return this.reportStatus;
    }
    
    public void setReportStatus(Integer reportStatus) {
        this.reportStatus = reportStatus;
    }
    public Integer getOfficeIdOffice() {
        return this.officeIdOffice;
    }
    
    public void setOfficeIdOffice(Integer officeIdOffice) {
        this.officeIdOffice = officeIdOffice;
    }




}


