package pojo;
// Generated Sep 9, 2019 3:22:27 PM by Hibernate Tools 4.3.1



/**
 * AccountInfo generated by hbm2java
 */
public class AccountInfo  implements java.io.Serializable {


     private Integer idAccountInfo;
     private Integer bankId;
     private Integer appcatId;
     private Integer officeId;
     private Integer accountinfoStatus;
     private String descriptionInfo;

    public AccountInfo() {
    }

    public AccountInfo(Integer bankId, Integer appcatId, Integer officeId, Integer accountinfoStatus, String descriptionInfo) {
       this.bankId = bankId;
       this.appcatId = appcatId;
       this.officeId = officeId;
       this.accountinfoStatus = accountinfoStatus;
       this.descriptionInfo = descriptionInfo;
    }
   
    public Integer getIdAccountInfo() {
        return this.idAccountInfo;
    }
    
    public void setIdAccountInfo(Integer idAccountInfo) {
        this.idAccountInfo = idAccountInfo;
    }
    public Integer getBankId() {
        return this.bankId;
    }
    
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }
    public Integer getAppcatId() {
        return this.appcatId;
    }
    
    public void setAppcatId(Integer appcatId) {
        this.appcatId = appcatId;
    }
    public Integer getOfficeId() {
        return this.officeId;
    }
    
    public void setOfficeId(Integer officeId) {
        this.officeId = officeId;
    }
    public Integer getAccountinfoStatus() {
        return this.accountinfoStatus;
    }
    
    public void setAccountinfoStatus(Integer accountinfoStatus) {
        this.accountinfoStatus = accountinfoStatus;
    }
    public String getDescriptionInfo() {
        return this.descriptionInfo;
    }
    
    public void setDescriptionInfo(String descriptionInfo) {
        this.descriptionInfo = descriptionInfo;
    }




}


