package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AssPayhistry generated by hbm2java
 */
public class AssPayhistry  implements java.io.Serializable {


     private Integer idassPayHistry;
     private Assessment assessment;
     private Integer assPayHistryQcunt;
     private Integer assPayHistryYear;
     private Date assPayHistryDate;
     private Integer assPayHistryStatus;
     private String assPayHistryComment;
     private Double assPayHistryTotalPayid;
     private Double assPayHistryQ1;
     private Double assPayHistryQ2;
     private Double assPayHistryQ3;
     private Double assPayHistryQ4;
     private Double assPayHistryOver;
     private Double assPayHistryDrq1;
     private Double assPayHistryDrq2;
     private Double assPayHistryDrq3;
     private Double assPayHistryDrq4;
     private Integer assPayHistryQ1status;
     private Integer assPayHistryQ2status;
     private Integer assPayHistryQ3status;
     private Integer assPayHistryQ4status;

    public AssPayhistry() {
    }

	
    public AssPayhistry(Assessment assessment) {
        this.assessment = assessment;
    }
    public AssPayhistry(Assessment assessment, Integer assPayHistryQcunt, Integer assPayHistryYear, Date assPayHistryDate, Integer assPayHistryStatus, String assPayHistryComment, Double assPayHistryTotalPayid, Double assPayHistryQ1, Double assPayHistryQ2, Double assPayHistryQ3, Double assPayHistryQ4, Double assPayHistryOver, Double assPayHistryDrq1, Double assPayHistryDrq2, Double assPayHistryDrq3, Double assPayHistryDrq4, Integer assPayHistryQ1status, Integer assPayHistryQ2status, Integer assPayHistryQ3status, Integer assPayHistryQ4status) {
       this.assessment = assessment;
       this.assPayHistryQcunt = assPayHistryQcunt;
       this.assPayHistryYear = assPayHistryYear;
       this.assPayHistryDate = assPayHistryDate;
       this.assPayHistryStatus = assPayHistryStatus;
       this.assPayHistryComment = assPayHistryComment;
       this.assPayHistryTotalPayid = assPayHistryTotalPayid;
       this.assPayHistryQ1 = assPayHistryQ1;
       this.assPayHistryQ2 = assPayHistryQ2;
       this.assPayHistryQ3 = assPayHistryQ3;
       this.assPayHistryQ4 = assPayHistryQ4;
       this.assPayHistryOver = assPayHistryOver;
       this.assPayHistryDrq1 = assPayHistryDrq1;
       this.assPayHistryDrq2 = assPayHistryDrq2;
       this.assPayHistryDrq3 = assPayHistryDrq3;
       this.assPayHistryDrq4 = assPayHistryDrq4;
       this.assPayHistryQ1status = assPayHistryQ1status;
       this.assPayHistryQ2status = assPayHistryQ2status;
       this.assPayHistryQ3status = assPayHistryQ3status;
       this.assPayHistryQ4status = assPayHistryQ4status;
    }
   
    public Integer getIdassPayHistry() {
        return this.idassPayHistry;
    }
    
    public void setIdassPayHistry(Integer idassPayHistry) {
        this.idassPayHistry = idassPayHistry;
    }
    public Assessment getAssessment() {
        return this.assessment;
    }
    
    public void setAssessment(Assessment assessment) {
        this.assessment = assessment;
    }
    public Integer getAssPayHistryQcunt() {
        return this.assPayHistryQcunt;
    }
    
    public void setAssPayHistryQcunt(Integer assPayHistryQcunt) {
        this.assPayHistryQcunt = assPayHistryQcunt;
    }
    public Integer getAssPayHistryYear() {
        return this.assPayHistryYear;
    }
    
    public void setAssPayHistryYear(Integer assPayHistryYear) {
        this.assPayHistryYear = assPayHistryYear;
    }
    public Date getAssPayHistryDate() {
        return this.assPayHistryDate;
    }
    
    public void setAssPayHistryDate(Date assPayHistryDate) {
        this.assPayHistryDate = assPayHistryDate;
    }
    public Integer getAssPayHistryStatus() {
        return this.assPayHistryStatus;
    }
    
    public void setAssPayHistryStatus(Integer assPayHistryStatus) {
        this.assPayHistryStatus = assPayHistryStatus;
    }
    public String getAssPayHistryComment() {
        return this.assPayHistryComment;
    }
    
    public void setAssPayHistryComment(String assPayHistryComment) {
        this.assPayHistryComment = assPayHistryComment;
    }
    public Double getAssPayHistryTotalPayid() {
        return this.assPayHistryTotalPayid;
    }
    
    public void setAssPayHistryTotalPayid(Double assPayHistryTotalPayid) {
        this.assPayHistryTotalPayid = assPayHistryTotalPayid;
    }
    public Double getAssPayHistryQ1() {
        return this.assPayHistryQ1;
    }
    
    public void setAssPayHistryQ1(Double assPayHistryQ1) {
        this.assPayHistryQ1 = assPayHistryQ1;
    }
    public Double getAssPayHistryQ2() {
        return this.assPayHistryQ2;
    }
    
    public void setAssPayHistryQ2(Double assPayHistryQ2) {
        this.assPayHistryQ2 = assPayHistryQ2;
    }
    public Double getAssPayHistryQ3() {
        return this.assPayHistryQ3;
    }
    
    public void setAssPayHistryQ3(Double assPayHistryQ3) {
        this.assPayHistryQ3 = assPayHistryQ3;
    }
    public Double getAssPayHistryQ4() {
        return this.assPayHistryQ4;
    }
    
    public void setAssPayHistryQ4(Double assPayHistryQ4) {
        this.assPayHistryQ4 = assPayHistryQ4;
    }
    public Double getAssPayHistryOver() {
        return this.assPayHistryOver;
    }
    
    public void setAssPayHistryOver(Double assPayHistryOver) {
        this.assPayHistryOver = assPayHistryOver;
    }
    public Double getAssPayHistryDrq1() {
        return this.assPayHistryDrq1;
    }
    
    public void setAssPayHistryDrq1(Double assPayHistryDrq1) {
        this.assPayHistryDrq1 = assPayHistryDrq1;
    }
    public Double getAssPayHistryDrq2() {
        return this.assPayHistryDrq2;
    }
    
    public void setAssPayHistryDrq2(Double assPayHistryDrq2) {
        this.assPayHistryDrq2 = assPayHistryDrq2;
    }
    public Double getAssPayHistryDrq3() {
        return this.assPayHistryDrq3;
    }
    
    public void setAssPayHistryDrq3(Double assPayHistryDrq3) {
        this.assPayHistryDrq3 = assPayHistryDrq3;
    }
    public Double getAssPayHistryDrq4() {
        return this.assPayHistryDrq4;
    }
    
    public void setAssPayHistryDrq4(Double assPayHistryDrq4) {
        this.assPayHistryDrq4 = assPayHistryDrq4;
    }
    public Integer getAssPayHistryQ1status() {
        return this.assPayHistryQ1status;
    }
    
    public void setAssPayHistryQ1status(Integer assPayHistryQ1status) {
        this.assPayHistryQ1status = assPayHistryQ1status;
    }
    public Integer getAssPayHistryQ2status() {
        return this.assPayHistryQ2status;
    }
    
    public void setAssPayHistryQ2status(Integer assPayHistryQ2status) {
        this.assPayHistryQ2status = assPayHistryQ2status;
    }
    public Integer getAssPayHistryQ3status() {
        return this.assPayHistryQ3status;
    }
    
    public void setAssPayHistryQ3status(Integer assPayHistryQ3status) {
        this.assPayHistryQ3status = assPayHistryQ3status;
    }
    public Integer getAssPayHistryQ4status() {
        return this.assPayHistryQ4status;
    }
    
    public void setAssPayHistryQ4status(Integer assPayHistryQ4status) {
        this.assPayHistryQ4status = assPayHistryQ4status;
    }




}


