package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1



/**
 * BaQuestionDetails generated by hbm2java
 */
public class BaQuestionDetails  implements java.io.Serializable {


     private Integer questionDetailId;
     private Integer questionId;
     private String answerList;
     private Integer controlId;
     private Integer status;

    public BaQuestionDetails() {
    }

    public BaQuestionDetails(Integer questionId, String answerList, Integer controlId, Integer status) {
       this.questionId = questionId;
       this.answerList = answerList;
       this.controlId = controlId;
       this.status = status;
    }
   
    public Integer getQuestionDetailId() {
        return this.questionDetailId;
    }
    
    public void setQuestionDetailId(Integer questionDetailId) {
        this.questionDetailId = questionDetailId;
    }
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public String getAnswerList() {
        return this.answerList;
    }
    
    public void setAnswerList(String answerList) {
        this.answerList = answerList;
    }
    public Integer getControlId() {
        return this.controlId;
    }
    
    public void setControlId(Integer controlId) {
        this.controlId = controlId;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


