package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1



/**
 * BaToCheckList generated by hbm2java
 */
public class BaToCheckList  implements java.io.Serializable {


     private Integer questionId;
     private String question;
     private Integer status;

    public BaToCheckList() {
    }

    public BaToCheckList(String question, Integer status) {
       this.question = question;
       this.status = status;
    }
   
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


