package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bophascommettee generated by hbm2java
 */
public class Bophascommettee  implements java.io.Serializable {


     private Integer idBopHasCommettee;
     private Bop bop;
     private String regulations;
     private String comment;
     private Set<BopRegCon> bopRegCons = new HashSet<BopRegCon>(0);
     private Set<Commetteemembers> commetteememberses = new HashSet<Commetteemembers>(0);

    public Bophascommettee() {
    }

    public Bophascommettee(Bop bop, String regulations, String comment, Set<BopRegCon> bopRegCons, Set<Commetteemembers> commetteememberses) {
       this.bop = bop;
       this.regulations = regulations;
       this.comment = comment;
       this.bopRegCons = bopRegCons;
       this.commetteememberses = commetteememberses;
    }
   
    public Integer getIdBopHasCommettee() {
        return this.idBopHasCommettee;
    }
    
    public void setIdBopHasCommettee(Integer idBopHasCommettee) {
        this.idBopHasCommettee = idBopHasCommettee;
    }
    public Bop getBop() {
        return this.bop;
    }
    
    public void setBop(Bop bop) {
        this.bop = bop;
    }
    public String getRegulations() {
        return this.regulations;
    }
    
    public void setRegulations(String regulations) {
        this.regulations = regulations;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<BopRegCon> getBopRegCons() {
        return this.bopRegCons;
    }
    
    public void setBopRegCons(Set<BopRegCon> bopRegCons) {
        this.bopRegCons = bopRegCons;
    }
    public Set<Commetteemembers> getCommetteememberses() {
        return this.commetteememberses;
    }
    
    public void setCommetteememberses(Set<Commetteemembers> commetteememberses) {
        this.commetteememberses = commetteememberses;
    }




}


