package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * De generated by hbm2java
 */
public class De  implements java.io.Serializable {


     private Integer idde;
     private Integer receiptId;
     private Integer appcatId;
     private Integer userId;
     private Integer staus;
     private Date dayendtime;
     private String comment;
     private Date receiptDate;

    public De() {
    }

    public De(Integer receiptId, Integer appcatId, Integer userId, Integer staus, Date dayendtime, String comment, Date receiptDate) {
       this.receiptId = receiptId;
       this.appcatId = appcatId;
       this.userId = userId;
       this.staus = staus;
       this.dayendtime = dayendtime;
       this.comment = comment;
       this.receiptDate = receiptDate;
    }
   
    public Integer getIdde() {
        return this.idde;
    }
    
    public void setIdde(Integer idde) {
        this.idde = idde;
    }
    public Integer getReceiptId() {
        return this.receiptId;
    }
    
    public void setReceiptId(Integer receiptId) {
        this.receiptId = receiptId;
    }
    public Integer getAppcatId() {
        return this.appcatId;
    }
    
    public void setAppcatId(Integer appcatId) {
        this.appcatId = appcatId;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getStaus() {
        return this.staus;
    }
    
    public void setStaus(Integer staus) {
        this.staus = staus;
    }
    public Date getDayendtime() {
        return this.dayendtime;
    }
    
    public void setDayendtime(Date dayendtime) {
        this.dayendtime = dayendtime;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getReceiptDate() {
        return this.receiptDate;
    }
    
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }




}


