package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1



/**
 * GaliHasEmploye generated by hbm2java
 */
public class GaliHasEmploye  implements java.io.Serializable {


     private Integer idGaliHasEmploye;
     private Employe employe;
     private Gali gali;

    public GaliHasEmploye() {
    }

    public GaliHasEmploye(Employe employe, Gali gali) {
       this.employe = employe;
       this.gali = gali;
    }
   
    public Integer getIdGaliHasEmploye() {
        return this.idGaliHasEmploye;
    }
    
    public void setIdGaliHasEmploye(Integer idGaliHasEmploye) {
        this.idGaliHasEmploye = idGaliHasEmploye;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public Gali getGali() {
        return this.gali;
    }
    
    public void setGali(Gali gali) {
        this.gali = gali;
    }




}


