package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gnd generated by hbm2java
 */
public class Gnd  implements java.io.Serializable {


     private Integer idGnd;
     private String gndName;
     private String gndCode;
     private Set<Userhasdivition> userhasdivitions = new HashSet<Userhasdivition>(0);

    public Gnd() {
    }

    public Gnd(String gndName, String gndCode, Set<Userhasdivition> userhasdivitions) {
       this.gndName = gndName;
       this.gndCode = gndCode;
       this.userhasdivitions = userhasdivitions;
    }
   
    public Integer getIdGnd() {
        return this.idGnd;
    }
    
    public void setIdGnd(Integer idGnd) {
        this.idGnd = idGnd;
    }
    public String getGndName() {
        return this.gndName;
    }
    
    public void setGndName(String gndName) {
        this.gndName = gndName;
    }
    public String getGndCode() {
        return this.gndCode;
    }
    
    public void setGndCode(String gndCode) {
        this.gndCode = gndCode;
    }
    public Set<Userhasdivition> getUserhasdivitions() {
        return this.userhasdivitions;
    }
    
    public void setUserhasdivitions(Set<Userhasdivition> userhasdivitions) {
        this.userhasdivitions = userhasdivitions;
    }




}


