package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grade generated by hbm2java
 */
public class Grade  implements java.io.Serializable {


     private Integer idGrade;
     private String employeType;
     private Set<Employe> employes = new HashSet<Employe>(0);

    public Grade() {
    }

    public Grade(String employeType, Set<Employe> employes) {
       this.employeType = employeType;
       this.employes = employes;
    }
   
    public Integer getIdGrade() {
        return this.idGrade;
    }
    
    public void setIdGrade(Integer idGrade) {
        this.idGrade = idGrade;
    }
    public String getEmployeType() {
        return this.employeType;
    }
    
    public void setEmployeType(String employeType) {
        this.employeType = employeType;
    }
    public Set<Employe> getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set<Employe> employes) {
        this.employes = employes;
    }




}


