package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mixintype generated by hbm2java
 */
public class Mixintype  implements java.io.Serializable {


     private Integer idMixintype;
     private AccountReceiptTitle accountReceiptTitle;
     private String mixintypeName;
     private Integer mixintypeStatus;
     private Integer bankinfoIdBank;
     private Integer activeStatus;
     private Integer officeId;
     private Integer extraInt;
     private String extraString;
     private Set<Mixdata> mixdatas = new HashSet<Mixdata>(0);

    public Mixintype() {
    }

    public Mixintype(AccountReceiptTitle accountReceiptTitle, String mixintypeName, Integer mixintypeStatus, Integer bankinfoIdBank, Integer activeStatus, Integer officeId, Integer extraInt, String extraString, Set<Mixdata> mixdatas) {
       this.accountReceiptTitle = accountReceiptTitle;
       this.mixintypeName = mixintypeName;
       this.mixintypeStatus = mixintypeStatus;
       this.bankinfoIdBank = bankinfoIdBank;
       this.activeStatus = activeStatus;
       this.officeId = officeId;
       this.extraInt = extraInt;
       this.extraString = extraString;
       this.mixdatas = mixdatas;
    }
   
    public Integer getIdMixintype() {
        return this.idMixintype;
    }
    
    public void setIdMixintype(Integer idMixintype) {
        this.idMixintype = idMixintype;
    }
    public AccountReceiptTitle getAccountReceiptTitle() {
        return this.accountReceiptTitle;
    }
    
    public void setAccountReceiptTitle(AccountReceiptTitle accountReceiptTitle) {
        this.accountReceiptTitle = accountReceiptTitle;
    }
    public String getMixintypeName() {
        return this.mixintypeName;
    }
    
    public void setMixintypeName(String mixintypeName) {
        this.mixintypeName = mixintypeName;
    }
    public Integer getMixintypeStatus() {
        return this.mixintypeStatus;
    }
    
    public void setMixintypeStatus(Integer mixintypeStatus) {
        this.mixintypeStatus = mixintypeStatus;
    }
    public Integer getBankinfoIdBank() {
        return this.bankinfoIdBank;
    }
    
    public void setBankinfoIdBank(Integer bankinfoIdBank) {
        this.bankinfoIdBank = bankinfoIdBank;
    }
    public Integer getActiveStatus() {
        return this.activeStatus;
    }
    
    public void setActiveStatus(Integer activeStatus) {
        this.activeStatus = activeStatus;
    }
    public Integer getOfficeId() {
        return this.officeId;
    }
    
    public void setOfficeId(Integer officeId) {
        this.officeId = officeId;
    }
    public Integer getExtraInt() {
        return this.extraInt;
    }
    
    public void setExtraInt(Integer extraInt) {
        this.extraInt = extraInt;
    }
    public String getExtraString() {
        return this.extraString;
    }
    
    public void setExtraString(String extraString) {
        this.extraString = extraString;
    }
    public Set<Mixdata> getMixdatas() {
        return this.mixdatas;
    }
    
    public void setMixdatas(Set<Mixdata> mixdatas) {
        this.mixdatas = mixdatas;
    }




}


