package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Privilage generated by hbm2java
 */
public class Privilage  implements java.io.Serializable {


     private Integer idPrivilage;
     private String view;
     private String btn;
     private Double arange;
     private String type;
     private Set<UserHasPrivilage> userHasPrivilages = new HashSet<UserHasPrivilage>(0);

    public Privilage() {
    }

    public Privilage(String view, String btn, Double arange, String type, Set<UserHasPrivilage> userHasPrivilages) {
       this.view = view;
       this.btn = btn;
       this.arange = arange;
       this.type = type;
       this.userHasPrivilages = userHasPrivilages;
    }
   
    public Integer getIdPrivilage() {
        return this.idPrivilage;
    }
    
    public void setIdPrivilage(Integer idPrivilage) {
        this.idPrivilage = idPrivilage;
    }
    public String getView() {
        return this.view;
    }
    
    public void setView(String view) {
        this.view = view;
    }
    public String getBtn() {
        return this.btn;
    }
    
    public void setBtn(String btn) {
        this.btn = btn;
    }
    public Double getArange() {
        return this.arange;
    }
    
    public void setArange(Double arange) {
        this.arange = arange;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<UserHasPrivilage> getUserHasPrivilages() {
        return this.userHasPrivilages;
    }
    
    public void setUserHasPrivilages(Set<UserHasPrivilage> userHasPrivilages) {
        this.userHasPrivilages = userHasPrivilages;
    }




}


