package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SlLaType generated by hbm2java
 */
public class SlLaType  implements java.io.Serializable {


     private Integer laTypeId;
     private String laType;
     private Set<SlSabhaType> slSabhaTypes = new HashSet<SlSabhaType>(0);

    public SlLaType() {
    }

    public SlLaType(String laType, Set<SlSabhaType> slSabhaTypes) {
       this.laType = laType;
       this.slSabhaTypes = slSabhaTypes;
    }
   
    public Integer getLaTypeId() {
        return this.laTypeId;
    }
    
    public void setLaTypeId(Integer laTypeId) {
        this.laTypeId = laTypeId;
    }
    public String getLaType() {
        return this.laType;
    }
    
    public void setLaType(String laType) {
        this.laType = laType;
    }
    public Set<SlSabhaType> getSlSabhaTypes() {
        return this.slSabhaTypes;
    }
    
    public void setSlSabhaTypes(Set<SlSabhaType> slSabhaTypes) {
        this.slSabhaTypes = slSabhaTypes;
    }




}


