package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1



/**
 * SlUploadImages generated by hbm2java
 */
public class SlUploadImages  implements java.io.Serializable {


     private Integer imageId;
     private String nicPath;
     private String docPath;
     private String nvDocPath;
     private String docWebPath;

    public SlUploadImages() {
    }

    public SlUploadImages(String nicPath, String docPath, String nvDocPath, String docWebPath) {
       this.nicPath = nicPath;
       this.docPath = docPath;
       this.nvDocPath = nvDocPath;
       this.docWebPath = docWebPath;
    }
   
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }
    public String getNicPath() {
        return this.nicPath;
    }
    
    public void setNicPath(String nicPath) {
        this.nicPath = nicPath;
    }
    public String getDocPath() {
        return this.docPath;
    }
    
    public void setDocPath(String docPath) {
        this.docPath = docPath;
    }
    public String getNvDocPath() {
        return this.nvDocPath;
    }
    
    public void setNvDocPath(String nvDocPath) {
        this.nvDocPath = nvDocPath;
    }
    public String getDocWebPath() {
        return this.docWebPath;
    }
    
    public void setDocWebPath(String docWebPath) {
        this.docWebPath = docWebPath;
    }




}


