package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SrShopPaymentCrossTbl generated by hbm2java
 */
public class SrShopPaymentCrossTbl  implements java.io.Serializable {


     private Integer srShopPayment2Id;
     private SrShop srShop;
     private Integer srShopPayment2VoteId;
     private Double srShopPayment2Amount;
     private Integer srShopPayment2AccountId;
     private String srShopPayment2ReceiptNo;
     private Date srShopPayment2Date;
     private Date srShopPayment2Time;
     private Integer srShopPayment2User;
     private Integer srShopPayment2CompleteOrNot;

    public SrShopPaymentCrossTbl() {
    }

    public SrShopPaymentCrossTbl(SrShop srShop, Integer srShopPayment2VoteId, Double srShopPayment2Amount, Integer srShopPayment2AccountId, String srShopPayment2ReceiptNo, Date srShopPayment2Date, Date srShopPayment2Time, Integer srShopPayment2User, Integer srShopPayment2CompleteOrNot) {
       this.srShop = srShop;
       this.srShopPayment2VoteId = srShopPayment2VoteId;
       this.srShopPayment2Amount = srShopPayment2Amount;
       this.srShopPayment2AccountId = srShopPayment2AccountId;
       this.srShopPayment2ReceiptNo = srShopPayment2ReceiptNo;
       this.srShopPayment2Date = srShopPayment2Date;
       this.srShopPayment2Time = srShopPayment2Time;
       this.srShopPayment2User = srShopPayment2User;
       this.srShopPayment2CompleteOrNot = srShopPayment2CompleteOrNot;
    }
   
    public Integer getSrShopPayment2Id() {
        return this.srShopPayment2Id;
    }
    
    public void setSrShopPayment2Id(Integer srShopPayment2Id) {
        this.srShopPayment2Id = srShopPayment2Id;
    }
    public SrShop getSrShop() {
        return this.srShop;
    }
    
    public void setSrShop(SrShop srShop) {
        this.srShop = srShop;
    }
    public Integer getSrShopPayment2VoteId() {
        return this.srShopPayment2VoteId;
    }
    
    public void setSrShopPayment2VoteId(Integer srShopPayment2VoteId) {
        this.srShopPayment2VoteId = srShopPayment2VoteId;
    }
    public Double getSrShopPayment2Amount() {
        return this.srShopPayment2Amount;
    }
    
    public void setSrShopPayment2Amount(Double srShopPayment2Amount) {
        this.srShopPayment2Amount = srShopPayment2Amount;
    }
    public Integer getSrShopPayment2AccountId() {
        return this.srShopPayment2AccountId;
    }
    
    public void setSrShopPayment2AccountId(Integer srShopPayment2AccountId) {
        this.srShopPayment2AccountId = srShopPayment2AccountId;
    }
    public String getSrShopPayment2ReceiptNo() {
        return this.srShopPayment2ReceiptNo;
    }
    
    public void setSrShopPayment2ReceiptNo(String srShopPayment2ReceiptNo) {
        this.srShopPayment2ReceiptNo = srShopPayment2ReceiptNo;
    }
    public Date getSrShopPayment2Date() {
        return this.srShopPayment2Date;
    }
    
    public void setSrShopPayment2Date(Date srShopPayment2Date) {
        this.srShopPayment2Date = srShopPayment2Date;
    }
    public Date getSrShopPayment2Time() {
        return this.srShopPayment2Time;
    }
    
    public void setSrShopPayment2Time(Date srShopPayment2Time) {
        this.srShopPayment2Time = srShopPayment2Time;
    }
    public Integer getSrShopPayment2User() {
        return this.srShopPayment2User;
    }
    
    public void setSrShopPayment2User(Integer srShopPayment2User) {
        this.srShopPayment2User = srShopPayment2User;
    }
    public Integer getSrShopPayment2CompleteOrNot() {
        return this.srShopPayment2CompleteOrNot;
    }
    
    public void setSrShopPayment2CompleteOrNot(Integer srShopPayment2CompleteOrNot) {
        this.srShopPayment2CompleteOrNot = srShopPayment2CompleteOrNot;
    }




}


