package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrShopValues generated by hbm2java
 */
public class SrShopValues  implements java.io.Serializable {


     private Integer srShopValueId;
     private String srShopValueCategoryName;
     private Double srShopValueRental;
     private Double srShopValueFine;
     private Double srShopValueOther1;
     private Double srShopValueOther2;
     private Double srShopValueOther3;
     private Integer srShopValueStamp;
     private Integer srShopValueVat;
     private Integer srShopValueNbt;
     private Integer srShopValueVatid;
     private Integer srShopValueNbtid;
     private Integer srShopValueStampid;
     private Set<SrShopHasValue> srShopHasValues = new HashSet<SrShopHasValue>(0);

    public SrShopValues() {
    }

    public SrShopValues(String srShopValueCategoryName, Double srShopValueRental, Double srShopValueFine, Double srShopValueOther1, Double srShopValueOther2, Double srShopValueOther3, Integer srShopValueStamp, Integer srShopValueVat, Integer srShopValueNbt, Integer srShopValueVatid, Integer srShopValueNbtid, Integer srShopValueStampid, Set<SrShopHasValue> srShopHasValues) {
       this.srShopValueCategoryName = srShopValueCategoryName;
       this.srShopValueRental = srShopValueRental;
       this.srShopValueFine = srShopValueFine;
       this.srShopValueOther1 = srShopValueOther1;
       this.srShopValueOther2 = srShopValueOther2;
       this.srShopValueOther3 = srShopValueOther3;
       this.srShopValueStamp = srShopValueStamp;
       this.srShopValueVat = srShopValueVat;
       this.srShopValueNbt = srShopValueNbt;
       this.srShopValueVatid = srShopValueVatid;
       this.srShopValueNbtid = srShopValueNbtid;
       this.srShopValueStampid = srShopValueStampid;
       this.srShopHasValues = srShopHasValues;
    }
   
    public Integer getSrShopValueId() {
        return this.srShopValueId;
    }
    
    public void setSrShopValueId(Integer srShopValueId) {
        this.srShopValueId = srShopValueId;
    }
    public String getSrShopValueCategoryName() {
        return this.srShopValueCategoryName;
    }
    
    public void setSrShopValueCategoryName(String srShopValueCategoryName) {
        this.srShopValueCategoryName = srShopValueCategoryName;
    }
    public Double getSrShopValueRental() {
        return this.srShopValueRental;
    }
    
    public void setSrShopValueRental(Double srShopValueRental) {
        this.srShopValueRental = srShopValueRental;
    }
    public Double getSrShopValueFine() {
        return this.srShopValueFine;
    }
    
    public void setSrShopValueFine(Double srShopValueFine) {
        this.srShopValueFine = srShopValueFine;
    }
    public Double getSrShopValueOther1() {
        return this.srShopValueOther1;
    }
    
    public void setSrShopValueOther1(Double srShopValueOther1) {
        this.srShopValueOther1 = srShopValueOther1;
    }
    public Double getSrShopValueOther2() {
        return this.srShopValueOther2;
    }
    
    public void setSrShopValueOther2(Double srShopValueOther2) {
        this.srShopValueOther2 = srShopValueOther2;
    }
    public Double getSrShopValueOther3() {
        return this.srShopValueOther3;
    }
    
    public void setSrShopValueOther3(Double srShopValueOther3) {
        this.srShopValueOther3 = srShopValueOther3;
    }
    public Integer getSrShopValueStamp() {
        return this.srShopValueStamp;
    }
    
    public void setSrShopValueStamp(Integer srShopValueStamp) {
        this.srShopValueStamp = srShopValueStamp;
    }
    public Integer getSrShopValueVat() {
        return this.srShopValueVat;
    }
    
    public void setSrShopValueVat(Integer srShopValueVat) {
        this.srShopValueVat = srShopValueVat;
    }
    public Integer getSrShopValueNbt() {
        return this.srShopValueNbt;
    }
    
    public void setSrShopValueNbt(Integer srShopValueNbt) {
        this.srShopValueNbt = srShopValueNbt;
    }
    public Integer getSrShopValueVatid() {
        return this.srShopValueVatid;
    }
    
    public void setSrShopValueVatid(Integer srShopValueVatid) {
        this.srShopValueVatid = srShopValueVatid;
    }
    public Integer getSrShopValueNbtid() {
        return this.srShopValueNbtid;
    }
    
    public void setSrShopValueNbtid(Integer srShopValueNbtid) {
        this.srShopValueNbtid = srShopValueNbtid;
    }
    public Integer getSrShopValueStampid() {
        return this.srShopValueStampid;
    }
    
    public void setSrShopValueStampid(Integer srShopValueStampid) {
        this.srShopValueStampid = srShopValueStampid;
    }
    public Set<SrShopHasValue> getSrShopHasValues() {
        return this.srShopHasValues;
    }
    
    public void setSrShopHasValues(Set<SrShopHasValue> srShopHasValues) {
        this.srShopHasValues = srShopHasValues;
    }




}


