package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1



/**
 * UserHasPrivilage generated by hbm2java
 */
public class UserHasPrivilage  implements java.io.Serializable {


     private Integer idUserHasPrivilage;
     private Privilage privilage;
     private User user;
     private Integer userHasPrivilageStatus;
     private Integer userHasPrivilageSyn;

    public UserHasPrivilage() {
    }

	
    public UserHasPrivilage(Privilage privilage, User user) {
        this.privilage = privilage;
        this.user = user;
    }
    public UserHasPrivilage(Privilage privilage, User user, Integer userHasPrivilageStatus, Integer userHasPrivilageSyn) {
       this.privilage = privilage;
       this.user = user;
       this.userHasPrivilageStatus = userHasPrivilageStatus;
       this.userHasPrivilageSyn = userHasPrivilageSyn;
    }
   
    public Integer getIdUserHasPrivilage() {
        return this.idUserHasPrivilage;
    }
    
    public void setIdUserHasPrivilage(Integer idUserHasPrivilage) {
        this.idUserHasPrivilage = idUserHasPrivilage;
    }
    public Privilage getPrivilage() {
        return this.privilage;
    }
    
    public void setPrivilage(Privilage privilage) {
        this.privilage = privilage;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getUserHasPrivilageStatus() {
        return this.userHasPrivilageStatus;
    }
    
    public void setUserHasPrivilageStatus(Integer userHasPrivilageStatus) {
        this.userHasPrivilageStatus = userHasPrivilageStatus;
    }
    public Integer getUserHasPrivilageSyn() {
        return this.userHasPrivilageSyn;
    }
    
    public void setUserHasPrivilageSyn(Integer userHasPrivilageSyn) {
        this.userHasPrivilageSyn = userHasPrivilageSyn;
    }




}


