package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1



/**
 * UserHasApprovalCat generated by hbm2java
 */
public class UserHasApprovalCat  implements java.io.Serializable {


     private Integer idUserHasApprovalCat;
     private ApprovalCat approvalCat;
     private User user;
     private Integer dipStatus;
     private Integer dipSyn;

    public UserHasApprovalCat() {
    }

	
    public UserHasApprovalCat(ApprovalCat approvalCat, User user) {
        this.approvalCat = approvalCat;
        this.user = user;
    }
    public UserHasApprovalCat(ApprovalCat approvalCat, User user, Integer dipStatus, Integer dipSyn) {
       this.approvalCat = approvalCat;
       this.user = user;
       this.dipStatus = dipStatus;
       this.dipSyn = dipSyn;
    }
   
    public Integer getIdUserHasApprovalCat() {
        return this.idUserHasApprovalCat;
    }
    
    public void setIdUserHasApprovalCat(Integer idUserHasApprovalCat) {
        this.idUserHasApprovalCat = idUserHasApprovalCat;
    }
    public ApprovalCat getApprovalCat() {
        return this.approvalCat;
    }
    
    public void setApprovalCat(ApprovalCat approvalCat) {
        this.approvalCat = approvalCat;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getDipStatus() {
        return this.dipStatus;
    }
    
    public void setDipStatus(Integer dipStatus) {
        this.dipStatus = dipStatus;
    }
    public Integer getDipSyn() {
        return this.dipSyn;
    }
    
    public void setDipSyn(Integer dipSyn) {
        this.dipSyn = dipSyn;
    }




}


