package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1



/**
 * WaterCus generated by hbm2java
 */
public class WaterCus  implements java.io.Serializable {


     private int id;
     private Integer customerId;
     private Integer waterId;

    public WaterCus() {
    }

	
    public WaterCus(int id) {
        this.id = id;
    }
    public WaterCus(int id, Integer customerId, Integer waterId) {
       this.id = id;
       this.customerId = customerId;
       this.waterId = waterId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Integer getWaterId() {
        return this.waterId;
    }
    
    public void setWaterId(Integer waterId) {
        this.waterId = waterId;
    }




}


