package pojo;
// Generated Sep 6, 2019 4:30:16 PM by Hibernate Tools 4.3.1



/**
 * Watter generated by hbm2java
 */
public class Watter  implements java.io.Serializable {


     private Integer idWatter;

    public Watter() {
    }

   
    public Integer getIdWatter() {
        return this.idWatter;
    }
    
    public void setIdWatter(Integer idWatter) {
        this.idWatter = idWatter;
    }




}


