package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WbMCustomer generated by hbm2java
 */
public class WbMCustomer  implements java.io.Serializable {


     private String cusId;
     private WbMDevision wbMDevision;
     private WbMNature wbMNature;
     private WbMSubRoad wbMSubRoad;
     private String nic;
     private String name;
     private String address;
     private String ownerName;
     private String taxNo;
     private Date regDate;
     private Double securityDeposit;
     private Double estimateAmount;
     private String status;
     private String meterNo;
     private String hasMeter;
     private Double monthlyAmount;
     private Set<WbTCustomerRoad> wbTCustomerRoads = new HashSet<WbTCustomerRoad>(0);
     private WbYearlyNonMeteredProcess wbYearlyNonMeteredProcess;
     private WbNonmeteredArrears1 wbNonmeteredArrears1;
     private WbYearlyMeteredProcess wbYearlyMeteredProcess;
     private Set<WbTCusInvoice> wbTCusInvoices = new HashSet<WbTCusInvoice>(0);
     private WbNonmeteredArrears wbNonmeteredArrears;

    public WbMCustomer() {
    }

	
    public WbMCustomer(String cusId, WbMNature wbMNature, WbMSubRoad wbMSubRoad, String address, String status) {
        this.cusId = cusId;
        this.wbMNature = wbMNature;
        this.wbMSubRoad = wbMSubRoad;
        this.address = address;
        this.status = status;
    }
    public WbMCustomer(String cusId, WbMDevision wbMDevision, WbMNature wbMNature, WbMSubRoad wbMSubRoad, String nic, String name, String address, String ownerName, String taxNo, Date regDate, Double securityDeposit, Double estimateAmount, String status, String meterNo, String hasMeter, Double monthlyAmount, Set<WbTCustomerRoad> wbTCustomerRoads, WbYearlyNonMeteredProcess wbYearlyNonMeteredProcess, WbNonmeteredArrears1 wbNonmeteredArrears1, WbYearlyMeteredProcess wbYearlyMeteredProcess, Set<WbTCusInvoice> wbTCusInvoices, WbNonmeteredArrears wbNonmeteredArrears) {
       this.cusId = cusId;
       this.wbMDevision = wbMDevision;
       this.wbMNature = wbMNature;
       this.wbMSubRoad = wbMSubRoad;
       this.nic = nic;
       this.name = name;
       this.address = address;
       this.ownerName = ownerName;
       this.taxNo = taxNo;
       this.regDate = regDate;
       this.securityDeposit = securityDeposit;
       this.estimateAmount = estimateAmount;
       this.status = status;
       this.meterNo = meterNo;
       this.hasMeter = hasMeter;
       this.monthlyAmount = monthlyAmount;
       this.wbTCustomerRoads = wbTCustomerRoads;
       this.wbYearlyNonMeteredProcess = wbYearlyNonMeteredProcess;
       this.wbNonmeteredArrears1 = wbNonmeteredArrears1;
       this.wbYearlyMeteredProcess = wbYearlyMeteredProcess;
       this.wbTCusInvoices = wbTCusInvoices;
       this.wbNonmeteredArrears = wbNonmeteredArrears;
    }
   
    public String getCusId() {
        return this.cusId;
    }
    
    public void setCusId(String cusId) {
        this.cusId = cusId;
    }
    public WbMDevision getWbMDevision() {
        return this.wbMDevision;
    }
    
    public void setWbMDevision(WbMDevision wbMDevision) {
        this.wbMDevision = wbMDevision;
    }
    public WbMNature getWbMNature() {
        return this.wbMNature;
    }
    
    public void setWbMNature(WbMNature wbMNature) {
        this.wbMNature = wbMNature;
    }
    public WbMSubRoad getWbMSubRoad() {
        return this.wbMSubRoad;
    }
    
    public void setWbMSubRoad(WbMSubRoad wbMSubRoad) {
        this.wbMSubRoad = wbMSubRoad;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getOwnerName() {
        return this.ownerName;
    }
    
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    public String getTaxNo() {
        return this.taxNo;
    }
    
    public void setTaxNo(String taxNo) {
        this.taxNo = taxNo;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public Double getSecurityDeposit() {
        return this.securityDeposit;
    }
    
    public void setSecurityDeposit(Double securityDeposit) {
        this.securityDeposit = securityDeposit;
    }
    public Double getEstimateAmount() {
        return this.estimateAmount;
    }
    
    public void setEstimateAmount(Double estimateAmount) {
        this.estimateAmount = estimateAmount;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getMeterNo() {
        return this.meterNo;
    }
    
    public void setMeterNo(String meterNo) {
        this.meterNo = meterNo;
    }
    public String getHasMeter() {
        return this.hasMeter;
    }
    
    public void setHasMeter(String hasMeter) {
        this.hasMeter = hasMeter;
    }
    public Double getMonthlyAmount() {
        return this.monthlyAmount;
    }
    
    public void setMonthlyAmount(Double monthlyAmount) {
        this.monthlyAmount = monthlyAmount;
    }
    public Set<WbTCustomerRoad> getWbTCustomerRoads() {
        return this.wbTCustomerRoads;
    }
    
    public void setWbTCustomerRoads(Set<WbTCustomerRoad> wbTCustomerRoads) {
        this.wbTCustomerRoads = wbTCustomerRoads;
    }
    public WbYearlyNonMeteredProcess getWbYearlyNonMeteredProcess() {
        return this.wbYearlyNonMeteredProcess;
    }
    
    public void setWbYearlyNonMeteredProcess(WbYearlyNonMeteredProcess wbYearlyNonMeteredProcess) {
        this.wbYearlyNonMeteredProcess = wbYearlyNonMeteredProcess;
    }
    public WbNonmeteredArrears1 getWbNonmeteredArrears1() {
        return this.wbNonmeteredArrears1;
    }
    
    public void setWbNonmeteredArrears1(WbNonmeteredArrears1 wbNonmeteredArrears1) {
        this.wbNonmeteredArrears1 = wbNonmeteredArrears1;
    }
    public WbYearlyMeteredProcess getWbYearlyMeteredProcess() {
        return this.wbYearlyMeteredProcess;
    }
    
    public void setWbYearlyMeteredProcess(WbYearlyMeteredProcess wbYearlyMeteredProcess) {
        this.wbYearlyMeteredProcess = wbYearlyMeteredProcess;
    }
    public Set<WbTCusInvoice> getWbTCusInvoices() {
        return this.wbTCusInvoices;
    }
    
    public void setWbTCusInvoices(Set<WbTCusInvoice> wbTCusInvoices) {
        this.wbTCusInvoices = wbTCusInvoices;
    }
    public WbNonmeteredArrears getWbNonmeteredArrears() {
        return this.wbNonmeteredArrears;
    }
    
    public void setWbNonmeteredArrears(WbNonmeteredArrears wbNonmeteredArrears) {
        this.wbNonmeteredArrears = wbNonmeteredArrears;
    }




}


