package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1



/**
 * WbMDataClearTbl generated by hbm2java
 */
public class WbMDataClearTbl  implements java.io.Serializable {


     private Integer wbMDataClearTblId;
     private WbMConnection wbMConnection;
     private Integer wbMWaterCusId;
     private Integer wbMWaterConId;
     private Integer wbMNicCusId;
     private String wbMNicNicno;
     private Integer wbMAssCusId;
     private Integer wbMAssAssId;
     private String wbMAssNo;

    public WbMDataClearTbl() {
    }

    public WbMDataClearTbl(WbMConnection wbMConnection, Integer wbMWaterCusId, Integer wbMWaterConId, Integer wbMNicCusId, String wbMNicNicno, Integer wbMAssCusId, Integer wbMAssAssId, String wbMAssNo) {
       this.wbMConnection = wbMConnection;
       this.wbMWaterCusId = wbMWaterCusId;
       this.wbMWaterConId = wbMWaterConId;
       this.wbMNicCusId = wbMNicCusId;
       this.wbMNicNicno = wbMNicNicno;
       this.wbMAssCusId = wbMAssCusId;
       this.wbMAssAssId = wbMAssAssId;
       this.wbMAssNo = wbMAssNo;
    }
   
    public Integer getWbMDataClearTblId() {
        return this.wbMDataClearTblId;
    }
    
    public void setWbMDataClearTblId(Integer wbMDataClearTblId) {
        this.wbMDataClearTblId = wbMDataClearTblId;
    }
    public WbMConnection getWbMConnection() {
        return this.wbMConnection;
    }
    
    public void setWbMConnection(WbMConnection wbMConnection) {
        this.wbMConnection = wbMConnection;
    }
    public Integer getWbMWaterCusId() {
        return this.wbMWaterCusId;
    }
    
    public void setWbMWaterCusId(Integer wbMWaterCusId) {
        this.wbMWaterCusId = wbMWaterCusId;
    }
    public Integer getWbMWaterConId() {
        return this.wbMWaterConId;
    }
    
    public void setWbMWaterConId(Integer wbMWaterConId) {
        this.wbMWaterConId = wbMWaterConId;
    }
    public Integer getWbMNicCusId() {
        return this.wbMNicCusId;
    }
    
    public void setWbMNicCusId(Integer wbMNicCusId) {
        this.wbMNicCusId = wbMNicCusId;
    }
    public String getWbMNicNicno() {
        return this.wbMNicNicno;
    }
    
    public void setWbMNicNicno(String wbMNicNicno) {
        this.wbMNicNicno = wbMNicNicno;
    }
    public Integer getWbMAssCusId() {
        return this.wbMAssCusId;
    }
    
    public void setWbMAssCusId(Integer wbMAssCusId) {
        this.wbMAssCusId = wbMAssCusId;
    }
    public Integer getWbMAssAssId() {
        return this.wbMAssAssId;
    }
    
    public void setWbMAssAssId(Integer wbMAssAssId) {
        this.wbMAssAssId = wbMAssAssId;
    }
    public String getWbMAssNo() {
        return this.wbMAssNo;
    }
    
    public void setWbMAssNo(String wbMAssNo) {
        this.wbMAssNo = wbMAssNo;
    }




}


