package pojo;
// Generated Oct 3, 2019 9:56:57 AM by Hibernate Tools 4.3.1



/**
 * WbTCustomerRoad generated by hbm2java
 */
public class WbTCustomerRoad  implements java.io.Serializable {


     private WbTCustomerRoadId id;
     private WbMCustomer wbMCustomer;
     private WbMSubRoad wbMSubRoad;
     private Integer readerId;

    public WbTCustomerRoad() {
    }

	
    public WbTCustomerRoad(WbTCustomerRoadId id, WbMCustomer wbMCustomer) {
        this.id = id;
        this.wbMCustomer = wbMCustomer;
    }
    public WbTCustomerRoad(WbTCustomerRoadId id, WbMCustomer wbMCustomer, WbMSubRoad wbMSubRoad, Integer readerId) {
       this.id = id;
       this.wbMCustomer = wbMCustomer;
       this.wbMSubRoad = wbMSubRoad;
       this.readerId = readerId;
    }
   
    public WbTCustomerRoadId getId() {
        return this.id;
    }
    
    public void setId(WbTCustomerRoadId id) {
        this.id = id;
    }
    public WbMCustomer getWbMCustomer() {
        return this.wbMCustomer;
    }
    
    public void setWbMCustomer(WbMCustomer wbMCustomer) {
        this.wbMCustomer = wbMCustomer;
    }
    public WbMSubRoad getWbMSubRoad() {
        return this.wbMSubRoad;
    }
    
    public void setWbMSubRoad(WbMSubRoad wbMSubRoad) {
        this.wbMSubRoad = wbMSubRoad;
    }
    public Integer getReaderId() {
        return this.readerId;
    }
    
    public void setReaderId(Integer readerId) {
        this.readerId = readerId;
    }




}


